// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ernestrc/go-tui/browser (interfaces: Browser)

// Package mock_browser is a generated GoMock package.
package browser

import (
	reflect "reflect"

	tui "github.com/ernestrc/go-tui"
	term "github.com/ernestrc/go-tui/term"
	gomock "github.com/golang/mock/gomock"
)

// MockBrowser is a mock of Browser interface
type MockBrowser struct {
	ctrl     *gomock.Controller
	recorder *MockBrowserMockRecorder
}

// MockBrowserMockRecorder is the mock recorder for MockBrowser
type MockBrowserMockRecorder struct {
	mock *MockBrowser
}

// NewMockBrowser creates a new mock instance
func NewMockBrowser(ctrl *gomock.Controller) *MockBrowser {
	mock := &MockBrowser{ctrl: ctrl}
	mock.recorder = &MockBrowserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockBrowser) EXPECT() *MockBrowserMockRecorder {
	return m.recorder
}

// Close mocks base method
func (m *MockBrowser) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close
func (mr *MockBrowserMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockBrowser)(nil).Close))
}

// MergeKeyMap mocks base method
func (m *MockBrowser) MergeKeyMap(arg0 map[term.Event]term.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MergeKeyMap", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// MergeKeyMap indicates an expected call of MergeKeyMap
func (mr *MockBrowserMockRecorder) MergeKeyMap(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MergeKeyMap", reflect.TypeOf((*MockBrowser)(nil).MergeKeyMap), arg0)
}

// OpenFile mocks base method
func (m *MockBrowser) OpenFile(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OpenFile", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// OpenFile indicates an expected call of OpenFile
func (mr *MockBrowserMockRecorder) OpenFile(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenFile", reflect.TypeOf((*MockBrowser)(nil).OpenFile), arg0)
}

// SetMessage mocks base method
func (m *MockBrowser) SetMessage(arg0 string, arg1 ...interface{}) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SetMessage", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetMessage indicates an expected call of SetMessage
func (mr *MockBrowserMockRecorder) SetMessage(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMessage", reflect.TypeOf((*MockBrowser)(nil).SetMessage), varargs...)
}

// SplitHorizontalAbove mocks base method
func (m *MockBrowser) SplitHorizontalAbove(arg0 tui.Handler) (Window, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SplitHorizontalAbove", arg0)
	ret0, _ := ret[0].(Window)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SplitHorizontalAbove indicates an expected call of SplitHorizontalAbove
func (mr *MockBrowserMockRecorder) SplitHorizontalAbove(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SplitHorizontalAbove", reflect.TypeOf((*MockBrowser)(nil).SplitHorizontalAbove), arg0)
}

// SplitHorizontalBelow mocks base method
func (m *MockBrowser) SplitHorizontalBelow(arg0 tui.Handler) (Window, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SplitHorizontalBelow", arg0)
	ret0, _ := ret[0].(Window)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SplitHorizontalBelow indicates an expected call of SplitHorizontalBelow
func (mr *MockBrowserMockRecorder) SplitHorizontalBelow(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SplitHorizontalBelow", reflect.TypeOf((*MockBrowser)(nil).SplitHorizontalBelow), arg0)
}

// SplitVerticalLeft mocks base method
func (m *MockBrowser) SplitVerticalLeft(arg0 tui.Handler) (Window, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SplitVerticalLeft", arg0)
	ret0, _ := ret[0].(Window)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SplitVerticalLeft indicates an expected call of SplitVerticalLeft
func (mr *MockBrowserMockRecorder) SplitVerticalLeft(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SplitVerticalLeft", reflect.TypeOf((*MockBrowser)(nil).SplitVerticalLeft), arg0)
}

// SplitVerticalRight mocks base method
func (m *MockBrowser) SplitVerticalRight(arg0 tui.Handler) (Window, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SplitVerticalRight", arg0)
	ret0, _ := ret[0].(Window)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SplitVerticalRight indicates an expected call of SplitVerticalRight
func (mr *MockBrowserMockRecorder) SplitVerticalRight(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SplitVerticalRight", reflect.TypeOf((*MockBrowser)(nil).SplitVerticalRight), arg0)
}

// Subscribe mocks base method
func (m *MockBrowser) Subscribe(arg0 term.Event, arg1 EventHandler) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Subscribe indicates an expected call of Subscribe
func (mr *MockBrowserMockRecorder) Subscribe(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockBrowser)(nil).Subscribe), arg0, arg1)
}
