kind: pipeline
type: docker
name: default

steps:
- name: prepare
  image: us-central1-docker.pkg.dev/unstable-build-blue-dev/docker/go-tui-ci:latest
  privileged: true
  environment:
    GIT_SSH_KEY:
      from_secret: git_ssh_key
  commands:
  - source ci_prepare.sh
  volumes:
    - name: home
      path: /root

- name: lint
  image: us-central1-docker.pkg.dev/unstable-build-blue-dev/docker/go-tui-ci:latest
  pull: always
  privileged: true
  environment:
    GOCACHE: /go/cache
  commands:
    - make lint
  volumes:
    - name: home
      path: /root

- name: license
  image: us-central1-docker.pkg.dev/unstable-build-blue-dev/docker/go-tui-ci:latest
  pull: always
  privileged: true
  environment:
    GOCACHE: /go/cache
  commands:
    - make assert_license
  volumes:
    - name: home
      path: /root

- name: test
  image: us-central1-docker.pkg.dev/unstable-build-blue-dev/docker/go-tui-ci:latest
  pull: always
  privileged: true
  environment:
    GOCACHE: /go/cache
  commands:
  - make debug
  - xvfb-run make test CI="true" GOTESTFLAGS="-race -timeout 400s"
  volumes:
    - name: home
      path: /root

- name: crosscompile
  image: us-central1-docker.pkg.dev/unstable-build-blue-dev/docker/go-tui-ci:latest
  pull: always
  privileged: true
  environment:
    GOCACHE: /go/cache
  commands:
  - make cross-compile
  volumes:
    - name: home
      path: /root

- name: slack
  image: plugins/slack
  when:
    status:
    - failure
    - success
    ref:
    - refs/heads/main
  settings:
    webhook:
      from_secret: slack_webhook_url
    channel: git
    icon_url: https://raw.githubusercontent.com/drone/brand/master/logos/png/dark/drone-logo-png-dark-256.png

trigger:
  event:
  - push
  - pull_request
  ref:
    include:
    - refs/heads/main
    - refs/pull/**
    - refs/tags/**

image_pull_secrets:
- dockerconfig

volumes:
  - name: home
    temp: {}


---
kind: pipeline
name: build-ci-image
type: docker

steps:
- name: push-to-gar
  image: plugins/docker
  environment:
    GIT_SSH_KEY:
      from_secret: git_ssh_key
  settings:
    config:
      from_secret: dockerconfig
    tags:
      - latest
    repo: us-central1-docker.pkg.dev/unstable-build-blue-dev/docker/go-tui-ci
    dockerfile: Dockerfile.build
    build_args_from_env: [ GIT_SSH_KEY ]

trigger:
  event:
  - cron
