kind: pipeline
type: docker
name: default

steps:
- name: test
  image: golang:alpine
  environment:
    GIT_SSH_KEY:
      from_secret: git_ssh_key
  commands:
  - apk add --update --no-cache make git openssh gcc g++ musl-dev
  - mkdir -p ~/.ssh
  - echo "$GIT_SSH_KEY" > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - chmod 700 ~/.ssh
  - ssh-keyscan -t rsa git.unstable.build >> ~/.ssh/known_hosts
  - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
  - git config --global url.ssh://git@github.com/.insteadOf https://github.com/
  - make
  - make test
- name: slack
  image: plugins/slack
  when:
    status:
    - failure
    - success
  settings:
    webhook:
      from_secret: slack_webhook_url
    channel: git
    icon_url: https://raw.githubusercontent.com/drone/brand/master/logos/png/dark/drone-logo-png-dark-256.png

trigger:
  ref:
    include:
    - refs/heads/main
    - refs/pull/**
    - refs/tags/**
