kind: pipeline
type: docker
name: default

steps:
- name: test
  image: us-central1-docker.pkg.dev/unstable-build-blue-dev/docker/go-tui-ci:v0.1.96b
  environment:
    GIT_SSH_KEY:
      from_secret: git_ssh_key
    GOCACHE: /go/cache
  commands:
  - apk add --update --no-cache make git openssh gcc g++ musl-dev linux-headers
  - mkdir -p ~/.ssh
  - echo "$GIT_SSH_KEY" > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - chmod 700 ~/.ssh
  - ssh-keyscan -t rsa git.unstable.build >> ~/.ssh/known_hosts
  - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
  - git config --global url.ssh://git@github.com/.insteadOf https://github.com/
  - make debug
  - make test NOCI="false" GOTESTFLAGS="-race -timeout 400s"

- name: slack
  image: plugins/slack
  when:
    status:
    - failure
    - success
  settings:
    webhook:
      from_secret: slack_webhook_url
    channel: git
    icon_url: https://raw.githubusercontent.com/drone/brand/master/logos/png/dark/drone-logo-png-dark-256.png

trigger:
  ref:
    include:
    - refs/heads/main
    - refs/pull/**
    - refs/tags/**

image_pull_secrets:
- dockerconfig
