run:
  timeout: 5m
  exclude-dirs:
    - bin
    - target
# we should slowly fix tests too
issues:
  include:
    - EXC0012 # exported symbols should have comment or be unexported
    - EXC0014 # comment on exported symbols should be of the form
  exclude:
    - SA1019 # deprecations
  exclude-rules:
    - path: (.+)_test.go
      linters:
        - funlen
        - errcheck
        - unused
        - govet
        - ineffassign
        - staticcheck
        - gosimple
        - revive
linters:
  enable:
    - revive

linters-settings:
  revive:
    rules:
      - name: unused-parameter
        Disabled: true
      - name: exported
        severity: error
