// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ernestrc/golang-internal-tools/lsp/protocol (interfaces: Server)

// Package main is a generated GoMock package.
package main

import (
	context "context"
	reflect "reflect"

	protocol "github.com/ernestrc/golang-internal-tools/lsp/protocol"
	gomock "github.com/golang/mock/gomock"
)

// MockServer is a mock of Server interface.
type MockServer struct {
	ctrl     *gomock.Controller
	recorder *MockServerMockRecorder
}

// MockServerMockRecorder is the mock recorder for MockServer.
type MockServerMockRecorder struct {
	mock *MockServer
}

// NewMockServer creates a new mock instance.
func NewMockServer(ctrl *gomock.Controller) *MockServer {
	mock := &MockServer{ctrl: ctrl}
	mock.recorder = &MockServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServer) EXPECT() *MockServerMockRecorder {
	return m.recorder
}

// CodeAction mocks base method.
func (m *MockServer) CodeAction(arg0 context.Context, arg1 *protocol.CodeActionParams) ([]protocol.CodeAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CodeAction", arg0, arg1)
	ret0, _ := ret[0].([]protocol.CodeAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CodeAction indicates an expected call of CodeAction.
func (mr *MockServerMockRecorder) CodeAction(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CodeAction", reflect.TypeOf((*MockServer)(nil).CodeAction), arg0, arg1)
}

// CodeLens mocks base method.
func (m *MockServer) CodeLens(arg0 context.Context, arg1 *protocol.CodeLensParams) ([]protocol.CodeLens, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CodeLens", arg0, arg1)
	ret0, _ := ret[0].([]protocol.CodeLens)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CodeLens indicates an expected call of CodeLens.
func (mr *MockServerMockRecorder) CodeLens(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CodeLens", reflect.TypeOf((*MockServer)(nil).CodeLens), arg0, arg1)
}

// ColorPresentation mocks base method.
func (m *MockServer) ColorPresentation(arg0 context.Context, arg1 *protocol.ColorPresentationParams) ([]protocol.ColorPresentation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ColorPresentation", arg0, arg1)
	ret0, _ := ret[0].([]protocol.ColorPresentation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ColorPresentation indicates an expected call of ColorPresentation.
func (mr *MockServerMockRecorder) ColorPresentation(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ColorPresentation", reflect.TypeOf((*MockServer)(nil).ColorPresentation), arg0, arg1)
}

// Completion mocks base method.
func (m *MockServer) Completion(arg0 context.Context, arg1 *protocol.CompletionParams) (*protocol.CompletionList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Completion", arg0, arg1)
	ret0, _ := ret[0].(*protocol.CompletionList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Completion indicates an expected call of Completion.
func (mr *MockServerMockRecorder) Completion(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Completion", reflect.TypeOf((*MockServer)(nil).Completion), arg0, arg1)
}

// Declaration mocks base method.
func (m *MockServer) Declaration(arg0 context.Context, arg1 *protocol.DeclarationParams) ([]protocol.Location, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Declaration", arg0, arg1)
	ret0, _ := ret[0].([]protocol.Location)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Declaration indicates an expected call of Declaration.
func (mr *MockServerMockRecorder) Declaration(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Declaration", reflect.TypeOf((*MockServer)(nil).Declaration), arg0, arg1)
}

// Definition mocks base method.
func (m *MockServer) Definition(arg0 context.Context, arg1 *protocol.DefinitionParams) ([]protocol.Location, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Definition", arg0, arg1)
	ret0, _ := ret[0].([]protocol.Location)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Definition indicates an expected call of Definition.
func (mr *MockServerMockRecorder) Definition(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Definition", reflect.TypeOf((*MockServer)(nil).Definition), arg0, arg1)
}

// DidChange mocks base method.
func (m *MockServer) DidChange(arg0 context.Context, arg1 *protocol.DidChangeTextDocumentParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DidChange", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DidChange indicates an expected call of DidChange.
func (mr *MockServerMockRecorder) DidChange(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DidChange", reflect.TypeOf((*MockServer)(nil).DidChange), arg0, arg1)
}

// DidChangeConfiguration mocks base method.
func (m *MockServer) DidChangeConfiguration(arg0 context.Context, arg1 *protocol.DidChangeConfigurationParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DidChangeConfiguration", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DidChangeConfiguration indicates an expected call of DidChangeConfiguration.
func (mr *MockServerMockRecorder) DidChangeConfiguration(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DidChangeConfiguration", reflect.TypeOf((*MockServer)(nil).DidChangeConfiguration), arg0, arg1)
}

// DidChangeWatchedFiles mocks base method.
func (m *MockServer) DidChangeWatchedFiles(arg0 context.Context, arg1 *protocol.DidChangeWatchedFilesParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DidChangeWatchedFiles", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DidChangeWatchedFiles indicates an expected call of DidChangeWatchedFiles.
func (mr *MockServerMockRecorder) DidChangeWatchedFiles(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DidChangeWatchedFiles", reflect.TypeOf((*MockServer)(nil).DidChangeWatchedFiles), arg0, arg1)
}

// DidChangeWorkspaceFolders mocks base method.
func (m *MockServer) DidChangeWorkspaceFolders(arg0 context.Context, arg1 *protocol.DidChangeWorkspaceFoldersParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DidChangeWorkspaceFolders", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DidChangeWorkspaceFolders indicates an expected call of DidChangeWorkspaceFolders.
func (mr *MockServerMockRecorder) DidChangeWorkspaceFolders(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DidChangeWorkspaceFolders", reflect.TypeOf((*MockServer)(nil).DidChangeWorkspaceFolders), arg0, arg1)
}

// DidClose mocks base method.
func (m *MockServer) DidClose(arg0 context.Context, arg1 *protocol.DidCloseTextDocumentParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DidClose", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DidClose indicates an expected call of DidClose.
func (mr *MockServerMockRecorder) DidClose(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DidClose", reflect.TypeOf((*MockServer)(nil).DidClose), arg0, arg1)
}

// DidOpen mocks base method.
func (m *MockServer) DidOpen(arg0 context.Context, arg1 *protocol.DidOpenTextDocumentParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DidOpen", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DidOpen indicates an expected call of DidOpen.
func (mr *MockServerMockRecorder) DidOpen(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DidOpen", reflect.TypeOf((*MockServer)(nil).DidOpen), arg0, arg1)
}

// DidSave mocks base method.
func (m *MockServer) DidSave(arg0 context.Context, arg1 *protocol.DidSaveTextDocumentParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DidSave", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DidSave indicates an expected call of DidSave.
func (mr *MockServerMockRecorder) DidSave(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DidSave", reflect.TypeOf((*MockServer)(nil).DidSave), arg0, arg1)
}

// DocumentColor mocks base method.
func (m *MockServer) DocumentColor(arg0 context.Context, arg1 *protocol.DocumentColorParams) ([]protocol.ColorInformation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DocumentColor", arg0, arg1)
	ret0, _ := ret[0].([]protocol.ColorInformation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DocumentColor indicates an expected call of DocumentColor.
func (mr *MockServerMockRecorder) DocumentColor(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DocumentColor", reflect.TypeOf((*MockServer)(nil).DocumentColor), arg0, arg1)
}

// DocumentHighlight mocks base method.
func (m *MockServer) DocumentHighlight(arg0 context.Context, arg1 *protocol.DocumentHighlightParams) ([]protocol.DocumentHighlight, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DocumentHighlight", arg0, arg1)
	ret0, _ := ret[0].([]protocol.DocumentHighlight)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DocumentHighlight indicates an expected call of DocumentHighlight.
func (mr *MockServerMockRecorder) DocumentHighlight(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DocumentHighlight", reflect.TypeOf((*MockServer)(nil).DocumentHighlight), arg0, arg1)
}

// DocumentLink mocks base method.
func (m *MockServer) DocumentLink(arg0 context.Context, arg1 *protocol.DocumentLinkParams) ([]protocol.DocumentLink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DocumentLink", arg0, arg1)
	ret0, _ := ret[0].([]protocol.DocumentLink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DocumentLink indicates an expected call of DocumentLink.
func (mr *MockServerMockRecorder) DocumentLink(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DocumentLink", reflect.TypeOf((*MockServer)(nil).DocumentLink), arg0, arg1)
}

// DocumentSymbol mocks base method.
func (m *MockServer) DocumentSymbol(arg0 context.Context, arg1 *protocol.DocumentSymbolParams) ([]interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DocumentSymbol", arg0, arg1)
	ret0, _ := ret[0].([]interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DocumentSymbol indicates an expected call of DocumentSymbol.
func (mr *MockServerMockRecorder) DocumentSymbol(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DocumentSymbol", reflect.TypeOf((*MockServer)(nil).DocumentSymbol), arg0, arg1)
}

// ExecuteCommand mocks base method.
func (m *MockServer) ExecuteCommand(arg0 context.Context, arg1 *protocol.ExecuteCommandParams) (interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteCommand", arg0, arg1)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteCommand indicates an expected call of ExecuteCommand.
func (mr *MockServerMockRecorder) ExecuteCommand(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteCommand", reflect.TypeOf((*MockServer)(nil).ExecuteCommand), arg0, arg1)
}

// Exit mocks base method.
func (m *MockServer) Exit(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exit", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Exit indicates an expected call of Exit.
func (mr *MockServerMockRecorder) Exit(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exit", reflect.TypeOf((*MockServer)(nil).Exit), arg0)
}

// FoldingRange mocks base method.
func (m *MockServer) FoldingRange(arg0 context.Context, arg1 *protocol.FoldingRangeParams) ([]protocol.FoldingRange, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FoldingRange", arg0, arg1)
	ret0, _ := ret[0].([]protocol.FoldingRange)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FoldingRange indicates an expected call of FoldingRange.
func (mr *MockServerMockRecorder) FoldingRange(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FoldingRange", reflect.TypeOf((*MockServer)(nil).FoldingRange), arg0, arg1)
}

// Formatting mocks base method.
func (m *MockServer) Formatting(arg0 context.Context, arg1 *protocol.DocumentFormattingParams) ([]protocol.TextEdit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Formatting", arg0, arg1)
	ret0, _ := ret[0].([]protocol.TextEdit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Formatting indicates an expected call of Formatting.
func (mr *MockServerMockRecorder) Formatting(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Formatting", reflect.TypeOf((*MockServer)(nil).Formatting), arg0, arg1)
}

// Hover mocks base method.
func (m *MockServer) Hover(arg0 context.Context, arg1 *protocol.HoverParams) (*protocol.Hover, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hover", arg0, arg1)
	ret0, _ := ret[0].(*protocol.Hover)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Hover indicates an expected call of Hover.
func (mr *MockServerMockRecorder) Hover(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hover", reflect.TypeOf((*MockServer)(nil).Hover), arg0, arg1)
}

// Implementation mocks base method.
func (m *MockServer) Implementation(arg0 context.Context, arg1 *protocol.ImplementationParams) ([]protocol.Location, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Implementation", arg0, arg1)
	ret0, _ := ret[0].([]protocol.Location)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Implementation indicates an expected call of Implementation.
func (mr *MockServerMockRecorder) Implementation(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Implementation", reflect.TypeOf((*MockServer)(nil).Implementation), arg0, arg1)
}

// IncomingCalls mocks base method.
func (m *MockServer) IncomingCalls(arg0 context.Context, arg1 *protocol.CallHierarchyIncomingCallsParams) ([]protocol.CallHierarchyIncomingCall, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncomingCalls", arg0, arg1)
	ret0, _ := ret[0].([]protocol.CallHierarchyIncomingCall)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncomingCalls indicates an expected call of IncomingCalls.
func (mr *MockServerMockRecorder) IncomingCalls(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncomingCalls", reflect.TypeOf((*MockServer)(nil).IncomingCalls), arg0, arg1)
}

// Initialize mocks base method.
func (m *MockServer) Initialize(arg0 context.Context, arg1 *protocol.ParamInitialize) (*protocol.InitializeResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Initialize", arg0, arg1)
	ret0, _ := ret[0].(*protocol.InitializeResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Initialize indicates an expected call of Initialize.
func (mr *MockServerMockRecorder) Initialize(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Initialize", reflect.TypeOf((*MockServer)(nil).Initialize), arg0, arg1)
}

// Initialized mocks base method.
func (m *MockServer) Initialized(arg0 context.Context, arg1 *protocol.InitializedParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Initialized", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Initialized indicates an expected call of Initialized.
func (mr *MockServerMockRecorder) Initialized(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Initialized", reflect.TypeOf((*MockServer)(nil).Initialized), arg0, arg1)
}

// LogTrace mocks base method.
func (m *MockServer) LogTrace(arg0 context.Context, arg1 *protocol.LogTraceParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogTrace", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogTrace indicates an expected call of LogTrace.
func (mr *MockServerMockRecorder) LogTrace(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogTrace", reflect.TypeOf((*MockServer)(nil).LogTrace), arg0, arg1)
}

// Moniker mocks base method.
func (m *MockServer) Moniker(arg0 context.Context, arg1 *protocol.MonikerParams) ([]protocol.Moniker, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Moniker", arg0, arg1)
	ret0, _ := ret[0].([]protocol.Moniker)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Moniker indicates an expected call of Moniker.
func (mr *MockServerMockRecorder) Moniker(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Moniker", reflect.TypeOf((*MockServer)(nil).Moniker), arg0, arg1)
}

// NonstandardRequest mocks base method.
func (m *MockServer) NonstandardRequest(arg0 context.Context, arg1 string, arg2 interface{}) (interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NonstandardRequest", arg0, arg1, arg2)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NonstandardRequest indicates an expected call of NonstandardRequest.
func (mr *MockServerMockRecorder) NonstandardRequest(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NonstandardRequest", reflect.TypeOf((*MockServer)(nil).NonstandardRequest), arg0, arg1, arg2)
}

// OnTypeFormatting mocks base method.
func (m *MockServer) OnTypeFormatting(arg0 context.Context, arg1 *protocol.DocumentOnTypeFormattingParams) ([]protocol.TextEdit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnTypeFormatting", arg0, arg1)
	ret0, _ := ret[0].([]protocol.TextEdit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OnTypeFormatting indicates an expected call of OnTypeFormatting.
func (mr *MockServerMockRecorder) OnTypeFormatting(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnTypeFormatting", reflect.TypeOf((*MockServer)(nil).OnTypeFormatting), arg0, arg1)
}

// OutgoingCalls mocks base method.
func (m *MockServer) OutgoingCalls(arg0 context.Context, arg1 *protocol.CallHierarchyOutgoingCallsParams) ([]protocol.CallHierarchyOutgoingCall, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OutgoingCalls", arg0, arg1)
	ret0, _ := ret[0].([]protocol.CallHierarchyOutgoingCall)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OutgoingCalls indicates an expected call of OutgoingCalls.
func (mr *MockServerMockRecorder) OutgoingCalls(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OutgoingCalls", reflect.TypeOf((*MockServer)(nil).OutgoingCalls), arg0, arg1)
}

// PrepareCallHierarchy mocks base method.
func (m *MockServer) PrepareCallHierarchy(arg0 context.Context, arg1 *protocol.CallHierarchyPrepareParams) ([]protocol.CallHierarchyItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrepareCallHierarchy", arg0, arg1)
	ret0, _ := ret[0].([]protocol.CallHierarchyItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PrepareCallHierarchy indicates an expected call of PrepareCallHierarchy.
func (mr *MockServerMockRecorder) PrepareCallHierarchy(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrepareCallHierarchy", reflect.TypeOf((*MockServer)(nil).PrepareCallHierarchy), arg0, arg1)
}

// PrepareRename mocks base method.
func (m *MockServer) PrepareRename(arg0 context.Context, arg1 *protocol.PrepareRenameParams) (*protocol.Range, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrepareRename", arg0, arg1)
	ret0, _ := ret[0].(*protocol.Range)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PrepareRename indicates an expected call of PrepareRename.
func (mr *MockServerMockRecorder) PrepareRename(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrepareRename", reflect.TypeOf((*MockServer)(nil).PrepareRename), arg0, arg1)
}

// RangeFormatting mocks base method.
func (m *MockServer) RangeFormatting(arg0 context.Context, arg1 *protocol.DocumentRangeFormattingParams) ([]protocol.TextEdit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RangeFormatting", arg0, arg1)
	ret0, _ := ret[0].([]protocol.TextEdit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RangeFormatting indicates an expected call of RangeFormatting.
func (mr *MockServerMockRecorder) RangeFormatting(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RangeFormatting", reflect.TypeOf((*MockServer)(nil).RangeFormatting), arg0, arg1)
}

// References mocks base method.
func (m *MockServer) References(arg0 context.Context, arg1 *protocol.ReferenceParams) ([]protocol.Location, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "References", arg0, arg1)
	ret0, _ := ret[0].([]protocol.Location)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// References indicates an expected call of References.
func (mr *MockServerMockRecorder) References(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "References", reflect.TypeOf((*MockServer)(nil).References), arg0, arg1)
}

// Rename mocks base method.
func (m *MockServer) Rename(arg0 context.Context, arg1 *protocol.RenameParams) (*protocol.WorkspaceEdit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rename", arg0, arg1)
	ret0, _ := ret[0].(*protocol.WorkspaceEdit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Rename indicates an expected call of Rename.
func (mr *MockServerMockRecorder) Rename(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rename", reflect.TypeOf((*MockServer)(nil).Rename), arg0, arg1)
}

// Resolve mocks base method.
func (m *MockServer) Resolve(arg0 context.Context, arg1 *protocol.CompletionItem) (*protocol.CompletionItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", arg0, arg1)
	ret0, _ := ret[0].(*protocol.CompletionItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resolve indicates an expected call of Resolve.
func (mr *MockServerMockRecorder) Resolve(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockServer)(nil).Resolve), arg0, arg1)
}

// ResolveCodeAction mocks base method.
func (m *MockServer) ResolveCodeAction(arg0 context.Context, arg1 *protocol.CodeAction) (*protocol.CodeAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveCodeAction", arg0, arg1)
	ret0, _ := ret[0].(*protocol.CodeAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveCodeAction indicates an expected call of ResolveCodeAction.
func (mr *MockServerMockRecorder) ResolveCodeAction(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveCodeAction", reflect.TypeOf((*MockServer)(nil).ResolveCodeAction), arg0, arg1)
}

// ResolveCodeLens mocks base method.
func (m *MockServer) ResolveCodeLens(arg0 context.Context, arg1 *protocol.CodeLens) (*protocol.CodeLens, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveCodeLens", arg0, arg1)
	ret0, _ := ret[0].(*protocol.CodeLens)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveCodeLens indicates an expected call of ResolveCodeLens.
func (mr *MockServerMockRecorder) ResolveCodeLens(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveCodeLens", reflect.TypeOf((*MockServer)(nil).ResolveCodeLens), arg0, arg1)
}

// ResolveDocumentLink mocks base method.
func (m *MockServer) ResolveDocumentLink(arg0 context.Context, arg1 *protocol.DocumentLink) (*protocol.DocumentLink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveDocumentLink", arg0, arg1)
	ret0, _ := ret[0].(*protocol.DocumentLink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveDocumentLink indicates an expected call of ResolveDocumentLink.
func (mr *MockServerMockRecorder) ResolveDocumentLink(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveDocumentLink", reflect.TypeOf((*MockServer)(nil).ResolveDocumentLink), arg0, arg1)
}

// SelectionRange mocks base method.
func (m *MockServer) SelectionRange(arg0 context.Context, arg1 *protocol.SelectionRangeParams) ([]protocol.SelectionRange, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectionRange", arg0, arg1)
	ret0, _ := ret[0].([]protocol.SelectionRange)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectionRange indicates an expected call of SelectionRange.
func (mr *MockServerMockRecorder) SelectionRange(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectionRange", reflect.TypeOf((*MockServer)(nil).SelectionRange), arg0, arg1)
}

// SemanticTokensFull mocks base method.
func (m *MockServer) SemanticTokensFull(arg0 context.Context, arg1 *protocol.SemanticTokensParams) (*protocol.SemanticTokens, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SemanticTokensFull", arg0, arg1)
	ret0, _ := ret[0].(*protocol.SemanticTokens)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SemanticTokensFull indicates an expected call of SemanticTokensFull.
func (mr *MockServerMockRecorder) SemanticTokensFull(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SemanticTokensFull", reflect.TypeOf((*MockServer)(nil).SemanticTokensFull), arg0, arg1)
}

// SemanticTokensFullDelta mocks base method.
func (m *MockServer) SemanticTokensFullDelta(arg0 context.Context, arg1 *protocol.SemanticTokensDeltaParams) (interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SemanticTokensFullDelta", arg0, arg1)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SemanticTokensFullDelta indicates an expected call of SemanticTokensFullDelta.
func (mr *MockServerMockRecorder) SemanticTokensFullDelta(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SemanticTokensFullDelta", reflect.TypeOf((*MockServer)(nil).SemanticTokensFullDelta), arg0, arg1)
}

// SemanticTokensRange mocks base method.
func (m *MockServer) SemanticTokensRange(arg0 context.Context, arg1 *protocol.SemanticTokensRangeParams) (*protocol.SemanticTokens, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SemanticTokensRange", arg0, arg1)
	ret0, _ := ret[0].(*protocol.SemanticTokens)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SemanticTokensRange indicates an expected call of SemanticTokensRange.
func (mr *MockServerMockRecorder) SemanticTokensRange(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SemanticTokensRange", reflect.TypeOf((*MockServer)(nil).SemanticTokensRange), arg0, arg1)
}

// SemanticTokensRefresh mocks base method.
func (m *MockServer) SemanticTokensRefresh(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SemanticTokensRefresh", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SemanticTokensRefresh indicates an expected call of SemanticTokensRefresh.
func (mr *MockServerMockRecorder) SemanticTokensRefresh(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SemanticTokensRefresh", reflect.TypeOf((*MockServer)(nil).SemanticTokensRefresh), arg0)
}

// SetTrace mocks base method.
func (m *MockServer) SetTrace(arg0 context.Context, arg1 *protocol.SetTraceParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetTrace", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetTrace indicates an expected call of SetTrace.
func (mr *MockServerMockRecorder) SetTrace(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTrace", reflect.TypeOf((*MockServer)(nil).SetTrace), arg0, arg1)
}

// Shutdown mocks base method.
func (m *MockServer) Shutdown(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Shutdown", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockServerMockRecorder) Shutdown(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockServer)(nil).Shutdown), arg0)
}

// SignatureHelp mocks base method.
func (m *MockServer) SignatureHelp(arg0 context.Context, arg1 *protocol.SignatureHelpParams) (*protocol.SignatureHelp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignatureHelp", arg0, arg1)
	ret0, _ := ret[0].(*protocol.SignatureHelp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SignatureHelp indicates an expected call of SignatureHelp.
func (mr *MockServerMockRecorder) SignatureHelp(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignatureHelp", reflect.TypeOf((*MockServer)(nil).SignatureHelp), arg0, arg1)
}

// Symbol mocks base method.
func (m *MockServer) Symbol(arg0 context.Context, arg1 *protocol.WorkspaceSymbolParams) ([]protocol.SymbolInformation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Symbol", arg0, arg1)
	ret0, _ := ret[0].([]protocol.SymbolInformation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Symbol indicates an expected call of Symbol.
func (mr *MockServerMockRecorder) Symbol(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Symbol", reflect.TypeOf((*MockServer)(nil).Symbol), arg0, arg1)
}

// TypeDefinition mocks base method.
func (m *MockServer) TypeDefinition(arg0 context.Context, arg1 *protocol.TypeDefinitionParams) ([]protocol.Location, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TypeDefinition", arg0, arg1)
	ret0, _ := ret[0].([]protocol.Location)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TypeDefinition indicates an expected call of TypeDefinition.
func (mr *MockServerMockRecorder) TypeDefinition(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TypeDefinition", reflect.TypeOf((*MockServer)(nil).TypeDefinition), arg0, arg1)
}

// WillSave mocks base method.
func (m *MockServer) WillSave(arg0 context.Context, arg1 *protocol.WillSaveTextDocumentParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WillSave", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// WillSave indicates an expected call of WillSave.
func (mr *MockServerMockRecorder) WillSave(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WillSave", reflect.TypeOf((*MockServer)(nil).WillSave), arg0, arg1)
}

// WillSaveWaitUntil mocks base method.
func (m *MockServer) WillSaveWaitUntil(arg0 context.Context, arg1 *protocol.WillSaveTextDocumentParams) ([]protocol.TextEdit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WillSaveWaitUntil", arg0, arg1)
	ret0, _ := ret[0].([]protocol.TextEdit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WillSaveWaitUntil indicates an expected call of WillSaveWaitUntil.
func (mr *MockServerMockRecorder) WillSaveWaitUntil(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WillSaveWaitUntil", reflect.TypeOf((*MockServer)(nil).WillSaveWaitUntil), arg0, arg1)
}

// WorkDoneProgressCancel mocks base method.
func (m *MockServer) WorkDoneProgressCancel(arg0 context.Context, arg1 *protocol.WorkDoneProgressCancelParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WorkDoneProgressCancel", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// WorkDoneProgressCancel indicates an expected call of WorkDoneProgressCancel.
func (mr *MockServerMockRecorder) WorkDoneProgressCancel(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WorkDoneProgressCancel", reflect.TypeOf((*MockServer)(nil).WorkDoneProgressCancel), arg0, arg1)
}
