package term

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestParse(t *testing.T) {
	suite := []KeyComb{
		{Key: KeyF1},
		{Key: KeyF2},
		{Key: KeyF3},
		{Key: KeyF4},
		{Key: KeyF5},
		{Key: KeyF6},
		{Key: KeyF7},
		{Key: KeyF8},
		{Key: KeyF9},
		{Key: KeyF10},
		{Key: KeyF11},
		{Key: KeyF12},
		{Key: KeyInsert},
		{Key: KeyDelete},
		{Key: KeyHome},
		{Key: KeyEnd},
		{Key: KeyPgup},
		{Key: KeyPgdn},
		{Key: KeyArrowUp},
		{Key: KeyArrowDown},
		{Key: KeyArrowLeft},
		{Key: KeyArrowRight},
		{Key: MouseLeft},
		{Key: MouseMiddle},
		{Key: MouseRight},
		{Key: MouseRelease},
		{Key: MouseWheelUp},
		{Key: MouseWheelDown},
		{Key: KeyCtrlTilde},
		{Key: KeyCtrl2},
		{Key: KeyCtrlSpace},
		{Key: KeyCtrlA},
		{Key: KeyCtrlB},
		{Key: KeyCtrlC},
		{Key: KeyCtrlD},
		{Key: KeyCtrlE},
		{Key: KeyCtrlF},
		{Key: KeyCtrlG},
		{Key: KeyBackspace},
		{Key: KeyCtrlH},
		{Key: KeyTab},
		{Key: KeyCtrlI},
		{Key: KeyCtrlJ},
		{Key: KeyCtrlK},
		{Key: KeyCtrlL},
		{Key: KeyEnter},
		{Key: KeyCtrlM},
		{Key: KeyCtrlN},
		{Key: KeyCtrlO},
		{Key: KeyCtrlP},
		{Key: KeyCtrlQ},
		{Key: KeyCtrlR},
		{Key: KeyCtrlS},
		{Key: KeyCtrlT},
		{Key: KeyCtrlU},
		{Key: KeyCtrlV},
		{Key: KeyCtrlW},
		{Key: KeyCtrlX},
		{Key: KeyCtrlY},
		{Key: KeyCtrlZ},
		{Key: KeyEsc},
		{Key: KeyCtrlLsqBracket},
		{Key: KeyCtrl3},
		{Key: KeyCtrl4},
		{Key: KeyCtrlBackslash},
		{Key: KeyCtrl5},
		{Key: KeyCtrlRsqBracket},
		{Key: KeyCtrl6},
		{Key: KeyCtrl7},
		{Key: KeyCtrlSlash},
		{Key: KeyCtrlUnderscore},
		{Key: KeySpace},
		{Key: KeyBackspace2},
		{Key: KeyCtrl8},
		{Key: KeyF1, Mod: ModAlt},
		{Key: KeyF2, Mod: ModAlt},
		{Key: KeyF3, Mod: ModAlt},
		{Key: KeyF4, Mod: ModAlt},
		{Key: KeyF5, Mod: ModAlt},
		{Key: KeyF6, Mod: ModAlt},
		{Key: KeyF7, Mod: ModAlt},
		{Key: KeyF8, Mod: ModAlt},
		{Key: KeyF9, Mod: ModAlt},
		{Key: KeyF10, Mod: ModAlt},
		{Key: KeyF11, Mod: ModAlt},
		{Key: KeyF12, Mod: ModAlt},
		{Key: KeyInsert, Mod: ModAlt},
		{Key: KeyDelete, Mod: ModAlt},
		{Key: KeyHome, Mod: ModAlt},
		{Key: KeyEnd, Mod: ModAlt},
		{Key: KeyPgup, Mod: ModAlt},
		{Key: KeyPgdn, Mod: ModAlt},
		{Key: KeyArrowUp, Mod: ModAlt},
		{Key: KeyArrowDown, Mod: ModAlt},
		{Key: KeyArrowLeft, Mod: ModAlt},
		{Key: KeyArrowRight, Mod: ModAlt},
		{Key: MouseLeft, Mod: ModAlt},
		{Key: MouseMiddle, Mod: ModAlt},
		{Key: MouseRight, Mod: ModAlt},
		{Key: MouseRelease, Mod: ModAlt},
		{Key: MouseWheelUp, Mod: ModAlt},
		{Key: MouseWheelDown, Mod: ModAlt},
		{Key: KeyCtrlTilde, Mod: ModAlt},
		{Key: KeyCtrl2, Mod: ModAlt},
		{Key: KeyCtrlSpace, Mod: ModAlt},
		{Key: KeyCtrlA, Mod: ModAlt},
		{Key: KeyCtrlB, Mod: ModAlt},
		{Key: KeyCtrlC, Mod: ModAlt},
		{Key: KeyCtrlD, Mod: ModAlt},
		{Key: KeyCtrlE, Mod: ModAlt},
		{Key: KeyCtrlF, Mod: ModAlt},
		{Key: KeyCtrlG, Mod: ModAlt},
		{Key: KeyBackspace, Mod: ModAlt},
		{Key: KeyCtrlH, Mod: ModAlt},
		{Key: KeyTab, Mod: ModAlt},
		{Key: KeyCtrlI, Mod: ModAlt},
		{Key: KeyCtrlJ, Mod: ModAlt},
		{Key: KeyCtrlK, Mod: ModAlt},
		{Key: KeyCtrlL, Mod: ModAlt},
		{Key: KeyEnter, Mod: ModAlt},
		{Key: KeyCtrlM, Mod: ModAlt},
		{Key: KeyCtrlN, Mod: ModAlt},
		{Key: KeyCtrlO, Mod: ModAlt},
		{Key: KeyCtrlP, Mod: ModAlt},
		{Key: KeyCtrlQ, Mod: ModAlt},
		{Key: KeyCtrlR, Mod: ModAlt},
		{Key: KeyCtrlS, Mod: ModAlt},
		{Key: KeyCtrlT, Mod: ModAlt},
		{Key: KeyCtrlU, Mod: ModAlt},
		{Key: KeyCtrlV, Mod: ModAlt},
		{Key: KeyCtrlW, Mod: ModAlt},
		{Key: KeyCtrlX, Mod: ModAlt},
		{Key: KeyCtrlY, Mod: ModAlt},
		{Key: KeyCtrlZ, Mod: ModAlt},
		{Key: KeyEsc, Mod: ModAlt},
		{Key: KeyCtrlLsqBracket, Mod: ModAlt},
		{Key: KeyCtrl3, Mod: ModAlt},
		{Key: KeyCtrl4, Mod: ModAlt},
		{Key: KeyCtrlBackslash, Mod: ModAlt},
		{Key: KeyCtrl5, Mod: ModAlt},
		{Key: KeyCtrlRsqBracket, Mod: ModAlt},
		{Key: KeyCtrl6, Mod: ModAlt},
		{Key: KeyCtrl7, Mod: ModAlt},
		{Key: KeyCtrlSlash, Mod: ModAlt},
		{Key: KeyCtrlUnderscore, Mod: ModAlt},
		{Key: KeySpace, Mod: ModAlt},
		{Key: KeyBackspace2, Mod: ModAlt},
		{Key: KeyCtrl8, Mod: ModAlt},
	}

	for _, comb := range suite {
		t.Run(comb.String(), func(t *testing.T) {
			c, err := ParseKey(comb.String())
			assert.NoError(t, err)
			assert.Equal(t, comb, c)

			c, err = ParseKey(c.String())
			assert.NoError(t, err)
			assert.Equal(t, comb, c)
		})
	}
}
