// Code generated by MockGen. DO NOT EDIT.
// Source: ./component.go
//
// Generated by this command:
//
//	mockgen -destination=./texttest/workspace_gomock.go -package texttest -self_package unstable.build/go-tui/text/texttest -source ./component.go
//

// Package texttest is a generated GoMock package.
package texttest

import (
	os "os"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	workspaceapi "unstable.build/go-tui/api/workspaceapi"
	cell "unstable.build/go-tui/cell"
	notifications "unstable.build/go-tui/component/notifications"
	workspace "unstable.build/go-tui/workspace"
)

// MockWorkspace is a mock of Workspace interface.
type MockWorkspace struct {
	ctrl     *gomock.Controller
	recorder *MockWorkspaceMockRecorder
}

// MockWorkspaceMockRecorder is the mock recorder for MockWorkspace.
type MockWorkspaceMockRecorder struct {
	mock *MockWorkspace
}

// NewMockWorkspace creates a new mock instance.
func NewMockWorkspace(ctrl *gomock.Controller) *MockWorkspace {
	mock := &MockWorkspace{ctrl: ctrl}
	mock.recorder = &MockWorkspaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkspace) EXPECT() *MockWorkspaceMockRecorder {
	return m.recorder
}

// Load mocks base method.
func (m *MockWorkspace) Load(file workspaceapi.URI, buf *cell.Buffer, swapDir workspaceapi.URI, readOnly bool) (workspace.FlusherCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", file, buf, swapDir, readOnly)
	ret0, _ := ret[0].(workspace.FlusherCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockWorkspaceMockRecorder) Load(file, buf, swapDir, readOnly any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockWorkspace)(nil).Load), file, buf, swapDir, readOnly)
}

// Open mocks base method.
func (m *MockWorkspace) Open(path string, flag int, perm os.FileMode) (workspaceapi.File, *workspaceapi.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", path, flag, perm)
	ret0, _ := ret[0].(workspaceapi.File)
	ret1, _ := ret[1].(*workspaceapi.Error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockWorkspaceMockRecorder) Open(path, flag, perm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockWorkspace)(nil).Open), path, flag, perm)
}

// ReadDir mocks base method.
func (m *MockWorkspace) ReadDir(name string) ([]os.DirEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadDir", name)
	ret0, _ := ret[0].([]os.DirEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadDir indicates an expected call of ReadDir.
func (mr *MockWorkspaceMockRecorder) ReadDir(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadDir", reflect.TypeOf((*MockWorkspace)(nil).ReadDir), name)
}

// Recover mocks base method.
func (m *MockWorkspace) Recover(file, swapFilePath workspaceapi.URI, buf *cell.Buffer, force bool) (workspace.FlusherCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recover", file, swapFilePath, buf, force)
	ret0, _ := ret[0].(workspace.FlusherCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recover indicates an expected call of Recover.
func (mr *MockWorkspaceMockRecorder) Recover(file, swapFilePath, buf, force any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recover", reflect.TypeOf((*MockWorkspace)(nil).Recover), file, swapFilePath, buf, force)
}

// Remove mocks base method.
func (m *MockWorkspace) Remove(file string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", file)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockWorkspaceMockRecorder) Remove(file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockWorkspace)(nil).Remove), file)
}

// Stat mocks base method.
func (m *MockWorkspace) Stat(path string) (os.FileInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stat", path)
	ret0, _ := ret[0].(os.FileInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stat indicates an expected call of Stat.
func (mr *MockWorkspaceMockRecorder) Stat(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stat", reflect.TypeOf((*MockWorkspace)(nil).Stat), path)
}

// URI mocks base method.
func (m *MockWorkspace) URI(arg0 string) (workspaceapi.URI, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "URI", arg0)
	ret0, _ := ret[0].(workspaceapi.URI)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// URI indicates an expected call of URI.
func (mr *MockWorkspaceMockRecorder) URI(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "URI", reflect.TypeOf((*MockWorkspace)(nil).URI), arg0)
}

// Mocknotifier is a mock of notifier interface.
type Mocknotifier struct {
	ctrl     *gomock.Controller
	recorder *MocknotifierMockRecorder
}

// MocknotifierMockRecorder is the mock recorder for Mocknotifier.
type MocknotifierMockRecorder struct {
	mock *Mocknotifier
}

// NewMocknotifier creates a new mock instance.
func NewMocknotifier(ctrl *gomock.Controller) *Mocknotifier {
	mock := &Mocknotifier{ctrl: ctrl}
	mock.recorder = &MocknotifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mocknotifier) EXPECT() *MocknotifierMockRecorder {
	return m.recorder
}

// Notify mocks base method.
func (m *Mocknotifier) Notify(level notifications.Level, msg string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{level, msg}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Notify", varargs...)
}

// Notify indicates an expected call of Notify.
func (mr *MocknotifierMockRecorder) Notify(level, msg any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{level, msg}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Notify", reflect.TypeOf((*Mocknotifier)(nil).Notify), varargs...)
}
