package openai

import (
	"context"
	"errors"
	"io"
	"time"

	"github.com/ernestrc/blue/iterator"
	"github.com/ernestrc/blue/logging"
	"github.com/ernestrc/blue/retry"
	"github.com/sashabaranov/go-openai"
	log "github.com/sirupsen/logrus"
	"unstable.build/go-tui/cmd/extension_ai/backend"
)

// Config represents the default parameters used for chat completions
// along with the configuration passed to the openai client.
type Config struct {
	// ID of the model to use. If this is not set NewClient panics.
	Model string
	// Number between -2.0 and 2.0. Positive values penalize new tokens based
	// on their existing frequency in the text so far, decreasing the model's likelihood
	// to repeat the same line verbatim.
	FrequencyPenalty float32
	// Modify the likelihood of specified tokens appearing in the completion.
	//Accepts a JSON object that maps tokens (specified by their token ID in the tokenizer)
	// to an associated bias value from -100 to 100. Mathematically, the bias is added to
	// the logits generated by the model prior to sampling. The exact effect will vary per model,
	// but values between -1 and 1 should decrease or increase likelihood of selection;
	// values like -100 or 100 should result in a ban or exclusive selection of the relevant token.
	LogitBias map[string]int
	// The maximum number of tokens to generate in the chat completion.
	// The total length of input tokens and generated tokens is limited by the model's
	// context length.
	MaxTokens int

	// Number between -2.0 and 2.0. Positive values penalize new tokens based on whether they
	// appear in the text so far, increasing the model's likelihood to talk about new topics.
	PresencePenalty float32
	// If specified, our system will make a best effort to sample deterministically, such that repeated
	// requests with the same seed and parameters should return the same result.
	// Determinism is not guaranteed, and you should refer to the system_fingerprint response
	// parameter to monitor changes in the backend.
	// In beta, currently.
	// Seed int

	// What sampling temperature to use, between 0 and 2. Higher values like 0.8 will
	// make the output more random, while lower values like 0.2 will make it more
	// focused and deterministic.
	// Openai generally recommends altering this or top_p but not both.
	Temperature float32
	// An alternative to sampling with temperature, called nucleus sampling,
	// where the model considers the results of the tokens with top_p probability mass.
	// So 0.1 means only the tokens comprising the top 10% probability mass are considered.
	// Openai generally recommends altering this or temperature but not both.
	TopP float32

	// A list of tools the model may call. Currently, only functions are supported
	// as a tool. Use this to provide a list of functions the model may generate JSON inputs for.
	Tools []Tool
}

// NewClient returns a backedn.Service backed by openai's text completion API.
//
// The iterator returned by CreateChatCompletion sets ChatCompletionResponse's
// Metadata to a type openai.Metadata struct.
func NewClient(token string, config Config) backend.Service {
	if config.Model == "" {
		panic("Config.Model cannot be empty")
	}
	var tools []openai.Tool
	for _, tool := range config.Tools {
		tools = append(tools, openai.Tool{
			Type: openai.ToolType(tool.Type),
			Function: openai.FunctionDefinition{
				Name:        tool.Function.Name,
				Description: tool.Function.Description,
				Parameters:  tool.Function.Parameters,
			},
		})
	}
	return openaiClientAdapter{
		tools:  tools,
		config: config,
		client: openai.NewClient(token),
	}
}

var (
	retryStrategy = retry.CombinedStrategy(
		retry.LimitStrategy(5),
		retry.ExponentialStrategy(100*time.Millisecond, 2000*time.Millisecond),
	)
)

type openaiClientAdapter struct {
	tools  []openai.Tool
	config Config
	client *openai.Client
}

func (a openaiClientAdapter) CreateChatCompletion(
	ctx context.Context, request backend.ChatCompletionRequest,
) (iterator.Iterator[backend.ChatCompletionResponse], error) {
	// TODO use https://github.com/pkoukk/tiktoken-go to count tokens
	// and ensure that token limit is not reached for the given model.
	messages := make([]openai.ChatCompletionMessage, len(request.Messages))
	for i, msg := range request.Messages {
		messages[i] = openAIMessageFromModel(msg)
	}
	req := openai.ChatCompletionRequest{
		Messages:         messages,
		Model:            a.config.Model,
		FrequencyPenalty: a.config.FrequencyPenalty,
		LogitBias:        a.config.LogitBias,
		MaxTokens:        a.config.MaxTokens,
		PresencePenalty:  a.config.PresencePenalty,
		Temperature:      a.config.Temperature,
		TopP:             a.config.TopP,
		Tools:            a.tools,
		// NOTE: openai's choices/N API is not very useful at the moment
		// so we simply do not allow user to employ it
		// which greatly simplifies the backend.Service interface.
		// N:                1,
	}

	// see https://platform.openai.com/docs/guides/error-codes/api-errors
	var stream *openai.ChatCompletionStream
	var n int
	err := retry.Retry(ctx, retryStrategy, func(ctx context.Context) (bool, error) {
		n++
		var err error
		stream, err = a.client.CreateChatCompletionStream(ctx, req)
		if err == nil {
			return false, nil // done
		}
		apiErr := &openai.APIError{}
		if !errors.As(err, &apiErr) {
			return false, err // do not retry unknown error
		}
		log.WithFields(log.Fields{
			"call":           "CreateChatCompletion",
			"attempt":        n,
			"code":           apiErr.HTTPStatusCode,
			logging.KeyError: err.Error(),
			logging.KeyClass: "openai.Client",
		}).Warn(apiErr.Message)
		switch apiErr.HTTPStatusCode {
		case 429, 500:
			return true, err // retry allowed codes
		default:
			return false, err // do not retry the rest
		}
	})
	if err != nil {
		return nil, err
	}
	return &completionStreamIterator{stream: stream}, nil
}

// wraps an openai.ChatCompletionStream to satisfy iterator.Iterator
type completionStreamIterator struct {
	role   string
	stream *openai.ChatCompletionStream
	err    error
}

func (s *completionStreamIterator) Next() (ret backend.ChatCompletionResponse, ok bool) {
	resp, err := s.stream.Recv()
	if err != nil {
		s.stream.Close()
		if !errors.Is(err, io.EOF) {
			s.err = err
		}
		return
	}
	// NOTE: see above N parameter config
	choice := resp.Choices[0]
	if s.role == "" {
		s.role = choice.Delta.Role
	}
	ok = true
	ret = backend.ChatCompletionResponse{
		ID:      resp.ID,
		Created: time.Unix(resp.Created, 0),
		Message: backend.ChatCompletionMessage{
			Role:    s.role,
			Content: choice.Delta.Content,
			Metadata: Metadata{
				ToolCalls: modelToolCallsFromOpenAI(choice.Delta.ToolCalls),
			},
			// Name: assistant's name is never defined;
			// at least the unofficial openai client doesn't defined
		},
		FinishReason: backend.FinishReason(choice.FinishReason),
	}
	return
}

// Err returns the first error or an aggreation of the errors
// encountered by the Iterator.
func (s *completionStreamIterator) Err() error {
	return s.err
}
