// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.21.4
// source: rpc/clipboard.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetRegisterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RegisterId string `protobuf:"bytes,1,opt,name=register_id,json=registerId,proto3" json:"register_id,omitempty"`
	HandlerId  uint64 `protobuf:"varint,2,opt,name=handler_id,json=handlerId,proto3" json:"handler_id,omitempty"`
}

func (x *SetRegisterRequest) Reset() {
	*x = SetRegisterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_clipboard_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRegisterRequest) ProtoMessage() {}

func (x *SetRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_clipboard_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRegisterRequest.ProtoReflect.Descriptor instead.
func (*SetRegisterRequest) Descriptor() ([]byte, []int) {
	return file_rpc_clipboard_proto_rawDescGZIP(), []int{0}
}

func (x *SetRegisterRequest) GetRegisterId() string {
	if x != nil {
		return x.RegisterId
	}
	return ""
}

func (x *SetRegisterRequest) GetHandlerId() uint64 {
	if x != nil {
		return x.HandlerId
	}
	return 0
}

type SetRegisterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetRegisterResponse) Reset() {
	*x = SetRegisterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_clipboard_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetRegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRegisterResponse) ProtoMessage() {}

func (x *SetRegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_clipboard_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRegisterResponse.ProtoReflect.Descriptor instead.
func (*SetRegisterResponse) Descriptor() ([]byte, []int) {
	return file_rpc_clipboard_proto_rawDescGZIP(), []int{1}
}

type ClipboardCopyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ClipboardCopyRequest) Reset() {
	*x = ClipboardCopyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_clipboard_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClipboardCopyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClipboardCopyRequest) ProtoMessage() {}

func (x *ClipboardCopyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_clipboard_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClipboardCopyRequest.ProtoReflect.Descriptor instead.
func (*ClipboardCopyRequest) Descriptor() ([]byte, []int) {
	return file_rpc_clipboard_proto_rawDescGZIP(), []int{2}
}

func (x *ClipboardCopyRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type ClipboardCopyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ClipboardCopyResponse) Reset() {
	*x = ClipboardCopyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_clipboard_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClipboardCopyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClipboardCopyResponse) ProtoMessage() {}

func (x *ClipboardCopyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_clipboard_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClipboardCopyResponse.ProtoReflect.Descriptor instead.
func (*ClipboardCopyResponse) Descriptor() ([]byte, []int) {
	return file_rpc_clipboard_proto_rawDescGZIP(), []int{3}
}

type ClipboardPasteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ClipboardPasteRequest) Reset() {
	*x = ClipboardPasteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_clipboard_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClipboardPasteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClipboardPasteRequest) ProtoMessage() {}

func (x *ClipboardPasteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_clipboard_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClipboardPasteRequest.ProtoReflect.Descriptor instead.
func (*ClipboardPasteRequest) Descriptor() ([]byte, []int) {
	return file_rpc_clipboard_proto_rawDescGZIP(), []int{4}
}

type ClipboardPasteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ClipboardPasteResponse) Reset() {
	*x = ClipboardPasteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_clipboard_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClipboardPasteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClipboardPasteResponse) ProtoMessage() {}

func (x *ClipboardPasteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_clipboard_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClipboardPasteResponse.ProtoReflect.Descriptor instead.
func (*ClipboardPasteResponse) Descriptor() ([]byte, []int) {
	return file_rpc_clipboard_proto_rawDescGZIP(), []int{5}
}

func (x *ClipboardPasteResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_rpc_clipboard_proto protoreflect.FileDescriptor

var file_rpc_clipboard_proto_rawDesc = []byte{
	0x0a, 0x13, 0x72, 0x70, 0x63, 0x2f, 0x63, 0x6c, 0x69, 0x70, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x22, 0x54, 0x0a,
	0x12, 0x53, 0x65, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65,
	0x72, 0x49, 0x64, 0x22, 0x15, 0x0a, 0x13, 0x53, 0x65, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2a, 0x0a, 0x14, 0x43, 0x6c,
	0x69, 0x70, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x43, 0x6f, 0x70, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x17, 0x0a, 0x15, 0x43, 0x6c, 0x69, 0x70, 0x62, 0x6f,
	0x61, 0x72, 0x64, 0x43, 0x6f, 0x70, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x17, 0x0a, 0x15, 0x43, 0x6c, 0x69, 0x70, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x50, 0x61, 0x73, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x2c, 0x0a, 0x16, 0x43, 0x6c, 0x69, 0x70,
	0x62, 0x6f, 0x61, 0x72, 0x64, 0x50, 0x61, 0x73, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0x53, 0x0a, 0x09, 0x43, 0x6c, 0x69, 0x70, 0x62, 0x6f,
	0x61, 0x72, 0x64, 0x12, 0x46, 0x0a, 0x0b, 0x53, 0x65, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x12, 0x1a, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x53, 0x65, 0x74, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b,
	0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x53, 0x65, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xa0, 0x01, 0x0a, 0x11,
	0x43, 0x6c, 0x69, 0x70, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x12, 0x43, 0x0a, 0x04, 0x43, 0x6f, 0x70, 0x79, 0x12, 0x1c, 0x2e, 0x70, 0x6c, 0x75, 0x67,
	0x69, 0x6e, 0x2e, 0x43, 0x6c, 0x69, 0x70, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x43, 0x6f, 0x70, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x2e, 0x43, 0x6c, 0x69, 0x70, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x43, 0x6f, 0x70, 0x79, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a, 0x05, 0x50, 0x61, 0x73, 0x74, 0x65, 0x12,
	0x1d, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x43, 0x6c, 0x69, 0x70, 0x62, 0x6f, 0x61,
	0x72, 0x64, 0x50, 0x61, 0x73, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e,
	0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x43, 0x6c, 0x69, 0x70, 0x62, 0x6f, 0x61, 0x72,
	0x64, 0x50, 0x61, 0x73, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x22,
	0x5a, 0x20, 0x75, 0x6e, 0x73, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x62, 0x75, 0x69, 0x6c, 0x64,
	0x2f, 0x67, 0x6f, 0x2d, 0x74, 0x75, 0x69, 0x2f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2f, 0x72,
	0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_clipboard_proto_rawDescOnce sync.Once
	file_rpc_clipboard_proto_rawDescData = file_rpc_clipboard_proto_rawDesc
)

func file_rpc_clipboard_proto_rawDescGZIP() []byte {
	file_rpc_clipboard_proto_rawDescOnce.Do(func() {
		file_rpc_clipboard_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_clipboard_proto_rawDescData)
	})
	return file_rpc_clipboard_proto_rawDescData
}

var file_rpc_clipboard_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_rpc_clipboard_proto_goTypes = []interface{}{
	(*SetRegisterRequest)(nil),     // 0: plugin.SetRegisterRequest
	(*SetRegisterResponse)(nil),    // 1: plugin.SetRegisterResponse
	(*ClipboardCopyRequest)(nil),   // 2: plugin.ClipboardCopyRequest
	(*ClipboardCopyResponse)(nil),  // 3: plugin.ClipboardCopyResponse
	(*ClipboardPasteRequest)(nil),  // 4: plugin.ClipboardPasteRequest
	(*ClipboardPasteResponse)(nil), // 5: plugin.ClipboardPasteResponse
}
var file_rpc_clipboard_proto_depIdxs = []int32{
	0, // 0: plugin.Clipboard.SetRegister:input_type -> plugin.SetRegisterRequest
	2, // 1: plugin.ClipboardRegister.Copy:input_type -> plugin.ClipboardCopyRequest
	4, // 2: plugin.ClipboardRegister.Paste:input_type -> plugin.ClipboardPasteRequest
	1, // 3: plugin.Clipboard.SetRegister:output_type -> plugin.SetRegisterResponse
	3, // 4: plugin.ClipboardRegister.Copy:output_type -> plugin.ClipboardCopyResponse
	5, // 5: plugin.ClipboardRegister.Paste:output_type -> plugin.ClipboardPasteResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_clipboard_proto_init() }
func file_rpc_clipboard_proto_init() {
	if File_rpc_clipboard_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_clipboard_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetRegisterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_clipboard_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetRegisterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_clipboard_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClipboardCopyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_clipboard_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClipboardCopyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_clipboard_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClipboardPasteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_clipboard_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClipboardPasteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_clipboard_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_rpc_clipboard_proto_goTypes,
		DependencyIndexes: file_rpc_clipboard_proto_depIdxs,
		MessageInfos:      file_rpc_clipboard_proto_msgTypes,
	}.Build()
	File_rpc_clipboard_proto = out.File
	file_rpc_clipboard_proto_rawDesc = nil
	file_rpc_clipboard_proto_goTypes = nil
	file_rpc_clipboard_proto_depIdxs = nil
}
