// Copyright (C) 2017-2026 The Rune Authors
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or (at
// your option) any later version.
//
// This program is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
// General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

package template

import (
	"fmt"
	"strings"

	"github.com/unstablebuild/rune-go-sdk/component"
	"github.com/unstablebuild/rune-go-sdk/term"
	"github.com/unstablebuild/rune-go-sdk/term/graphemecluster"
)

// Build builds a component from a template string, value
// and attributes generated by Parse.
func Build(
	template string, value any, attrs, defAttrs term.Attributes,
	bgColor term.Color,
) []component.Floating {
	if attrs.Bg == 0 && attrs.Fg == 0 {
		attrs = defAttrs
	}
	attrs.Attrs |= defAttrs.Attrs
	cfg := component.StringConfig{
		Alignment: component.AlignmentCentered,
	}
	cfg.Attributes = attrs
	if cfg.Attributes.Bg == 0 {
		cfg.Attributes.Bg = bgColor
	}
	cfg.BackgroundAttributes.Bg = cfg.Attributes.Bg
	backgroundRunesCfg := cfg
	backgroundRunesCfg.Fg = cfg.Attributes.Bg
	backgroundRunesCfg.Bg = bgColor

	var components []component.Floating
	var buf strings.Builder
	var currentBackground bool
	// invert background/foreground if template chunk has background runes
	for i, r := range template {
		isBackground := graphemecluster.IsBackground(r)
		if i == 0 {
			currentBackground = isBackground
		}
		switch {
		case isBackground && currentBackground:
			buf.WriteRune(r)
		case !isBackground && !currentBackground:
			buf.WriteRune(r)
		case !isBackground && currentBackground:
			components = appendComponent(components, &buf, value, backgroundRunesCfg)
			currentBackground = isBackground
			buf.Reset()
			buf.WriteRune(r)
		case isBackground && !currentBackground:
			components = appendComponent(components, &buf, value, cfg)
			currentBackground = isBackground
			buf.Reset()
			buf.WriteRune(r)
		}
	}
	if currentBackground {
		components = appendComponent(components, &buf, value, backgroundRunesCfg)
	} else {
		components = appendComponent(components, &buf, value, cfg)
	}
	return components
}

func appendComponent(
	components []component.Floating, buf *strings.Builder,
	value any, cfg component.StringConfig,
) []component.Floating {
	str := buf.String()
	if strings.Contains(str, "%s") || strings.Contains(str, "%d") {
		str = fmt.Sprintf(str, value)
	}
	components = append(components,
		component.NewStringWithConfig(str, cfg),
	)
	return components
}
