// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/browser.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OpenFileRequest struct {
	File                 string   `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpenFileRequest) Reset()         { *m = OpenFileRequest{} }
func (m *OpenFileRequest) String() string { return proto.CompactTextString(m) }
func (*OpenFileRequest) ProtoMessage()    {}
func (*OpenFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2117966f04d6c9a0, []int{0}
}

func (m *OpenFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenFileRequest.Unmarshal(m, b)
}
func (m *OpenFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenFileRequest.Marshal(b, m, deterministic)
}
func (m *OpenFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenFileRequest.Merge(m, src)
}
func (m *OpenFileRequest) XXX_Size() int {
	return xxx_messageInfo_OpenFileRequest.Size(m)
}
func (m *OpenFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OpenFileRequest proto.InternalMessageInfo

func (m *OpenFileRequest) GetFile() string {
	if m != nil {
		return m.File
	}
	return ""
}

type OpenFileResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpenFileResponse) Reset()         { *m = OpenFileResponse{} }
func (m *OpenFileResponse) String() string { return proto.CompactTextString(m) }
func (*OpenFileResponse) ProtoMessage()    {}
func (*OpenFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2117966f04d6c9a0, []int{1}
}

func (m *OpenFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenFileResponse.Unmarshal(m, b)
}
func (m *OpenFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenFileResponse.Marshal(b, m, deterministic)
}
func (m *OpenFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenFileResponse.Merge(m, src)
}
func (m *OpenFileResponse) XXX_Size() int {
	return xxx_messageInfo_OpenFileResponse.Size(m)
}
func (m *OpenFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OpenFileResponse proto.InternalMessageInfo

type SetMessageRequest struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetMessageRequest) Reset()         { *m = SetMessageRequest{} }
func (m *SetMessageRequest) String() string { return proto.CompactTextString(m) }
func (*SetMessageRequest) ProtoMessage()    {}
func (*SetMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2117966f04d6c9a0, []int{2}
}

func (m *SetMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetMessageRequest.Unmarshal(m, b)
}
func (m *SetMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetMessageRequest.Marshal(b, m, deterministic)
}
func (m *SetMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetMessageRequest.Merge(m, src)
}
func (m *SetMessageRequest) XXX_Size() int {
	return xxx_messageInfo_SetMessageRequest.Size(m)
}
func (m *SetMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetMessageRequest proto.InternalMessageInfo

func (m *SetMessageRequest) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type SetMessageResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetMessageResponse) Reset()         { *m = SetMessageResponse{} }
func (m *SetMessageResponse) String() string { return proto.CompactTextString(m) }
func (*SetMessageResponse) ProtoMessage()    {}
func (*SetMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2117966f04d6c9a0, []int{3}
}

func (m *SetMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetMessageResponse.Unmarshal(m, b)
}
func (m *SetMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetMessageResponse.Marshal(b, m, deterministic)
}
func (m *SetMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetMessageResponse.Merge(m, src)
}
func (m *SetMessageResponse) XXX_Size() int {
	return xxx_messageInfo_SetMessageResponse.Size(m)
}
func (m *SetMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetMessageResponse proto.InternalMessageInfo

type Mapping struct {
	From                 *Event   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   *Event   `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Mapping) Reset()         { *m = Mapping{} }
func (m *Mapping) String() string { return proto.CompactTextString(m) }
func (*Mapping) ProtoMessage()    {}
func (*Mapping) Descriptor() ([]byte, []int) {
	return fileDescriptor_2117966f04d6c9a0, []int{4}
}

func (m *Mapping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Mapping.Unmarshal(m, b)
}
func (m *Mapping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Mapping.Marshal(b, m, deterministic)
}
func (m *Mapping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mapping.Merge(m, src)
}
func (m *Mapping) XXX_Size() int {
	return xxx_messageInfo_Mapping.Size(m)
}
func (m *Mapping) XXX_DiscardUnknown() {
	xxx_messageInfo_Mapping.DiscardUnknown(m)
}

var xxx_messageInfo_Mapping proto.InternalMessageInfo

func (m *Mapping) GetFrom() *Event {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *Mapping) GetTo() *Event {
	if m != nil {
		return m.To
	}
	return nil
}

type MergeKeyMapRequest struct {
	Mappings             []*Mapping `protobuf:"bytes,1,rep,name=mappings,proto3" json:"mappings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *MergeKeyMapRequest) Reset()         { *m = MergeKeyMapRequest{} }
func (m *MergeKeyMapRequest) String() string { return proto.CompactTextString(m) }
func (*MergeKeyMapRequest) ProtoMessage()    {}
func (*MergeKeyMapRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2117966f04d6c9a0, []int{5}
}

func (m *MergeKeyMapRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MergeKeyMapRequest.Unmarshal(m, b)
}
func (m *MergeKeyMapRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MergeKeyMapRequest.Marshal(b, m, deterministic)
}
func (m *MergeKeyMapRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MergeKeyMapRequest.Merge(m, src)
}
func (m *MergeKeyMapRequest) XXX_Size() int {
	return xxx_messageInfo_MergeKeyMapRequest.Size(m)
}
func (m *MergeKeyMapRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MergeKeyMapRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MergeKeyMapRequest proto.InternalMessageInfo

func (m *MergeKeyMapRequest) GetMappings() []*Mapping {
	if m != nil {
		return m.Mappings
	}
	return nil
}

type MergeKeyMapResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MergeKeyMapResponse) Reset()         { *m = MergeKeyMapResponse{} }
func (m *MergeKeyMapResponse) String() string { return proto.CompactTextString(m) }
func (*MergeKeyMapResponse) ProtoMessage()    {}
func (*MergeKeyMapResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2117966f04d6c9a0, []int{6}
}

func (m *MergeKeyMapResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MergeKeyMapResponse.Unmarshal(m, b)
}
func (m *MergeKeyMapResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MergeKeyMapResponse.Marshal(b, m, deterministic)
}
func (m *MergeKeyMapResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MergeKeyMapResponse.Merge(m, src)
}
func (m *MergeKeyMapResponse) XXX_Size() int {
	return xxx_messageInfo_MergeKeyMapResponse.Size(m)
}
func (m *MergeKeyMapResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MergeKeyMapResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MergeKeyMapResponse proto.InternalMessageInfo

type SplitRequest struct {
	HandlerId            uint32   `protobuf:"varint,1,opt,name=handler_id,json=handlerId,proto3" json:"handler_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SplitRequest) Reset()         { *m = SplitRequest{} }
func (m *SplitRequest) String() string { return proto.CompactTextString(m) }
func (*SplitRequest) ProtoMessage()    {}
func (*SplitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2117966f04d6c9a0, []int{7}
}

func (m *SplitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SplitRequest.Unmarshal(m, b)
}
func (m *SplitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SplitRequest.Marshal(b, m, deterministic)
}
func (m *SplitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SplitRequest.Merge(m, src)
}
func (m *SplitRequest) XXX_Size() int {
	return xxx_messageInfo_SplitRequest.Size(m)
}
func (m *SplitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SplitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SplitRequest proto.InternalMessageInfo

func (m *SplitRequest) GetHandlerId() uint32 {
	if m != nil {
		return m.HandlerId
	}
	return 0
}

type SplitResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SplitResponse) Reset()         { *m = SplitResponse{} }
func (m *SplitResponse) String() string { return proto.CompactTextString(m) }
func (*SplitResponse) ProtoMessage()    {}
func (*SplitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2117966f04d6c9a0, []int{8}
}

func (m *SplitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SplitResponse.Unmarshal(m, b)
}
func (m *SplitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SplitResponse.Marshal(b, m, deterministic)
}
func (m *SplitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SplitResponse.Merge(m, src)
}
func (m *SplitResponse) XXX_Size() int {
	return xxx_messageInfo_SplitResponse.Size(m)
}
func (m *SplitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SplitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SplitResponse proto.InternalMessageInfo

type SubscribeRequest struct {
	Ev                   *Event   `protobuf:"bytes,1,opt,name=ev,proto3" json:"ev,omitempty"`
	HandlerId            uint32   `protobuf:"varint,2,opt,name=handler_id,json=handlerId,proto3" json:"handler_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeRequest) Reset()         { *m = SubscribeRequest{} }
func (m *SubscribeRequest) String() string { return proto.CompactTextString(m) }
func (*SubscribeRequest) ProtoMessage()    {}
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2117966f04d6c9a0, []int{9}
}

func (m *SubscribeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeRequest.Unmarshal(m, b)
}
func (m *SubscribeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeRequest.Marshal(b, m, deterministic)
}
func (m *SubscribeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeRequest.Merge(m, src)
}
func (m *SubscribeRequest) XXX_Size() int {
	return xxx_messageInfo_SubscribeRequest.Size(m)
}
func (m *SubscribeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeRequest proto.InternalMessageInfo

func (m *SubscribeRequest) GetEv() *Event {
	if m != nil {
		return m.Ev
	}
	return nil
}

func (m *SubscribeRequest) GetHandlerId() uint32 {
	if m != nil {
		return m.HandlerId
	}
	return 0
}

type SubscribeResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeResponse) Reset()         { *m = SubscribeResponse{} }
func (m *SubscribeResponse) String() string { return proto.CompactTextString(m) }
func (*SubscribeResponse) ProtoMessage()    {}
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2117966f04d6c9a0, []int{10}
}

func (m *SubscribeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeResponse.Unmarshal(m, b)
}
func (m *SubscribeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeResponse.Marshal(b, m, deterministic)
}
func (m *SubscribeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeResponse.Merge(m, src)
}
func (m *SubscribeResponse) XXX_Size() int {
	return xxx_messageInfo_SubscribeResponse.Size(m)
}
func (m *SubscribeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeResponse proto.InternalMessageInfo

type HandleEventRequest struct {
	Ev                   *Event   `protobuf:"bytes,1,opt,name=ev,proto3" json:"ev,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HandleEventRequest) Reset()         { *m = HandleEventRequest{} }
func (m *HandleEventRequest) String() string { return proto.CompactTextString(m) }
func (*HandleEventRequest) ProtoMessage()    {}
func (*HandleEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2117966f04d6c9a0, []int{11}
}

func (m *HandleEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandleEventRequest.Unmarshal(m, b)
}
func (m *HandleEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandleEventRequest.Marshal(b, m, deterministic)
}
func (m *HandleEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandleEventRequest.Merge(m, src)
}
func (m *HandleEventRequest) XXX_Size() int {
	return xxx_messageInfo_HandleEventRequest.Size(m)
}
func (m *HandleEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HandleEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HandleEventRequest proto.InternalMessageInfo

func (m *HandleEventRequest) GetEv() *Event {
	if m != nil {
		return m.Ev
	}
	return nil
}

type HandleEventResponse struct {
	Exit                 bool     `protobuf:"varint,1,opt,name=exit,proto3" json:"exit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HandleEventResponse) Reset()         { *m = HandleEventResponse{} }
func (m *HandleEventResponse) String() string { return proto.CompactTextString(m) }
func (*HandleEventResponse) ProtoMessage()    {}
func (*HandleEventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2117966f04d6c9a0, []int{12}
}

func (m *HandleEventResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandleEventResponse.Unmarshal(m, b)
}
func (m *HandleEventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandleEventResponse.Marshal(b, m, deterministic)
}
func (m *HandleEventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandleEventResponse.Merge(m, src)
}
func (m *HandleEventResponse) XXX_Size() int {
	return xxx_messageInfo_HandleEventResponse.Size(m)
}
func (m *HandleEventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HandleEventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HandleEventResponse proto.InternalMessageInfo

func (m *HandleEventResponse) GetExit() bool {
	if m != nil {
		return m.Exit
	}
	return false
}

func init() {
	proto.RegisterType((*OpenFileRequest)(nil), "proto.OpenFileRequest")
	proto.RegisterType((*OpenFileResponse)(nil), "proto.OpenFileResponse")
	proto.RegisterType((*SetMessageRequest)(nil), "proto.SetMessageRequest")
	proto.RegisterType((*SetMessageResponse)(nil), "proto.SetMessageResponse")
	proto.RegisterType((*Mapping)(nil), "proto.Mapping")
	proto.RegisterType((*MergeKeyMapRequest)(nil), "proto.MergeKeyMapRequest")
	proto.RegisterType((*MergeKeyMapResponse)(nil), "proto.MergeKeyMapResponse")
	proto.RegisterType((*SplitRequest)(nil), "proto.SplitRequest")
	proto.RegisterType((*SplitResponse)(nil), "proto.SplitResponse")
	proto.RegisterType((*SubscribeRequest)(nil), "proto.SubscribeRequest")
	proto.RegisterType((*SubscribeResponse)(nil), "proto.SubscribeResponse")
	proto.RegisterType((*HandleEventRequest)(nil), "proto.HandleEventRequest")
	proto.RegisterType((*HandleEventResponse)(nil), "proto.HandleEventResponse")
}

func init() { proto.RegisterFile("proto/browser.proto", fileDescriptor_2117966f04d6c9a0) }

var fileDescriptor_2117966f04d6c9a0 = []byte{
	// 526 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x52, 0x61, 0x6f, 0xd3, 0x30,
	0x10, 0x55, 0xb3, 0x31, 0xda, 0x6b, 0xbb, 0xb5, 0x6e, 0x81, 0x12, 0x0d, 0xa9, 0x8a, 0x34, 0x69,
	0x20, 0x31, 0xa4, 0xf0, 0x11, 0x69, 0x50, 0x04, 0x68, 0x15, 0x84, 0x8e, 0x54, 0x82, 0x8f, 0x28,
	0x59, 0xaf, 0xa9, 0xa5, 0x34, 0x0e, 0xb6, 0xdb, 0x02, 0x3f, 0x84, 0xdf, 0x8b, 0x62, 0x3b, 0x59,
	0xdb, 0xe4, 0x03, 0x13, 0x9f, 0xe2, 0xf8, 0xdd, 0x7b, 0x77, 0xbe, 0xf7, 0xa0, 0x97, 0x72, 0x26,
	0xd9, 0x8b, 0x90, 0xb3, 0x8d, 0x40, 0x7e, 0xa1, 0xfe, 0xc8, 0x3d, 0xf5, 0xb1, 0x3b, 0x1a, 0x93,
	0xc8, 0x97, 0x1a, 0x70, 0xce, 0xe0, 0x64, 0x92, 0x62, 0xf2, 0x81, 0xc6, 0xe8, 0xe3, 0x8f, 0x15,
	0x0a, 0x49, 0x08, 0x1c, 0xce, 0x69, 0x8c, 0x83, 0xda, 0xb0, 0x76, 0xde, 0xf0, 0xd5, 0xd9, 0x21,
	0xd0, 0xb9, 0x2d, 0x13, 0x29, 0x4b, 0x04, 0x3a, 0x67, 0xd0, 0x9d, 0xa2, 0xf4, 0x50, 0x88, 0x20,
	0x2a, 0xc8, 0x1d, 0x38, 0x58, 0x8a, 0xc8, 0x70, 0xb3, 0xa3, 0xd3, 0x07, 0xb2, 0x5d, 0x66, 0xc8,
	0x63, 0xb8, 0xef, 0x05, 0x69, 0x4a, 0x93, 0x88, 0x0c, 0xe1, 0x70, 0xce, 0xd9, 0x52, 0x71, 0x9a,
	0x6e, 0x4b, 0x0f, 0x76, 0xf1, 0x7e, 0x8d, 0x89, 0xf4, 0x15, 0x42, 0x4e, 0xc1, 0x92, 0x6c, 0x60,
	0x55, 0xe0, 0x96, 0x64, 0xce, 0x1b, 0x20, 0x1e, 0xf2, 0x08, 0x3f, 0xe2, 0x2f, 0x2f, 0x48, 0xf3,
	0x41, 0x9e, 0x41, 0x7d, 0xa9, 0x1b, 0x88, 0x41, 0x6d, 0x78, 0x70, 0xde, 0x74, 0x8f, 0x0d, 0xd3,
	0xf4, 0xf5, 0x0b, 0xdc, 0x79, 0x00, 0xbd, 0x1d, 0x05, 0x33, 0xe3, 0x73, 0x68, 0x4d, 0xd3, 0x98,
	0xca, 0x5c, 0xf2, 0x09, 0xc0, 0x22, 0x48, 0x66, 0x31, 0xf2, 0xef, 0x74, 0xa6, 0xc6, 0x6d, 0xfb,
	0x0d, 0x73, 0x33, 0x9e, 0x39, 0x27, 0xd0, 0x36, 0xe5, 0x86, 0x3f, 0x81, 0xce, 0x74, 0x15, 0x8a,
	0x1b, 0x4e, 0xc3, 0x62, 0x3f, 0xa7, 0x60, 0xe1, 0xba, 0xf2, 0xa9, 0x16, 0xae, 0xf7, 0x3a, 0x58,
	0xfb, 0x1d, 0x7a, 0xd0, 0xdd, 0x12, 0x34, 0x5d, 0x5c, 0x20, 0x57, 0xaa, 0x42, 0xcb, 0xfc, 0x4b,
	0x1f, 0xe7, 0x29, 0xf4, 0x76, 0x38, 0x5a, 0x2a, 0x73, 0x1e, 0x7f, 0x52, 0xa9, 0x68, 0x75, 0x5f,
	0x9d, 0xdd, 0x31, 0x40, 0xe6, 0x7a, 0xe6, 0x3e, 0x72, 0xf2, 0x0a, 0xea, 0x79, 0x0e, 0xc8, 0x43,
	0x23, 0xbb, 0x97, 0x1f, 0xfb, 0x51, 0xe9, 0x5e, 0xcb, 0xbb, 0x9f, 0xa1, 0x91, 0xc5, 0x00, 0x93,
	0x08, 0x39, 0x19, 0x01, 0xdc, 0xc6, 0x82, 0x0c, 0x0c, 0xa7, 0x14, 0x28, 0xfb, 0x71, 0x05, 0x62,
	0xf4, 0xbe, 0x40, 0x43, 0x3b, 0x96, 0x22, 0x27, 0xef, 0xa0, 0xb9, 0xe5, 0x21, 0xc9, 0x69, 0xe5,
	0x64, 0xd8, 0x76, 0x15, 0x64, 0x24, 0xaf, 0xe1, 0x58, 0xad, 0xe4, 0x7a, 0x15, 0xc6, 0x54, 0x2c,
	0x90, 0x93, 0x4b, 0x68, 0x14, 0x3b, 0x27, 0xf9, 0xd3, 0xf6, 0x6d, 0xb5, 0x07, 0x65, 0xc0, 0x28,
	0xfe, 0xb1, 0xa0, 0xfd, 0x8d, 0x26, 0x33, 0xb6, 0xf1, 0x82, 0x24, 0xc8, 0x5e, 0xfe, 0x1a, 0x88,
	0xca, 0xc9, 0x57, 0xe4, 0x92, 0xde, 0x04, 0xb1, 0x4f, 0xa3, 0x85, 0x24, 0xbd, 0x5c, 0x61, 0x2b,
	0x71, 0x76, 0x7f, 0xf7, 0xd2, 0xd8, 0x74, 0x09, 0xdd, 0x1d, 0x81, 0x4f, 0x38, 0xbf, 0x13, 0x7f,
	0x04, 0x7d, 0x75, 0x71, 0xc5, 0x38, 0xfd, 0xcd, 0x12, 0x19, 0xc4, 0xa3, 0x90, 0xad, 0xf1, 0xff,
	0x24, 0xde, 0x62, 0xcc, 0x36, 0x77, 0x90, 0x70, 0x27, 0xd0, 0x52, 0xab, 0xd6, 0x41, 0xcc, 0xd6,
	0x72, 0xa4, 0x8f, 0x85, 0x77, 0xe5, 0x58, 0x17, 0xde, 0x55, 0xa4, 0x37, 0x3c, 0x52, 0xd0, 0xcb,
	0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xfc, 0x4d, 0xc1, 0xba, 0x01, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// FileOpenerClient is the client API for FileOpener service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FileOpenerClient interface {
	OpenFile(ctx context.Context, in *OpenFileRequest, opts ...grpc.CallOption) (*OpenFileResponse, error)
}

type fileOpenerClient struct {
	cc grpc.ClientConnInterface
}

func NewFileOpenerClient(cc grpc.ClientConnInterface) FileOpenerClient {
	return &fileOpenerClient{cc}
}

func (c *fileOpenerClient) OpenFile(ctx context.Context, in *OpenFileRequest, opts ...grpc.CallOption) (*OpenFileResponse, error) {
	out := new(OpenFileResponse)
	err := c.cc.Invoke(ctx, "/proto.FileOpener/OpenFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FileOpenerServer is the server API for FileOpener service.
type FileOpenerServer interface {
	OpenFile(context.Context, *OpenFileRequest) (*OpenFileResponse, error)
}

// UnimplementedFileOpenerServer can be embedded to have forward compatible implementations.
type UnimplementedFileOpenerServer struct {
}

func (*UnimplementedFileOpenerServer) OpenFile(ctx context.Context, req *OpenFileRequest) (*OpenFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OpenFile not implemented")
}

func RegisterFileOpenerServer(s *grpc.Server, srv FileOpenerServer) {
	s.RegisterService(&_FileOpener_serviceDesc, srv)
}

func _FileOpener_OpenFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileOpenerServer).OpenFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.FileOpener/OpenFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileOpenerServer).OpenFile(ctx, req.(*OpenFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FileOpener_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.FileOpener",
	HandlerType: (*FileOpenerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OpenFile",
			Handler:    _FileOpener_OpenFile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/browser.proto",
}

// MessengerClient is the client API for Messenger service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MessengerClient interface {
	SetMessage(ctx context.Context, in *SetMessageRequest, opts ...grpc.CallOption) (*SetMessageResponse, error)
}

type messengerClient struct {
	cc grpc.ClientConnInterface
}

func NewMessengerClient(cc grpc.ClientConnInterface) MessengerClient {
	return &messengerClient{cc}
}

func (c *messengerClient) SetMessage(ctx context.Context, in *SetMessageRequest, opts ...grpc.CallOption) (*SetMessageResponse, error) {
	out := new(SetMessageResponse)
	err := c.cc.Invoke(ctx, "/proto.Messenger/SetMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessengerServer is the server API for Messenger service.
type MessengerServer interface {
	SetMessage(context.Context, *SetMessageRequest) (*SetMessageResponse, error)
}

// UnimplementedMessengerServer can be embedded to have forward compatible implementations.
type UnimplementedMessengerServer struct {
}

func (*UnimplementedMessengerServer) SetMessage(ctx context.Context, req *SetMessageRequest) (*SetMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetMessage not implemented")
}

func RegisterMessengerServer(s *grpc.Server, srv MessengerServer) {
	s.RegisterService(&_Messenger_serviceDesc, srv)
}

func _Messenger_SetMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessengerServer).SetMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Messenger/SetMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessengerServer).SetMessage(ctx, req.(*SetMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Messenger_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Messenger",
	HandlerType: (*MessengerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetMessage",
			Handler:    _Messenger_SetMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/browser.proto",
}

// KeyMapperClient is the client API for KeyMapper service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type KeyMapperClient interface {
	MergeKeyMap(ctx context.Context, in *MergeKeyMapRequest, opts ...grpc.CallOption) (*MergeKeyMapResponse, error)
}

type keyMapperClient struct {
	cc grpc.ClientConnInterface
}

func NewKeyMapperClient(cc grpc.ClientConnInterface) KeyMapperClient {
	return &keyMapperClient{cc}
}

func (c *keyMapperClient) MergeKeyMap(ctx context.Context, in *MergeKeyMapRequest, opts ...grpc.CallOption) (*MergeKeyMapResponse, error) {
	out := new(MergeKeyMapResponse)
	err := c.cc.Invoke(ctx, "/proto.KeyMapper/MergeKeyMap", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KeyMapperServer is the server API for KeyMapper service.
type KeyMapperServer interface {
	MergeKeyMap(context.Context, *MergeKeyMapRequest) (*MergeKeyMapResponse, error)
}

// UnimplementedKeyMapperServer can be embedded to have forward compatible implementations.
type UnimplementedKeyMapperServer struct {
}

func (*UnimplementedKeyMapperServer) MergeKeyMap(ctx context.Context, req *MergeKeyMapRequest) (*MergeKeyMapResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MergeKeyMap not implemented")
}

func RegisterKeyMapperServer(s *grpc.Server, srv KeyMapperServer) {
	s.RegisterService(&_KeyMapper_serviceDesc, srv)
}

func _KeyMapper_MergeKeyMap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MergeKeyMapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyMapperServer).MergeKeyMap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.KeyMapper/MergeKeyMap",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyMapperServer).MergeKeyMap(ctx, req.(*MergeKeyMapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _KeyMapper_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.KeyMapper",
	HandlerType: (*KeyMapperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MergeKeyMap",
			Handler:    _KeyMapper_MergeKeyMap_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/browser.proto",
}

// EventPublisherClient is the client API for EventPublisher service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EventPublisherClient interface {
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (*SubscribeResponse, error)
}

type eventPublisherClient struct {
	cc grpc.ClientConnInterface
}

func NewEventPublisherClient(cc grpc.ClientConnInterface) EventPublisherClient {
	return &eventPublisherClient{cc}
}

func (c *eventPublisherClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (*SubscribeResponse, error) {
	out := new(SubscribeResponse)
	err := c.cc.Invoke(ctx, "/proto.EventPublisher/Subscribe", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventPublisherServer is the server API for EventPublisher service.
type EventPublisherServer interface {
	Subscribe(context.Context, *SubscribeRequest) (*SubscribeResponse, error)
}

// UnimplementedEventPublisherServer can be embedded to have forward compatible implementations.
type UnimplementedEventPublisherServer struct {
}

func (*UnimplementedEventPublisherServer) Subscribe(ctx context.Context, req *SubscribeRequest) (*SubscribeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}

func RegisterEventPublisherServer(s *grpc.Server, srv EventPublisherServer) {
	s.RegisterService(&_EventPublisher_serviceDesc, srv)
}

func _EventPublisher_Subscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventPublisherServer).Subscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EventPublisher/Subscribe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventPublisherServer).Subscribe(ctx, req.(*SubscribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _EventPublisher_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.EventPublisher",
	HandlerType: (*EventPublisherServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Subscribe",
			Handler:    _EventPublisher_Subscribe_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/browser.proto",
}

// WindowManagerClient is the client API for WindowManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WindowManagerClient interface {
	SplitVerticalRight(ctx context.Context, in *SplitRequest, opts ...grpc.CallOption) (*SplitResponse, error)
	SplitVerticalLeft(ctx context.Context, in *SplitRequest, opts ...grpc.CallOption) (*SplitResponse, error)
	SplitHorizontalAbove(ctx context.Context, in *SplitRequest, opts ...grpc.CallOption) (*SplitResponse, error)
	SplitHorizontalBelow(ctx context.Context, in *SplitRequest, opts ...grpc.CallOption) (*SplitResponse, error)
}

type windowManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewWindowManagerClient(cc grpc.ClientConnInterface) WindowManagerClient {
	return &windowManagerClient{cc}
}

func (c *windowManagerClient) SplitVerticalRight(ctx context.Context, in *SplitRequest, opts ...grpc.CallOption) (*SplitResponse, error) {
	out := new(SplitResponse)
	err := c.cc.Invoke(ctx, "/proto.WindowManager/SplitVerticalRight", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *windowManagerClient) SplitVerticalLeft(ctx context.Context, in *SplitRequest, opts ...grpc.CallOption) (*SplitResponse, error) {
	out := new(SplitResponse)
	err := c.cc.Invoke(ctx, "/proto.WindowManager/SplitVerticalLeft", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *windowManagerClient) SplitHorizontalAbove(ctx context.Context, in *SplitRequest, opts ...grpc.CallOption) (*SplitResponse, error) {
	out := new(SplitResponse)
	err := c.cc.Invoke(ctx, "/proto.WindowManager/SplitHorizontalAbove", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *windowManagerClient) SplitHorizontalBelow(ctx context.Context, in *SplitRequest, opts ...grpc.CallOption) (*SplitResponse, error) {
	out := new(SplitResponse)
	err := c.cc.Invoke(ctx, "/proto.WindowManager/SplitHorizontalBelow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WindowManagerServer is the server API for WindowManager service.
type WindowManagerServer interface {
	SplitVerticalRight(context.Context, *SplitRequest) (*SplitResponse, error)
	SplitVerticalLeft(context.Context, *SplitRequest) (*SplitResponse, error)
	SplitHorizontalAbove(context.Context, *SplitRequest) (*SplitResponse, error)
	SplitHorizontalBelow(context.Context, *SplitRequest) (*SplitResponse, error)
}

// UnimplementedWindowManagerServer can be embedded to have forward compatible implementations.
type UnimplementedWindowManagerServer struct {
}

func (*UnimplementedWindowManagerServer) SplitVerticalRight(ctx context.Context, req *SplitRequest) (*SplitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SplitVerticalRight not implemented")
}
func (*UnimplementedWindowManagerServer) SplitVerticalLeft(ctx context.Context, req *SplitRequest) (*SplitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SplitVerticalLeft not implemented")
}
func (*UnimplementedWindowManagerServer) SplitHorizontalAbove(ctx context.Context, req *SplitRequest) (*SplitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SplitHorizontalAbove not implemented")
}
func (*UnimplementedWindowManagerServer) SplitHorizontalBelow(ctx context.Context, req *SplitRequest) (*SplitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SplitHorizontalBelow not implemented")
}

func RegisterWindowManagerServer(s *grpc.Server, srv WindowManagerServer) {
	s.RegisterService(&_WindowManager_serviceDesc, srv)
}

func _WindowManager_SplitVerticalRight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SplitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WindowManagerServer).SplitVerticalRight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.WindowManager/SplitVerticalRight",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WindowManagerServer).SplitVerticalRight(ctx, req.(*SplitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WindowManager_SplitVerticalLeft_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SplitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WindowManagerServer).SplitVerticalLeft(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.WindowManager/SplitVerticalLeft",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WindowManagerServer).SplitVerticalLeft(ctx, req.(*SplitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WindowManager_SplitHorizontalAbove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SplitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WindowManagerServer).SplitHorizontalAbove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.WindowManager/SplitHorizontalAbove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WindowManagerServer).SplitHorizontalAbove(ctx, req.(*SplitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WindowManager_SplitHorizontalBelow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SplitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WindowManagerServer).SplitHorizontalBelow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.WindowManager/SplitHorizontalBelow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WindowManagerServer).SplitHorizontalBelow(ctx, req.(*SplitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WindowManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.WindowManager",
	HandlerType: (*WindowManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SplitVerticalRight",
			Handler:    _WindowManager_SplitVerticalRight_Handler,
		},
		{
			MethodName: "SplitVerticalLeft",
			Handler:    _WindowManager_SplitVerticalLeft_Handler,
		},
		{
			MethodName: "SplitHorizontalAbove",
			Handler:    _WindowManager_SplitHorizontalAbove_Handler,
		},
		{
			MethodName: "SplitHorizontalBelow",
			Handler:    _WindowManager_SplitHorizontalBelow_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/browser.proto",
}

// EventHandlerClient is the client API for EventHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EventHandlerClient interface {
	Handle(ctx context.Context, in *HandleEventRequest, opts ...grpc.CallOption) (*HandleEventResponse, error)
}

type eventHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewEventHandlerClient(cc grpc.ClientConnInterface) EventHandlerClient {
	return &eventHandlerClient{cc}
}

func (c *eventHandlerClient) Handle(ctx context.Context, in *HandleEventRequest, opts ...grpc.CallOption) (*HandleEventResponse, error) {
	out := new(HandleEventResponse)
	err := c.cc.Invoke(ctx, "/proto.EventHandler/Handle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventHandlerServer is the server API for EventHandler service.
type EventHandlerServer interface {
	Handle(context.Context, *HandleEventRequest) (*HandleEventResponse, error)
}

// UnimplementedEventHandlerServer can be embedded to have forward compatible implementations.
type UnimplementedEventHandlerServer struct {
}

func (*UnimplementedEventHandlerServer) Handle(ctx context.Context, req *HandleEventRequest) (*HandleEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Handle not implemented")
}

func RegisterEventHandlerServer(s *grpc.Server, srv EventHandlerServer) {
	s.RegisterService(&_EventHandler_serviceDesc, srv)
}

func _EventHandler_Handle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventHandlerServer).Handle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EventHandler/Handle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventHandlerServer).Handle(ctx, req.(*HandleEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _EventHandler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.EventHandler",
	HandlerType: (*EventHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Handle",
			Handler:    _EventHandler_Handle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/browser.proto",
}
