syntax = "proto3";

import "term.proto";
import "tui.proto";

package proto;

message OpenResourceRequest {
    string resource = 1;
}

message OpenResourceResponse {
	uint64 handler_id = 1;
}

message SetMessageRequest {
	string msg = 1;
}

message SetMessageResponse {}

message Mapping {
	Event from = 1;
	Event to = 2;
}

message MergeKeyMapRequest {
	repeated Mapping mappings = 1;
}

message MergeKeyMapResponse {
}

message SplitRequest {
	uint64 handler_id = 1;
}

message SplitResponse {
	uint64 window_id = 1;
}

message FloatingWindowRequest {
	uint64 handler_id = 1;
	Coordinates at = 2;
	int32 height = 3;
	int32 width = 4;
}

message FloatingWindowResponse {
	uint64 window_id = 1;
}


message FocusRequest {
}

message FocusResponse {
	uint64 window_id = 1;
}


message SubscribeRequest {
	Event ev = 1;
	uint64 handler_id = 2;
}

message SubscribeResponse {
}

message PublishRequest {
	Event ev = 1;
}

message PublishResponse {
}

service ResourceOpener {
	rpc Open(OpenResourceRequest) returns (OpenResourceResponse);
}

service Messenger {
	rpc SetMessage(SetMessageRequest) returns (SetMessageResponse);
}

service KeyMapper {
	rpc MergeKeyMap(MergeKeyMapRequest) returns (MergeKeyMapResponse);
}

service EventSubscriber {
	rpc Subscribe(SubscribeRequest) returns (SubscribeResponse);
}

service EventPublisher {
	rpc Publish(PublishRequest) returns (PublishResponse);
}

service WindowManager {
	rpc Focus(FocusRequest) returns (FocusResponse);
	rpc SplitVerticalRight(SplitRequest) returns (SplitResponse);
	rpc SplitVerticalLeft(SplitRequest) returns (SplitResponse);
	rpc SplitHorizontalAbove(SplitRequest) returns (SplitResponse);
	rpc SplitHorizontalBelow(SplitRequest) returns (SplitResponse);
	rpc FloatingWindow(FloatingWindowRequest) returns (FloatingWindowResponse);
}

message WindowCloseRequest {
}

message WindowCloseResponse {
}

message WindowSetContentRequest {
	uint64 handler_id = 1;
}

message WindowSetContentResponse {
}

message WindowContentRequest {
}

message WindowContentResponse {
	uint64 handler_id = 1;
}

service Window {
	rpc SetContent(WindowSetContentRequest) returns (WindowSetContentResponse);
	rpc Content(WindowContentRequest) returns (WindowContentResponse);
	rpc Close(WindowCloseRequest) returns (WindowCloseResponse);
}
