// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.16.0
// source: clipboard.proto

package proto

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type SetRegisterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RegisterId string `protobuf:"bytes,1,opt,name=register_id,json=registerId,proto3" json:"register_id,omitempty"`
	HandlerId  uint64 `protobuf:"varint,2,opt,name=handler_id,json=handlerId,proto3" json:"handler_id,omitempty"`
}

func (x *SetRegisterRequest) Reset() {
	*x = SetRegisterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clipboard_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRegisterRequest) ProtoMessage() {}

func (x *SetRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clipboard_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRegisterRequest.ProtoReflect.Descriptor instead.
func (*SetRegisterRequest) Descriptor() ([]byte, []int) {
	return file_clipboard_proto_rawDescGZIP(), []int{0}
}

func (x *SetRegisterRequest) GetRegisterId() string {
	if x != nil {
		return x.RegisterId
	}
	return ""
}

func (x *SetRegisterRequest) GetHandlerId() uint64 {
	if x != nil {
		return x.HandlerId
	}
	return 0
}

type SetRegisterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetRegisterResponse) Reset() {
	*x = SetRegisterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clipboard_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetRegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRegisterResponse) ProtoMessage() {}

func (x *SetRegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clipboard_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRegisterResponse.ProtoReflect.Descriptor instead.
func (*SetRegisterResponse) Descriptor() ([]byte, []int) {
	return file_clipboard_proto_rawDescGZIP(), []int{1}
}

type ClipboardCopyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ClipboardCopyRequest) Reset() {
	*x = ClipboardCopyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clipboard_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClipboardCopyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClipboardCopyRequest) ProtoMessage() {}

func (x *ClipboardCopyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clipboard_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClipboardCopyRequest.ProtoReflect.Descriptor instead.
func (*ClipboardCopyRequest) Descriptor() ([]byte, []int) {
	return file_clipboard_proto_rawDescGZIP(), []int{2}
}

func (x *ClipboardCopyRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type ClipboardCopyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ClipboardCopyResponse) Reset() {
	*x = ClipboardCopyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clipboard_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClipboardCopyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClipboardCopyResponse) ProtoMessage() {}

func (x *ClipboardCopyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clipboard_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClipboardCopyResponse.ProtoReflect.Descriptor instead.
func (*ClipboardCopyResponse) Descriptor() ([]byte, []int) {
	return file_clipboard_proto_rawDescGZIP(), []int{3}
}

type ClipboardPasteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ClipboardPasteRequest) Reset() {
	*x = ClipboardPasteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clipboard_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClipboardPasteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClipboardPasteRequest) ProtoMessage() {}

func (x *ClipboardPasteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clipboard_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClipboardPasteRequest.ProtoReflect.Descriptor instead.
func (*ClipboardPasteRequest) Descriptor() ([]byte, []int) {
	return file_clipboard_proto_rawDescGZIP(), []int{4}
}

type ClipboardPasteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ClipboardPasteResponse) Reset() {
	*x = ClipboardPasteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clipboard_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClipboardPasteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClipboardPasteResponse) ProtoMessage() {}

func (x *ClipboardPasteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clipboard_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClipboardPasteResponse.ProtoReflect.Descriptor instead.
func (*ClipboardPasteResponse) Descriptor() ([]byte, []int) {
	return file_clipboard_proto_rawDescGZIP(), []int{5}
}

func (x *ClipboardPasteResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_clipboard_proto protoreflect.FileDescriptor

var file_clipboard_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x63, 0x6c, 0x69, 0x70, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x54, 0x0a, 0x12, 0x53, 0x65, 0x74, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f,
	0x0a, 0x0b, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x1d, 0x0a, 0x0a, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x09, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x49, 0x64, 0x22, 0x15,
	0x0a, 0x13, 0x53, 0x65, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2a, 0x0a, 0x14, 0x43, 0x6c, 0x69, 0x70, 0x62, 0x6f, 0x61,
	0x72, 0x64, 0x43, 0x6f, 0x70, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x22, 0x17, 0x0a, 0x15, 0x43, 0x6c, 0x69, 0x70, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x43, 0x6f,
	0x70, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x17, 0x0a, 0x15, 0x43, 0x6c,
	0x69, 0x70, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x50, 0x61, 0x73, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x2c, 0x0a, 0x16, 0x43, 0x6c, 0x69, 0x70, 0x62, 0x6f, 0x61, 0x72, 0x64,
	0x50, 0x61, 0x73, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x32, 0x51, 0x0a, 0x09, 0x43, 0x6c, 0x69, 0x70, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x12, 0x44,
	0x0a, 0x0b, 0x53, 0x65, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x19, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x53, 0x65, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x32, 0x9c, 0x01, 0x0a, 0x11, 0x43, 0x6c, 0x69, 0x70, 0x62, 0x6f, 0x61,
	0x72, 0x64, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x41, 0x0a, 0x04, 0x43, 0x6f,
	0x70, 0x79, 0x12, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6c, 0x69, 0x70, 0x62,
	0x6f, 0x61, 0x72, 0x64, 0x43, 0x6f, 0x70, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6c, 0x69, 0x70, 0x62, 0x6f, 0x61, 0x72,
	0x64, 0x43, 0x6f, 0x70, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a,
	0x05, 0x50, 0x61, 0x73, 0x74, 0x65, 0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43,
	0x6c, 0x69, 0x70, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x50, 0x61, 0x73, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6c, 0x69,
	0x70, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x50, 0x61, 0x73, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_clipboard_proto_rawDescOnce sync.Once
	file_clipboard_proto_rawDescData = file_clipboard_proto_rawDesc
)

func file_clipboard_proto_rawDescGZIP() []byte {
	file_clipboard_proto_rawDescOnce.Do(func() {
		file_clipboard_proto_rawDescData = protoimpl.X.CompressGZIP(file_clipboard_proto_rawDescData)
	})
	return file_clipboard_proto_rawDescData
}

var file_clipboard_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_clipboard_proto_goTypes = []interface{}{
	(*SetRegisterRequest)(nil),     // 0: proto.SetRegisterRequest
	(*SetRegisterResponse)(nil),    // 1: proto.SetRegisterResponse
	(*ClipboardCopyRequest)(nil),   // 2: proto.ClipboardCopyRequest
	(*ClipboardCopyResponse)(nil),  // 3: proto.ClipboardCopyResponse
	(*ClipboardPasteRequest)(nil),  // 4: proto.ClipboardPasteRequest
	(*ClipboardPasteResponse)(nil), // 5: proto.ClipboardPasteResponse
}
var file_clipboard_proto_depIdxs = []int32{
	0, // 0: proto.Clipboard.SetRegister:input_type -> proto.SetRegisterRequest
	2, // 1: proto.ClipboardRegister.Copy:input_type -> proto.ClipboardCopyRequest
	4, // 2: proto.ClipboardRegister.Paste:input_type -> proto.ClipboardPasteRequest
	1, // 3: proto.Clipboard.SetRegister:output_type -> proto.SetRegisterResponse
	3, // 4: proto.ClipboardRegister.Copy:output_type -> proto.ClipboardCopyResponse
	5, // 5: proto.ClipboardRegister.Paste:output_type -> proto.ClipboardPasteResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_clipboard_proto_init() }
func file_clipboard_proto_init() {
	if File_clipboard_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_clipboard_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetRegisterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clipboard_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetRegisterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clipboard_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClipboardCopyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clipboard_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClipboardCopyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clipboard_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClipboardPasteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clipboard_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClipboardPasteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_clipboard_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_clipboard_proto_goTypes,
		DependencyIndexes: file_clipboard_proto_depIdxs,
		MessageInfos:      file_clipboard_proto_msgTypes,
	}.Build()
	File_clipboard_proto = out.File
	file_clipboard_proto_rawDesc = nil
	file_clipboard_proto_goTypes = nil
	file_clipboard_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ClipboardClient is the client API for Clipboard service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ClipboardClient interface {
	SetRegister(ctx context.Context, in *SetRegisterRequest, opts ...grpc.CallOption) (*SetRegisterResponse, error)
}

type clipboardClient struct {
	cc grpc.ClientConnInterface
}

func NewClipboardClient(cc grpc.ClientConnInterface) ClipboardClient {
	return &clipboardClient{cc}
}

func (c *clipboardClient) SetRegister(ctx context.Context, in *SetRegisterRequest, opts ...grpc.CallOption) (*SetRegisterResponse, error) {
	out := new(SetRegisterResponse)
	err := c.cc.Invoke(ctx, "/proto.Clipboard/SetRegister", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClipboardServer is the server API for Clipboard service.
type ClipboardServer interface {
	SetRegister(context.Context, *SetRegisterRequest) (*SetRegisterResponse, error)
}

// UnimplementedClipboardServer can be embedded to have forward compatible implementations.
type UnimplementedClipboardServer struct {
}

func (*UnimplementedClipboardServer) SetRegister(context.Context, *SetRegisterRequest) (*SetRegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetRegister not implemented")
}

func RegisterClipboardServer(s *grpc.Server, srv ClipboardServer) {
	s.RegisterService(&_Clipboard_serviceDesc, srv)
}

func _Clipboard_SetRegister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClipboardServer).SetRegister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Clipboard/SetRegister",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClipboardServer).SetRegister(ctx, req.(*SetRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Clipboard_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Clipboard",
	HandlerType: (*ClipboardServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetRegister",
			Handler:    _Clipboard_SetRegister_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "clipboard.proto",
}

// ClipboardRegisterClient is the client API for ClipboardRegister service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ClipboardRegisterClient interface {
	Copy(ctx context.Context, in *ClipboardCopyRequest, opts ...grpc.CallOption) (*ClipboardCopyResponse, error)
	Paste(ctx context.Context, in *ClipboardPasteRequest, opts ...grpc.CallOption) (*ClipboardPasteResponse, error)
}

type clipboardRegisterClient struct {
	cc grpc.ClientConnInterface
}

func NewClipboardRegisterClient(cc grpc.ClientConnInterface) ClipboardRegisterClient {
	return &clipboardRegisterClient{cc}
}

func (c *clipboardRegisterClient) Copy(ctx context.Context, in *ClipboardCopyRequest, opts ...grpc.CallOption) (*ClipboardCopyResponse, error) {
	out := new(ClipboardCopyResponse)
	err := c.cc.Invoke(ctx, "/proto.ClipboardRegister/Copy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clipboardRegisterClient) Paste(ctx context.Context, in *ClipboardPasteRequest, opts ...grpc.CallOption) (*ClipboardPasteResponse, error) {
	out := new(ClipboardPasteResponse)
	err := c.cc.Invoke(ctx, "/proto.ClipboardRegister/Paste", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClipboardRegisterServer is the server API for ClipboardRegister service.
type ClipboardRegisterServer interface {
	Copy(context.Context, *ClipboardCopyRequest) (*ClipboardCopyResponse, error)
	Paste(context.Context, *ClipboardPasteRequest) (*ClipboardPasteResponse, error)
}

// UnimplementedClipboardRegisterServer can be embedded to have forward compatible implementations.
type UnimplementedClipboardRegisterServer struct {
}

func (*UnimplementedClipboardRegisterServer) Copy(context.Context, *ClipboardCopyRequest) (*ClipboardCopyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Copy not implemented")
}
func (*UnimplementedClipboardRegisterServer) Paste(context.Context, *ClipboardPasteRequest) (*ClipboardPasteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Paste not implemented")
}

func RegisterClipboardRegisterServer(s *grpc.Server, srv ClipboardRegisterServer) {
	s.RegisterService(&_ClipboardRegister_serviceDesc, srv)
}

func _ClipboardRegister_Copy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClipboardCopyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClipboardRegisterServer).Copy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ClipboardRegister/Copy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClipboardRegisterServer).Copy(ctx, req.(*ClipboardCopyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClipboardRegister_Paste_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClipboardPasteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClipboardRegisterServer).Paste(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ClipboardRegister/Paste",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClipboardRegisterServer).Paste(ctx, req.(*ClipboardPasteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ClipboardRegister_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ClipboardRegister",
	HandlerType: (*ClipboardRegisterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Copy",
			Handler:    _ClipboardRegister_Copy_Handler,
		},
		{
			MethodName: "Paste",
			Handler:    _ClipboardRegister_Paste_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "clipboard.proto",
}
