// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.16.0
// source: editor.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type EditorEvent_Type int32

const (
	EditorEvent_TypeOpen    EditorEvent_Type = 0
	EditorEvent_TypeClose   EditorEvent_Type = 1
	EditorEvent_TypeFlush   EditorEvent_Type = 2
	EditorEvent_TypeInsert  EditorEvent_Type = 3
	EditorEvent_TypeDelete  EditorEvent_Type = 4
	EditorEvent_TypeCommand EditorEvent_Type = 5
	EditorEvent_TypeScroll  EditorEvent_Type = 6
	EditorEvent_TypeFocus   EditorEvent_Type = 7
	EditorEvent_TypeCursor  EditorEvent_Type = 8
)

// Enum value maps for EditorEvent_Type.
var (
	EditorEvent_Type_name = map[int32]string{
		0: "TypeOpen",
		1: "TypeClose",
		2: "TypeFlush",
		3: "TypeInsert",
		4: "TypeDelete",
		5: "TypeCommand",
		6: "TypeScroll",
		7: "TypeFocus",
		8: "TypeCursor",
	}
	EditorEvent_Type_value = map[string]int32{
		"TypeOpen":    0,
		"TypeClose":   1,
		"TypeFlush":   2,
		"TypeInsert":  3,
		"TypeDelete":  4,
		"TypeCommand": 5,
		"TypeScroll":  6,
		"TypeFocus":   7,
		"TypeCursor":  8,
	}
)

func (x EditorEvent_Type) Enum() *EditorEvent_Type {
	p := new(EditorEvent_Type)
	*p = x
	return p
}

func (x EditorEvent_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EditorEvent_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_editor_proto_enumTypes[0].Descriptor()
}

func (EditorEvent_Type) Type() protoreflect.EnumType {
	return &file_editor_proto_enumTypes[0]
}

func (x EditorEvent_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EditorEvent_Type.Descriptor instead.
func (EditorEvent_Type) EnumDescriptor() ([]byte, []int) {
	return file_editor_proto_rawDescGZIP(), []int{2, 0}
}

type EditRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResourceName string     `protobuf:"bytes,1,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	Buffer       []*CellRow `protobuf:"bytes,2,rep,name=buffer,proto3" json:"buffer,omitempty"`
}

func (x *EditRequest) Reset() {
	*x = EditRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_editor_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditRequest) ProtoMessage() {}

func (x *EditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_editor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditRequest.ProtoReflect.Descriptor instead.
func (*EditRequest) Descriptor() ([]byte, []int) {
	return file_editor_proto_rawDescGZIP(), []int{0}
}

func (x *EditRequest) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

func (x *EditRequest) GetBuffer() []*CellRow {
	if x != nil {
		return x.Buffer
	}
	return nil
}

type EditResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HandlerId uint32 `protobuf:"varint,1,opt,name=handler_id,json=handlerId,proto3" json:"handler_id,omitempty"`
}

func (x *EditResponse) Reset() {
	*x = EditResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_editor_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditResponse) ProtoMessage() {}

func (x *EditResponse) ProtoReflect() protoreflect.Message {
	mi := &file_editor_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditResponse.ProtoReflect.Descriptor instead.
func (*EditResponse) Descriptor() ([]byte, []int) {
	return file_editor_proto_rawDescGZIP(), []int{1}
}

func (x *EditResponse) GetHandlerId() uint32 {
	if x != nil {
		return x.HandlerId
	}
	return 0
}

type EditorEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type         EditorEvent_Type `protobuf:"varint,1,opt,name=type,proto3,enum=proto.EditorEvent_Type" json:"type,omitempty"`
	ResourceName string           `protobuf:"bytes,2,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	ResourceId   uint32           `protobuf:"varint,3,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	Start        *Coordinates     `protobuf:"bytes,4,opt,name=start,proto3" json:"start,omitempty"`
	End          *Coordinates     `protobuf:"bytes,5,opt,name=end,proto3" json:"end,omitempty"`
	From         *Coordinates     `protobuf:"bytes,6,opt,name=from,proto3" json:"from,omitempty"`
	To           *Coordinates     `protobuf:"bytes,7,opt,name=to,proto3" json:"to,omitempty"`
	Content      string           `protobuf:"bytes,8,opt,name=content,proto3" json:"content,omitempty"`
	CmdArgs      []string         `protobuf:"bytes,9,rep,name=cmdArgs,proto3" json:"cmdArgs,omitempty"`
}

func (x *EditorEvent) Reset() {
	*x = EditorEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_editor_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditorEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditorEvent) ProtoMessage() {}

func (x *EditorEvent) ProtoReflect() protoreflect.Message {
	mi := &file_editor_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditorEvent.ProtoReflect.Descriptor instead.
func (*EditorEvent) Descriptor() ([]byte, []int) {
	return file_editor_proto_rawDescGZIP(), []int{2}
}

func (x *EditorEvent) GetType() EditorEvent_Type {
	if x != nil {
		return x.Type
	}
	return EditorEvent_TypeOpen
}

func (x *EditorEvent) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

func (x *EditorEvent) GetResourceId() uint32 {
	if x != nil {
		return x.ResourceId
	}
	return 0
}

func (x *EditorEvent) GetStart() *Coordinates {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *EditorEvent) GetEnd() *Coordinates {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *EditorEvent) GetFrom() *Coordinates {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *EditorEvent) GetTo() *Coordinates {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *EditorEvent) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *EditorEvent) GetCmdArgs() []string {
	if x != nil {
		return x.CmdArgs
	}
	return nil
}

type EditorSubscribeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type      EditorEvent_Type `protobuf:"varint,1,opt,name=type,proto3,enum=proto.EditorEvent_Type" json:"type,omitempty"`
	HandlerId uint32           `protobuf:"varint,2,opt,name=handler_id,json=handlerId,proto3" json:"handler_id,omitempty"`
}

func (x *EditorSubscribeRequest) Reset() {
	*x = EditorSubscribeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_editor_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditorSubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditorSubscribeRequest) ProtoMessage() {}

func (x *EditorSubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_editor_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditorSubscribeRequest.ProtoReflect.Descriptor instead.
func (*EditorSubscribeRequest) Descriptor() ([]byte, []int) {
	return file_editor_proto_rawDescGZIP(), []int{3}
}

func (x *EditorSubscribeRequest) GetType() EditorEvent_Type {
	if x != nil {
		return x.Type
	}
	return EditorEvent_TypeOpen
}

func (x *EditorSubscribeRequest) GetHandlerId() uint32 {
	if x != nil {
		return x.HandlerId
	}
	return 0
}

type EditorSubscribeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EditorSubscribeResponse) Reset() {
	*x = EditorSubscribeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_editor_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditorSubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditorSubscribeResponse) ProtoMessage() {}

func (x *EditorSubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_editor_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditorSubscribeResponse.ProtoReflect.Descriptor instead.
func (*EditorSubscribeResponse) Descriptor() ([]byte, []int) {
	return file_editor_proto_rawDescGZIP(), []int{4}
}

type SetLocationListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HandlerId uint32                             `protobuf:"varint,1,opt,name=handler_id,json=handlerId,proto3" json:"handler_id,omitempty"`
	ListId    string                             `protobuf:"bytes,2,opt,name=list_id,json=listId,proto3" json:"list_id,omitempty"`
	Locations []*SetLocationListRequest_Location `protobuf:"bytes,3,rep,name=locations,proto3" json:"locations,omitempty"`
}

func (x *SetLocationListRequest) Reset() {
	*x = SetLocationListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_editor_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetLocationListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLocationListRequest) ProtoMessage() {}

func (x *SetLocationListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_editor_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLocationListRequest.ProtoReflect.Descriptor instead.
func (*SetLocationListRequest) Descriptor() ([]byte, []int) {
	return file_editor_proto_rawDescGZIP(), []int{5}
}

func (x *SetLocationListRequest) GetHandlerId() uint32 {
	if x != nil {
		return x.HandlerId
	}
	return 0
}

func (x *SetLocationListRequest) GetListId() string {
	if x != nil {
		return x.ListId
	}
	return ""
}

func (x *SetLocationListRequest) GetLocations() []*SetLocationListRequest_Location {
	if x != nil {
		return x.Locations
	}
	return nil
}

type SetLocationListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetLocationListResponse) Reset() {
	*x = SetLocationListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_editor_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetLocationListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLocationListResponse) ProtoMessage() {}

func (x *SetLocationListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_editor_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLocationListResponse.ProtoReflect.Descriptor instead.
func (*SetLocationListResponse) Descriptor() ([]byte, []int) {
	return file_editor_proto_rawDescGZIP(), []int{6}
}

type InsertRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HandlerId uint32       `protobuf:"varint,1,opt,name=handler_id,json=handlerId,proto3" json:"handler_id,omitempty"`
	At        *Coordinates `protobuf:"bytes,2,opt,name=at,proto3" json:"at,omitempty"`
	Str       string       `protobuf:"bytes,3,opt,name=str,proto3" json:"str,omitempty"`
}

func (x *InsertRequest) Reset() {
	*x = InsertRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_editor_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertRequest) ProtoMessage() {}

func (x *InsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_editor_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertRequest.ProtoReflect.Descriptor instead.
func (*InsertRequest) Descriptor() ([]byte, []int) {
	return file_editor_proto_rawDescGZIP(), []int{7}
}

func (x *InsertRequest) GetHandlerId() uint32 {
	if x != nil {
		return x.HandlerId
	}
	return 0
}

func (x *InsertRequest) GetAt() *Coordinates {
	if x != nil {
		return x.At
	}
	return nil
}

func (x *InsertRequest) GetStr() string {
	if x != nil {
		return x.Str
	}
	return ""
}

type InsertResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From *Coordinates `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To   *Coordinates `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
}

func (x *InsertResponse) Reset() {
	*x = InsertResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_editor_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertResponse) ProtoMessage() {}

func (x *InsertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_editor_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertResponse.ProtoReflect.Descriptor instead.
func (*InsertResponse) Descriptor() ([]byte, []int) {
	return file_editor_proto_rawDescGZIP(), []int{8}
}

func (x *InsertResponse) GetFrom() *Coordinates {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *InsertResponse) GetTo() *Coordinates {
	if x != nil {
		return x.To
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HandlerId uint32       `protobuf:"varint,1,opt,name=handler_id,json=handlerId,proto3" json:"handler_id,omitempty"`
	From      *Coordinates `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To        *Coordinates `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_editor_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_editor_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_editor_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteRequest) GetHandlerId() uint32 {
	if x != nil {
		return x.HandlerId
	}
	return 0
}

func (x *DeleteRequest) GetFrom() *Coordinates {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *DeleteRequest) GetTo() *Coordinates {
	if x != nil {
		return x.To
	}
	return nil
}

type DeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Start *Coordinates `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End   *Coordinates `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	Str   string       `protobuf:"bytes,3,opt,name=str,proto3" json:"str,omitempty"`
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_editor_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_editor_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_editor_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteResponse) GetStart() *Coordinates {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *DeleteResponse) GetEnd() *Coordinates {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *DeleteResponse) GetStr() string {
	if x != nil {
		return x.Str
	}
	return ""
}

type RawCellsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HandlerId uint32 `protobuf:"varint,1,opt,name=handler_id,json=handlerId,proto3" json:"handler_id,omitempty"`
}

func (x *RawCellsRequest) Reset() {
	*x = RawCellsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_editor_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RawCellsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawCellsRequest) ProtoMessage() {}

func (x *RawCellsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_editor_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawCellsRequest.ProtoReflect.Descriptor instead.
func (*RawCellsRequest) Descriptor() ([]byte, []int) {
	return file_editor_proto_rawDescGZIP(), []int{11}
}

func (x *RawCellsRequest) GetHandlerId() uint32 {
	if x != nil {
		return x.HandlerId
	}
	return 0
}

type RawCellsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rows []*CellRow `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
}

func (x *RawCellsResponse) Reset() {
	*x = RawCellsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_editor_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RawCellsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawCellsResponse) ProtoMessage() {}

func (x *RawCellsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_editor_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawCellsResponse.ProtoReflect.Descriptor instead.
func (*RawCellsResponse) Descriptor() ([]byte, []int) {
	return file_editor_proto_rawDescGZIP(), []int{12}
}

func (x *RawCellsResponse) GetRows() []*CellRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

type MoveToLocationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HandlerId uint32 `protobuf:"varint,1,opt,name=handler_id,json=handlerId,proto3" json:"handler_id,omitempty"`
	ListId    string `protobuf:"bytes,2,opt,name=list_id,json=listId,proto3" json:"list_id,omitempty"`
}

func (x *MoveToLocationRequest) Reset() {
	*x = MoveToLocationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_editor_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveToLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveToLocationRequest) ProtoMessage() {}

func (x *MoveToLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_editor_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveToLocationRequest.ProtoReflect.Descriptor instead.
func (*MoveToLocationRequest) Descriptor() ([]byte, []int) {
	return file_editor_proto_rawDescGZIP(), []int{13}
}

func (x *MoveToLocationRequest) GetHandlerId() uint32 {
	if x != nil {
		return x.HandlerId
	}
	return 0
}

func (x *MoveToLocationRequest) GetListId() string {
	if x != nil {
		return x.ListId
	}
	return ""
}

type MoveToLocationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MoveToLocationResponse) Reset() {
	*x = MoveToLocationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_editor_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveToLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveToLocationResponse) ProtoMessage() {}

func (x *MoveToLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_editor_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveToLocationResponse.ProtoReflect.Descriptor instead.
func (*MoveToLocationResponse) Descriptor() ([]byte, []int) {
	return file_editor_proto_rawDescGZIP(), []int{14}
}

type RegisterCommandRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Command   string `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	HandlerId uint32 `protobuf:"varint,2,opt,name=handler_id,json=handlerId,proto3" json:"handler_id,omitempty"`
}

func (x *RegisterCommandRequest) Reset() {
	*x = RegisterCommandRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_editor_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterCommandRequest) ProtoMessage() {}

func (x *RegisterCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_editor_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterCommandRequest.ProtoReflect.Descriptor instead.
func (*RegisterCommandRequest) Descriptor() ([]byte, []int) {
	return file_editor_proto_rawDescGZIP(), []int{15}
}

func (x *RegisterCommandRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *RegisterCommandRequest) GetHandlerId() uint32 {
	if x != nil {
		return x.HandlerId
	}
	return 0
}

type RegisterCommandResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RegisterCommandResponse) Reset() {
	*x = RegisterCommandResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_editor_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterCommandResponse) ProtoMessage() {}

func (x *RegisterCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_editor_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterCommandResponse.ProtoReflect.Descriptor instead.
func (*RegisterCommandResponse) Descriptor() ([]byte, []int) {
	return file_editor_proto_rawDescGZIP(), []int{16}
}

type SetCursorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pos       *Coordinates `protobuf:"bytes,1,opt,name=pos,proto3" json:"pos,omitempty"`
	HandlerId uint32       `protobuf:"varint,2,opt,name=handler_id,json=handlerId,proto3" json:"handler_id,omitempty"`
}

func (x *SetCursorRequest) Reset() {
	*x = SetCursorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_editor_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetCursorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCursorRequest) ProtoMessage() {}

func (x *SetCursorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_editor_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCursorRequest.ProtoReflect.Descriptor instead.
func (*SetCursorRequest) Descriptor() ([]byte, []int) {
	return file_editor_proto_rawDescGZIP(), []int{17}
}

func (x *SetCursorRequest) GetPos() *Coordinates {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *SetCursorRequest) GetHandlerId() uint32 {
	if x != nil {
		return x.HandlerId
	}
	return 0
}

type SetCursorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetCursorResponse) Reset() {
	*x = SetCursorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_editor_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetCursorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCursorResponse) ProtoMessage() {}

func (x *SetCursorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_editor_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCursorResponse.ProtoReflect.Descriptor instead.
func (*SetCursorResponse) Descriptor() ([]byte, []int) {
	return file_editor_proto_rawDescGZIP(), []int{18}
}

type CursorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HandlerId uint32 `protobuf:"varint,1,opt,name=handler_id,json=handlerId,proto3" json:"handler_id,omitempty"`
}

func (x *CursorRequest) Reset() {
	*x = CursorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_editor_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CursorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CursorRequest) ProtoMessage() {}

func (x *CursorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_editor_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CursorRequest.ProtoReflect.Descriptor instead.
func (*CursorRequest) Descriptor() ([]byte, []int) {
	return file_editor_proto_rawDescGZIP(), []int{19}
}

func (x *CursorRequest) GetHandlerId() uint32 {
	if x != nil {
		return x.HandlerId
	}
	return 0
}

type CursorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pos *Coordinates `protobuf:"bytes,1,opt,name=pos,proto3" json:"pos,omitempty"`
}

func (x *CursorResponse) Reset() {
	*x = CursorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_editor_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CursorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CursorResponse) ProtoMessage() {}

func (x *CursorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_editor_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CursorResponse.ProtoReflect.Descriptor instead.
func (*CursorResponse) Descriptor() ([]byte, []int) {
	return file_editor_proto_rawDescGZIP(), []int{20}
}

func (x *CursorResponse) GetPos() *Coordinates {
	if x != nil {
		return x.Pos
	}
	return nil
}

type EditorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResourceName string `protobuf:"bytes,1,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
}

func (x *EditorRequest) Reset() {
	*x = EditorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_editor_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditorRequest) ProtoMessage() {}

func (x *EditorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_editor_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditorRequest.ProtoReflect.Descriptor instead.
func (*EditorRequest) Descriptor() ([]byte, []int) {
	return file_editor_proto_rawDescGZIP(), []int{21}
}

func (x *EditorRequest) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

type EditorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HandlerId uint32 `protobuf:"varint,1,opt,name=handler_id,json=handlerId,proto3" json:"handler_id,omitempty"`
}

func (x *EditorResponse) Reset() {
	*x = EditorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_editor_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditorResponse) ProtoMessage() {}

func (x *EditorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_editor_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditorResponse.ProtoReflect.Descriptor instead.
func (*EditorResponse) Descriptor() ([]byte, []int) {
	return file_editor_proto_rawDescGZIP(), []int{22}
}

func (x *EditorResponse) GetHandlerId() uint32 {
	if x != nil {
		return x.HandlerId
	}
	return 0
}

type SetLocationListRequest_Location struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From *Coordinates `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To   *Coordinates `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Attr *Attributes  `protobuf:"bytes,3,opt,name=attr,proto3" json:"attr,omitempty"`
	Msg  string       `protobuf:"bytes,4,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *SetLocationListRequest_Location) Reset() {
	*x = SetLocationListRequest_Location{}
	if protoimpl.UnsafeEnabled {
		mi := &file_editor_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetLocationListRequest_Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLocationListRequest_Location) ProtoMessage() {}

func (x *SetLocationListRequest_Location) ProtoReflect() protoreflect.Message {
	mi := &file_editor_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLocationListRequest_Location.ProtoReflect.Descriptor instead.
func (*SetLocationListRequest_Location) Descriptor() ([]byte, []int) {
	return file_editor_proto_rawDescGZIP(), []int{5, 0}
}

func (x *SetLocationListRequest_Location) GetFrom() *Coordinates {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *SetLocationListRequest_Location) GetTo() *Coordinates {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *SetLocationListRequest_Location) GetAttr() *Attributes {
	if x != nil {
		return x.Attr
	}
	return nil
}

func (x *SetLocationListRequest_Location) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_editor_proto protoreflect.FileDescriptor

var file_editor_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x74, 0x65, 0x72, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x09, 0x74, 0x75, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5a, 0x0a, 0x0b,
	0x45, 0x64, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x72,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x26, 0x0a, 0x06, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x65, 0x6c, 0x6c, 0x52, 0x6f, 0x77,
	0x52, 0x06, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x22, 0x2d, 0x0a, 0x0c, 0x45, 0x64, 0x69, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x68, 0x61, 0x6e, 0x64,
	0x6c, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x68, 0x61,
	0x6e, 0x64, 0x6c, 0x65, 0x72, 0x49, 0x64, 0x22, 0xe5, 0x03, 0x0a, 0x0b, 0x45, 0x64, 0x69, 0x74,
	0x6f, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x2b, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x64,
	0x69, 0x74, 0x6f, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a,
	0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x05, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x52, 0x05, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x12, 0x24, 0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69,
	0x6e, 0x61, 0x74, 0x65, 0x73, 0x52, 0x03, 0x65, 0x6e, 0x64, 0x12, 0x26, 0x0a, 0x04, 0x66, 0x72,
	0x6f, 0x6d, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x52, 0x04, 0x66, 0x72,
	0x6f, 0x6d, 0x12, 0x22, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74,
	0x65, 0x73, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x6d, 0x64, 0x41, 0x72, 0x67, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x07, 0x63, 0x6d, 0x64, 0x41, 0x72, 0x67, 0x73, 0x22, 0x92, 0x01, 0x0a, 0x04, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x0c, 0x0a, 0x08, 0x54, 0x79, 0x70, 0x65, 0x4f, 0x70, 0x65, 0x6e, 0x10,
	0x00, 0x12, 0x0d, 0x0a, 0x09, 0x54, 0x79, 0x70, 0x65, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x10, 0x01,
	0x12, 0x0d, 0x0a, 0x09, 0x54, 0x79, 0x70, 0x65, 0x46, 0x6c, 0x75, 0x73, 0x68, 0x10, 0x02, 0x12,
	0x0e, 0x0a, 0x0a, 0x54, 0x79, 0x70, 0x65, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x10, 0x03, 0x12,
	0x0e, 0x0a, 0x0a, 0x54, 0x79, 0x70, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x10, 0x04, 0x12,
	0x0f, 0x0a, 0x0b, 0x54, 0x79, 0x70, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x10, 0x05,
	0x12, 0x0e, 0x0a, 0x0a, 0x54, 0x79, 0x70, 0x65, 0x53, 0x63, 0x72, 0x6f, 0x6c, 0x6c, 0x10, 0x06,
	0x12, 0x0d, 0x0a, 0x09, 0x54, 0x79, 0x70, 0x65, 0x46, 0x6f, 0x63, 0x75, 0x73, 0x10, 0x07, 0x12,
	0x0e, 0x0a, 0x0a, 0x54, 0x79, 0x70, 0x65, 0x43, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x10, 0x08, 0x22,
	0x64, 0x0a, 0x16, 0x45, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69,
	0x62, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x45, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x68, 0x61, 0x6e, 0x64,
	0x6c, 0x65, 0x72, 0x49, 0x64, 0x22, 0x19, 0x0a, 0x17, 0x45, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x53,
	0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0xa8, 0x02, 0x0a, 0x16, 0x53, 0x65, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x68,
	0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x09, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x6c, 0x69,
	0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x69, 0x73,
	0x74, 0x49, 0x64, 0x12, 0x44, 0x0a, 0x09, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53,
	0x65, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09,
	0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x8f, 0x01, 0x0a, 0x08, 0x4c, 0x6f,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x26, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x6f,
	0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x22,
	0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x52, 0x02,
	0x74, 0x6f, 0x12, 0x25, 0x0a, 0x04, 0x61, 0x74, 0x74, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75,
	0x74, 0x65, 0x73, 0x52, 0x04, 0x61, 0x74, 0x74, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x19, 0x0a, 0x17, 0x53,
	0x65, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x64, 0x0a, 0x0d, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x68, 0x61, 0x6e, 0x64, 0x6c,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x68, 0x61, 0x6e,
	0x64, 0x6c, 0x65, 0x72, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x02, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x6f, 0x72, 0x64,
	0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x52, 0x02, 0x61, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x74,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x74, 0x72, 0x22, 0x5c, 0x0a, 0x0e,
	0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26,
	0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73,
	0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x22, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x6f, 0x72, 0x64,
	0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x52, 0x02, 0x74, 0x6f, 0x22, 0x7a, 0x0a, 0x0d, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x68,
	0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x09, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x04, 0x66, 0x72,
	0x6f, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x52, 0x04, 0x66, 0x72,
	0x6f, 0x6d, 0x12, 0x22, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74,
	0x65, 0x73, 0x52, 0x02, 0x74, 0x6f, 0x22, 0x72, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x52, 0x05, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x12, 0x24, 0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61,
	0x74, 0x65, 0x73, 0x52, 0x03, 0x65, 0x6e, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x74, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x74, 0x72, 0x22, 0x30, 0x0a, 0x0f, 0x52, 0x61,
	0x77, 0x43, 0x65, 0x6c, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a,
	0x0a, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x09, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x49, 0x64, 0x22, 0x36, 0x0a, 0x10,
	0x52, 0x61, 0x77, 0x43, 0x65, 0x6c, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x22, 0x0a, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x65, 0x6c, 0x6c, 0x52, 0x6f, 0x77, 0x52, 0x04,
	0x72, 0x6f, 0x77, 0x73, 0x22, 0x4f, 0x0a, 0x15, 0x4d, 0x6f, 0x76, 0x65, 0x54, 0x6f, 0x4c, 0x6f,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a,
	0x0a, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x09, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07,
	0x6c, 0x69, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6c,
	0x69, 0x73, 0x74, 0x49, 0x64, 0x22, 0x18, 0x0a, 0x16, 0x4d, 0x6f, 0x76, 0x65, 0x54, 0x6f, 0x4c,
	0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x51, 0x0a, 0x16, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72,
	0x49, 0x64, 0x22, 0x19, 0x0a, 0x17, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x57, 0x0a,
	0x10, 0x53, 0x65, 0x74, 0x43, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x24, 0x0a, 0x03, 0x70, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74,
	0x65, 0x73, 0x52, 0x03, 0x70, 0x6f, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x68, 0x61, 0x6e, 0x64, 0x6c,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x68, 0x61, 0x6e,
	0x64, 0x6c, 0x65, 0x72, 0x49, 0x64, 0x22, 0x13, 0x0a, 0x11, 0x53, 0x65, 0x74, 0x43, 0x75, 0x72,
	0x73, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2e, 0x0a, 0x0d, 0x43,
	0x75, 0x72, 0x73, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a,
	0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x09, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x49, 0x64, 0x22, 0x36, 0x0a, 0x0e, 0x43,
	0x75, 0x72, 0x73, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a,
	0x03, 0x70, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x52, 0x03,
	0x70, 0x6f, 0x73, 0x22, 0x34, 0x0a, 0x0d, 0x45, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x2f, 0x0a, 0x0e, 0x45, 0x64, 0x69,
	0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x68,
	0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x09, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x49, 0x64, 0x32, 0xa1, 0x06, 0x0a, 0x06, 0x45,
	0x64, 0x69, 0x74, 0x6f, 0x72, 0x12, 0x2f, 0x0a, 0x04, 0x45, 0x64, 0x69, 0x74, 0x12, 0x12, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x64, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x64, 0x69, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a, 0x0a, 0x09, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72,
	0x69, 0x62, 0x65, 0x12, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x64, 0x69, 0x74,
	0x6f, 0x72, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x64, 0x69, 0x74, 0x6f,
	0x72, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x49, 0x0a, 0x08, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x1d,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a,
	0x09, 0x53, 0x65, 0x74, 0x43, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x12, 0x17, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x53, 0x65, 0x74, 0x43, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x74, 0x43,
	0x75, 0x72, 0x73, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a,
	0x06, 0x43, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x12, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x43, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x06, 0x45, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x12, 0x14,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x64, 0x69,
	0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x50, 0x0a, 0x0f, 0x53,
	0x65, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1d,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x51, 0x0a,
	0x12, 0x4d, 0x6f, 0x76, 0x65, 0x54, 0x6f, 0x4e, 0x65, 0x78, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x6f, 0x76, 0x65,
	0x54, 0x6f, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x54, 0x6f,
	0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x51, 0x0a, 0x12, 0x4d, 0x6f, 0x76, 0x65, 0x54, 0x6f, 0x50, 0x72, 0x65, 0x76, 0x4c, 0x6f,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d,
	0x6f, 0x76, 0x65, 0x54, 0x6f, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x6f, 0x76,
	0x65, 0x54, 0x6f, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x06, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x12, 0x14, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6e, 0x73, 0x65,
	0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x06, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x12, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x3b, 0x0a, 0x08, 0x52, 0x61, 0x77, 0x43, 0x65, 0x6c, 0x6c, 0x73, 0x12, 0x16, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x61, 0x77, 0x43, 0x65, 0x6c, 0x6c, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x61,
	0x77, 0x43, 0x65, 0x6c, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_editor_proto_rawDescOnce sync.Once
	file_editor_proto_rawDescData = file_editor_proto_rawDesc
)

func file_editor_proto_rawDescGZIP() []byte {
	file_editor_proto_rawDescOnce.Do(func() {
		file_editor_proto_rawDescData = protoimpl.X.CompressGZIP(file_editor_proto_rawDescData)
	})
	return file_editor_proto_rawDescData
}

var file_editor_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_editor_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_editor_proto_goTypes = []interface{}{
	(EditorEvent_Type)(0),                   // 0: proto.EditorEvent.Type
	(*EditRequest)(nil),                     // 1: proto.EditRequest
	(*EditResponse)(nil),                    // 2: proto.EditResponse
	(*EditorEvent)(nil),                     // 3: proto.EditorEvent
	(*EditorSubscribeRequest)(nil),          // 4: proto.EditorSubscribeRequest
	(*EditorSubscribeResponse)(nil),         // 5: proto.EditorSubscribeResponse
	(*SetLocationListRequest)(nil),          // 6: proto.SetLocationListRequest
	(*SetLocationListResponse)(nil),         // 7: proto.SetLocationListResponse
	(*InsertRequest)(nil),                   // 8: proto.InsertRequest
	(*InsertResponse)(nil),                  // 9: proto.InsertResponse
	(*DeleteRequest)(nil),                   // 10: proto.DeleteRequest
	(*DeleteResponse)(nil),                  // 11: proto.DeleteResponse
	(*RawCellsRequest)(nil),                 // 12: proto.RawCellsRequest
	(*RawCellsResponse)(nil),                // 13: proto.RawCellsResponse
	(*MoveToLocationRequest)(nil),           // 14: proto.MoveToLocationRequest
	(*MoveToLocationResponse)(nil),          // 15: proto.MoveToLocationResponse
	(*RegisterCommandRequest)(nil),          // 16: proto.RegisterCommandRequest
	(*RegisterCommandResponse)(nil),         // 17: proto.RegisterCommandResponse
	(*SetCursorRequest)(nil),                // 18: proto.SetCursorRequest
	(*SetCursorResponse)(nil),               // 19: proto.SetCursorResponse
	(*CursorRequest)(nil),                   // 20: proto.CursorRequest
	(*CursorResponse)(nil),                  // 21: proto.CursorResponse
	(*EditorRequest)(nil),                   // 22: proto.EditorRequest
	(*EditorResponse)(nil),                  // 23: proto.EditorResponse
	(*SetLocationListRequest_Location)(nil), // 24: proto.SetLocationListRequest.Location
	(*CellRow)(nil),                         // 25: proto.CellRow
	(*Coordinates)(nil),                     // 26: proto.Coordinates
	(*Attributes)(nil),                      // 27: proto.Attributes
}
var file_editor_proto_depIdxs = []int32{
	25, // 0: proto.EditRequest.buffer:type_name -> proto.CellRow
	0,  // 1: proto.EditorEvent.type:type_name -> proto.EditorEvent.Type
	26, // 2: proto.EditorEvent.start:type_name -> proto.Coordinates
	26, // 3: proto.EditorEvent.end:type_name -> proto.Coordinates
	26, // 4: proto.EditorEvent.from:type_name -> proto.Coordinates
	26, // 5: proto.EditorEvent.to:type_name -> proto.Coordinates
	0,  // 6: proto.EditorSubscribeRequest.type:type_name -> proto.EditorEvent.Type
	24, // 7: proto.SetLocationListRequest.locations:type_name -> proto.SetLocationListRequest.Location
	26, // 8: proto.InsertRequest.at:type_name -> proto.Coordinates
	26, // 9: proto.InsertResponse.from:type_name -> proto.Coordinates
	26, // 10: proto.InsertResponse.to:type_name -> proto.Coordinates
	26, // 11: proto.DeleteRequest.from:type_name -> proto.Coordinates
	26, // 12: proto.DeleteRequest.to:type_name -> proto.Coordinates
	26, // 13: proto.DeleteResponse.start:type_name -> proto.Coordinates
	26, // 14: proto.DeleteResponse.end:type_name -> proto.Coordinates
	25, // 15: proto.RawCellsResponse.rows:type_name -> proto.CellRow
	26, // 16: proto.SetCursorRequest.pos:type_name -> proto.Coordinates
	26, // 17: proto.CursorResponse.pos:type_name -> proto.Coordinates
	26, // 18: proto.SetLocationListRequest.Location.from:type_name -> proto.Coordinates
	26, // 19: proto.SetLocationListRequest.Location.to:type_name -> proto.Coordinates
	27, // 20: proto.SetLocationListRequest.Location.attr:type_name -> proto.Attributes
	1,  // 21: proto.Editor.Edit:input_type -> proto.EditRequest
	4,  // 22: proto.Editor.Subscribe:input_type -> proto.EditorSubscribeRequest
	16, // 23: proto.Editor.Register:input_type -> proto.RegisterCommandRequest
	18, // 24: proto.Editor.SetCursor:input_type -> proto.SetCursorRequest
	20, // 25: proto.Editor.Cursor:input_type -> proto.CursorRequest
	22, // 26: proto.Editor.Editor:input_type -> proto.EditorRequest
	6,  // 27: proto.Editor.SetLocationList:input_type -> proto.SetLocationListRequest
	14, // 28: proto.Editor.MoveToNextLocation:input_type -> proto.MoveToLocationRequest
	14, // 29: proto.Editor.MoveToPrevLocation:input_type -> proto.MoveToLocationRequest
	8,  // 30: proto.Editor.Insert:input_type -> proto.InsertRequest
	10, // 31: proto.Editor.Delete:input_type -> proto.DeleteRequest
	12, // 32: proto.Editor.RawCells:input_type -> proto.RawCellsRequest
	2,  // 33: proto.Editor.Edit:output_type -> proto.EditResponse
	5,  // 34: proto.Editor.Subscribe:output_type -> proto.EditorSubscribeResponse
	17, // 35: proto.Editor.Register:output_type -> proto.RegisterCommandResponse
	19, // 36: proto.Editor.SetCursor:output_type -> proto.SetCursorResponse
	21, // 37: proto.Editor.Cursor:output_type -> proto.CursorResponse
	23, // 38: proto.Editor.Editor:output_type -> proto.EditorResponse
	7,  // 39: proto.Editor.SetLocationList:output_type -> proto.SetLocationListResponse
	15, // 40: proto.Editor.MoveToNextLocation:output_type -> proto.MoveToLocationResponse
	15, // 41: proto.Editor.MoveToPrevLocation:output_type -> proto.MoveToLocationResponse
	9,  // 42: proto.Editor.Insert:output_type -> proto.InsertResponse
	11, // 43: proto.Editor.Delete:output_type -> proto.DeleteResponse
	13, // 44: proto.Editor.RawCells:output_type -> proto.RawCellsResponse
	33, // [33:45] is the sub-list for method output_type
	21, // [21:33] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_editor_proto_init() }
func file_editor_proto_init() {
	if File_editor_proto != nil {
		return
	}
	file_term_proto_init()
	file_tui_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_editor_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_editor_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_editor_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditorEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_editor_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditorSubscribeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_editor_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditorSubscribeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_editor_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetLocationListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_editor_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetLocationListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_editor_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_editor_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_editor_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_editor_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_editor_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RawCellsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_editor_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RawCellsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_editor_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveToLocationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_editor_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveToLocationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_editor_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterCommandRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_editor_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterCommandResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_editor_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetCursorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_editor_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetCursorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_editor_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CursorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_editor_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CursorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_editor_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_editor_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_editor_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetLocationListRequest_Location); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_editor_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_editor_proto_goTypes,
		DependencyIndexes: file_editor_proto_depIdxs,
		EnumInfos:         file_editor_proto_enumTypes,
		MessageInfos:      file_editor_proto_msgTypes,
	}.Build()
	File_editor_proto = out.File
	file_editor_proto_rawDesc = nil
	file_editor_proto_goTypes = nil
	file_editor_proto_depIdxs = nil
}
