// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: editor_event_handler.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EditorEventHandlerClient is the client API for EditorEventHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EditorEventHandlerClient interface {
	Handle(ctx context.Context, in *EditorEventHandleRequest, opts ...grpc.CallOption) (*EditorEventHandleResponse, error)
}

type editorEventHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewEditorEventHandlerClient(cc grpc.ClientConnInterface) EditorEventHandlerClient {
	return &editorEventHandlerClient{cc}
}

func (c *editorEventHandlerClient) Handle(ctx context.Context, in *EditorEventHandleRequest, opts ...grpc.CallOption) (*EditorEventHandleResponse, error) {
	out := new(EditorEventHandleResponse)
	err := c.cc.Invoke(ctx, "/proto.EditorEventHandler/Handle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EditorEventHandlerServer is the server API for EditorEventHandler service.
// All implementations must embed UnimplementedEditorEventHandlerServer
// for forward compatibility
type EditorEventHandlerServer interface {
	Handle(context.Context, *EditorEventHandleRequest) (*EditorEventHandleResponse, error)
	mustEmbedUnimplementedEditorEventHandlerServer()
}

// UnimplementedEditorEventHandlerServer must be embedded to have forward compatible implementations.
type UnimplementedEditorEventHandlerServer struct {
}

func (UnimplementedEditorEventHandlerServer) Handle(context.Context, *EditorEventHandleRequest) (*EditorEventHandleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Handle not implemented")
}
func (UnimplementedEditorEventHandlerServer) mustEmbedUnimplementedEditorEventHandlerServer() {}

// UnsafeEditorEventHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EditorEventHandlerServer will
// result in compilation errors.
type UnsafeEditorEventHandlerServer interface {
	mustEmbedUnimplementedEditorEventHandlerServer()
}

func RegisterEditorEventHandlerServer(s grpc.ServiceRegistrar, srv EditorEventHandlerServer) {
	s.RegisterService(&EditorEventHandler_ServiceDesc, srv)
}

func _EditorEventHandler_Handle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditorEventHandleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EditorEventHandlerServer).Handle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EditorEventHandler/Handle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EditorEventHandlerServer).Handle(ctx, req.(*EditorEventHandleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EditorEventHandler_ServiceDesc is the grpc.ServiceDesc for EditorEventHandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EditorEventHandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.EditorEventHandler",
	HandlerType: (*EditorEventHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Handle",
			Handler:    _EditorEventHandler_Handle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "editor_event_handler.proto",
}
