// Code generated by protoc-gen-go. DO NOT EDIT.
// source: editor.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EditorEvent_Type int32

const (
	EditorEvent_TypeOpen  EditorEvent_Type = 0
	EditorEvent_TypeClose EditorEvent_Type = 1
	EditorEvent_TypeFlush EditorEvent_Type = 2
)

var EditorEvent_Type_name = map[int32]string{
	0: "TypeOpen",
	1: "TypeClose",
	2: "TypeFlush",
}

var EditorEvent_Type_value = map[string]int32{
	"TypeOpen":  0,
	"TypeClose": 1,
	"TypeFlush": 2,
}

func (x EditorEvent_Type) String() string {
	return proto.EnumName(EditorEvent_Type_name, int32(x))
}

func (EditorEvent_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7d780504008e31fd, []int{2, 0}
}

type EditRequest struct {
	ResourceName         string     `protobuf:"bytes,1,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	Buffer               []*CellRow `protobuf:"bytes,2,rep,name=buffer,proto3" json:"buffer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *EditRequest) Reset()         { *m = EditRequest{} }
func (m *EditRequest) String() string { return proto.CompactTextString(m) }
func (*EditRequest) ProtoMessage()    {}
func (*EditRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d780504008e31fd, []int{0}
}

func (m *EditRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditRequest.Unmarshal(m, b)
}
func (m *EditRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditRequest.Marshal(b, m, deterministic)
}
func (m *EditRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditRequest.Merge(m, src)
}
func (m *EditRequest) XXX_Size() int {
	return xxx_messageInfo_EditRequest.Size(m)
}
func (m *EditRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EditRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EditRequest proto.InternalMessageInfo

func (m *EditRequest) GetResourceName() string {
	if m != nil {
		return m.ResourceName
	}
	return ""
}

func (m *EditRequest) GetBuffer() []*CellRow {
	if m != nil {
		return m.Buffer
	}
	return nil
}

type EditResponse struct {
	HandlerId            uint32   `protobuf:"varint,1,opt,name=handler_id,json=handlerId,proto3" json:"handler_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditResponse) Reset()         { *m = EditResponse{} }
func (m *EditResponse) String() string { return proto.CompactTextString(m) }
func (*EditResponse) ProtoMessage()    {}
func (*EditResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d780504008e31fd, []int{1}
}

func (m *EditResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditResponse.Unmarshal(m, b)
}
func (m *EditResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditResponse.Marshal(b, m, deterministic)
}
func (m *EditResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditResponse.Merge(m, src)
}
func (m *EditResponse) XXX_Size() int {
	return xxx_messageInfo_EditResponse.Size(m)
}
func (m *EditResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EditResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EditResponse proto.InternalMessageInfo

func (m *EditResponse) GetHandlerId() uint32 {
	if m != nil {
		return m.HandlerId
	}
	return 0
}

type EditorEvent struct {
	Type                 EditorEvent_Type `protobuf:"varint,1,opt,name=type,proto3,enum=proto.EditorEvent_Type" json:"type,omitempty"`
	ResourceName         string           `protobuf:"bytes,2,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	ResourceId           uint32           `protobuf:"varint,3,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *EditorEvent) Reset()         { *m = EditorEvent{} }
func (m *EditorEvent) String() string { return proto.CompactTextString(m) }
func (*EditorEvent) ProtoMessage()    {}
func (*EditorEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d780504008e31fd, []int{2}
}

func (m *EditorEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditorEvent.Unmarshal(m, b)
}
func (m *EditorEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditorEvent.Marshal(b, m, deterministic)
}
func (m *EditorEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditorEvent.Merge(m, src)
}
func (m *EditorEvent) XXX_Size() int {
	return xxx_messageInfo_EditorEvent.Size(m)
}
func (m *EditorEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_EditorEvent.DiscardUnknown(m)
}

var xxx_messageInfo_EditorEvent proto.InternalMessageInfo

func (m *EditorEvent) GetType() EditorEvent_Type {
	if m != nil {
		return m.Type
	}
	return EditorEvent_TypeOpen
}

func (m *EditorEvent) GetResourceName() string {
	if m != nil {
		return m.ResourceName
	}
	return ""
}

func (m *EditorEvent) GetResourceId() uint32 {
	if m != nil {
		return m.ResourceId
	}
	return 0
}

type EditorSubscribeRequest struct {
	Type                 EditorEvent_Type `protobuf:"varint,1,opt,name=type,proto3,enum=proto.EditorEvent_Type" json:"type,omitempty"`
	HandlerId            uint32           `protobuf:"varint,2,opt,name=handler_id,json=handlerId,proto3" json:"handler_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *EditorSubscribeRequest) Reset()         { *m = EditorSubscribeRequest{} }
func (m *EditorSubscribeRequest) String() string { return proto.CompactTextString(m) }
func (*EditorSubscribeRequest) ProtoMessage()    {}
func (*EditorSubscribeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d780504008e31fd, []int{3}
}

func (m *EditorSubscribeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditorSubscribeRequest.Unmarshal(m, b)
}
func (m *EditorSubscribeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditorSubscribeRequest.Marshal(b, m, deterministic)
}
func (m *EditorSubscribeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditorSubscribeRequest.Merge(m, src)
}
func (m *EditorSubscribeRequest) XXX_Size() int {
	return xxx_messageInfo_EditorSubscribeRequest.Size(m)
}
func (m *EditorSubscribeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EditorSubscribeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EditorSubscribeRequest proto.InternalMessageInfo

func (m *EditorSubscribeRequest) GetType() EditorEvent_Type {
	if m != nil {
		return m.Type
	}
	return EditorEvent_TypeOpen
}

func (m *EditorSubscribeRequest) GetHandlerId() uint32 {
	if m != nil {
		return m.HandlerId
	}
	return 0
}

type EditorSubscribeResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditorSubscribeResponse) Reset()         { *m = EditorSubscribeResponse{} }
func (m *EditorSubscribeResponse) String() string { return proto.CompactTextString(m) }
func (*EditorSubscribeResponse) ProtoMessage()    {}
func (*EditorSubscribeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d780504008e31fd, []int{4}
}

func (m *EditorSubscribeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditorSubscribeResponse.Unmarshal(m, b)
}
func (m *EditorSubscribeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditorSubscribeResponse.Marshal(b, m, deterministic)
}
func (m *EditorSubscribeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditorSubscribeResponse.Merge(m, src)
}
func (m *EditorSubscribeResponse) XXX_Size() int {
	return xxx_messageInfo_EditorSubscribeResponse.Size(m)
}
func (m *EditorSubscribeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EditorSubscribeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EditorSubscribeResponse proto.InternalMessageInfo

type SetLocationListRequest struct {
	HandlerId            uint32                             `protobuf:"varint,1,opt,name=handler_id,json=handlerId,proto3" json:"handler_id,omitempty"`
	Locations            []*SetLocationListRequest_Location `protobuf:"bytes,2,rep,name=locations,proto3" json:"locations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *SetLocationListRequest) Reset()         { *m = SetLocationListRequest{} }
func (m *SetLocationListRequest) String() string { return proto.CompactTextString(m) }
func (*SetLocationListRequest) ProtoMessage()    {}
func (*SetLocationListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d780504008e31fd, []int{5}
}

func (m *SetLocationListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetLocationListRequest.Unmarshal(m, b)
}
func (m *SetLocationListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetLocationListRequest.Marshal(b, m, deterministic)
}
func (m *SetLocationListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetLocationListRequest.Merge(m, src)
}
func (m *SetLocationListRequest) XXX_Size() int {
	return xxx_messageInfo_SetLocationListRequest.Size(m)
}
func (m *SetLocationListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetLocationListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetLocationListRequest proto.InternalMessageInfo

func (m *SetLocationListRequest) GetHandlerId() uint32 {
	if m != nil {
		return m.HandlerId
	}
	return 0
}

func (m *SetLocationListRequest) GetLocations() []*SetLocationListRequest_Location {
	if m != nil {
		return m.Locations
	}
	return nil
}

type SetLocationListRequest_Location struct {
	From                 *Coordinates `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   *Coordinates `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Attr                 *Attributes  `protobuf:"bytes,3,opt,name=attr,proto3" json:"attr,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SetLocationListRequest_Location) Reset()         { *m = SetLocationListRequest_Location{} }
func (m *SetLocationListRequest_Location) String() string { return proto.CompactTextString(m) }
func (*SetLocationListRequest_Location) ProtoMessage()    {}
func (*SetLocationListRequest_Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d780504008e31fd, []int{5, 0}
}

func (m *SetLocationListRequest_Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetLocationListRequest_Location.Unmarshal(m, b)
}
func (m *SetLocationListRequest_Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetLocationListRequest_Location.Marshal(b, m, deterministic)
}
func (m *SetLocationListRequest_Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetLocationListRequest_Location.Merge(m, src)
}
func (m *SetLocationListRequest_Location) XXX_Size() int {
	return xxx_messageInfo_SetLocationListRequest_Location.Size(m)
}
func (m *SetLocationListRequest_Location) XXX_DiscardUnknown() {
	xxx_messageInfo_SetLocationListRequest_Location.DiscardUnknown(m)
}

var xxx_messageInfo_SetLocationListRequest_Location proto.InternalMessageInfo

func (m *SetLocationListRequest_Location) GetFrom() *Coordinates {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *SetLocationListRequest_Location) GetTo() *Coordinates {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *SetLocationListRequest_Location) GetAttr() *Attributes {
	if m != nil {
		return m.Attr
	}
	return nil
}

type SetLocationListResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetLocationListResponse) Reset()         { *m = SetLocationListResponse{} }
func (m *SetLocationListResponse) String() string { return proto.CompactTextString(m) }
func (*SetLocationListResponse) ProtoMessage()    {}
func (*SetLocationListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d780504008e31fd, []int{6}
}

func (m *SetLocationListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetLocationListResponse.Unmarshal(m, b)
}
func (m *SetLocationListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetLocationListResponse.Marshal(b, m, deterministic)
}
func (m *SetLocationListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetLocationListResponse.Merge(m, src)
}
func (m *SetLocationListResponse) XXX_Size() int {
	return xxx_messageInfo_SetLocationListResponse.Size(m)
}
func (m *SetLocationListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetLocationListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetLocationListResponse proto.InternalMessageInfo

type InsertRequest struct {
	HandlerId            uint32       `protobuf:"varint,1,opt,name=handler_id,json=handlerId,proto3" json:"handler_id,omitempty"`
	At                   *Coordinates `protobuf:"bytes,2,opt,name=at,proto3" json:"at,omitempty"`
	Str                  string       `protobuf:"bytes,3,opt,name=str,proto3" json:"str,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *InsertRequest) Reset()         { *m = InsertRequest{} }
func (m *InsertRequest) String() string { return proto.CompactTextString(m) }
func (*InsertRequest) ProtoMessage()    {}
func (*InsertRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d780504008e31fd, []int{7}
}

func (m *InsertRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertRequest.Unmarshal(m, b)
}
func (m *InsertRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertRequest.Marshal(b, m, deterministic)
}
func (m *InsertRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertRequest.Merge(m, src)
}
func (m *InsertRequest) XXX_Size() int {
	return xxx_messageInfo_InsertRequest.Size(m)
}
func (m *InsertRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InsertRequest proto.InternalMessageInfo

func (m *InsertRequest) GetHandlerId() uint32 {
	if m != nil {
		return m.HandlerId
	}
	return 0
}

func (m *InsertRequest) GetAt() *Coordinates {
	if m != nil {
		return m.At
	}
	return nil
}

func (m *InsertRequest) GetStr() string {
	if m != nil {
		return m.Str
	}
	return ""
}

type InsertResponse struct {
	From                 *Coordinates `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   *Coordinates `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *InsertResponse) Reset()         { *m = InsertResponse{} }
func (m *InsertResponse) String() string { return proto.CompactTextString(m) }
func (*InsertResponse) ProtoMessage()    {}
func (*InsertResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d780504008e31fd, []int{8}
}

func (m *InsertResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertResponse.Unmarshal(m, b)
}
func (m *InsertResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertResponse.Marshal(b, m, deterministic)
}
func (m *InsertResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertResponse.Merge(m, src)
}
func (m *InsertResponse) XXX_Size() int {
	return xxx_messageInfo_InsertResponse.Size(m)
}
func (m *InsertResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InsertResponse proto.InternalMessageInfo

func (m *InsertResponse) GetFrom() *Coordinates {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *InsertResponse) GetTo() *Coordinates {
	if m != nil {
		return m.To
	}
	return nil
}

type DeleteRequest struct {
	HandlerId            uint32       `protobuf:"varint,1,opt,name=handler_id,json=handlerId,proto3" json:"handler_id,omitempty"`
	From                 *Coordinates `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To                   *Coordinates `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d780504008e31fd, []int{9}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetHandlerId() uint32 {
	if m != nil {
		return m.HandlerId
	}
	return 0
}

func (m *DeleteRequest) GetFrom() *Coordinates {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *DeleteRequest) GetTo() *Coordinates {
	if m != nil {
		return m.To
	}
	return nil
}

type DeleteResponse struct {
	Start                *Coordinates `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End                  *Coordinates `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	Str                  string       `protobuf:"bytes,3,opt,name=str,proto3" json:"str,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d780504008e31fd, []int{10}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func (m *DeleteResponse) GetStart() *Coordinates {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *DeleteResponse) GetEnd() *Coordinates {
	if m != nil {
		return m.End
	}
	return nil
}

func (m *DeleteResponse) GetStr() string {
	if m != nil {
		return m.Str
	}
	return ""
}

func init() {
	proto.RegisterEnum("proto.EditorEvent_Type", EditorEvent_Type_name, EditorEvent_Type_value)
	proto.RegisterType((*EditRequest)(nil), "proto.EditRequest")
	proto.RegisterType((*EditResponse)(nil), "proto.EditResponse")
	proto.RegisterType((*EditorEvent)(nil), "proto.EditorEvent")
	proto.RegisterType((*EditorSubscribeRequest)(nil), "proto.EditorSubscribeRequest")
	proto.RegisterType((*EditorSubscribeResponse)(nil), "proto.EditorSubscribeResponse")
	proto.RegisterType((*SetLocationListRequest)(nil), "proto.SetLocationListRequest")
	proto.RegisterType((*SetLocationListRequest_Location)(nil), "proto.SetLocationListRequest.Location")
	proto.RegisterType((*SetLocationListResponse)(nil), "proto.SetLocationListResponse")
	proto.RegisterType((*InsertRequest)(nil), "proto.InsertRequest")
	proto.RegisterType((*InsertResponse)(nil), "proto.InsertResponse")
	proto.RegisterType((*DeleteRequest)(nil), "proto.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "proto.DeleteResponse")
}

func init() { proto.RegisterFile("editor.proto", fileDescriptor_7d780504008e31fd) }

var fileDescriptor_7d780504008e31fd = []byte{
	// 569 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0x6d, 0x6b, 0x13, 0x41,
	0x10, 0x36, 0x97, 0x34, 0xf4, 0x26, 0x2f, 0xc6, 0x55, 0xdb, 0x78, 0x50, 0x2d, 0xa7, 0x86, 0x80,
	0x18, 0xe1, 0xc4, 0x1f, 0x20, 0x6d, 0x85, 0x48, 0x51, 0xb9, 0xfa, 0x49, 0x84, 0x72, 0xc9, 0x4e,
	0xe8, 0xc1, 0xe5, 0x36, 0xee, 0xce, 0x29, 0x15, 0xfc, 0x57, 0xfe, 0x05, 0xff, 0x95, 0x1f, 0xe4,
	0x6e, 0x77, 0xaf, 0xbd, 0x24, 0x0d, 0x11, 0xfa, 0xe9, 0xf6, 0xe6, 0xe5, 0x99, 0x67, 0x9e, 0x99,
	0x81, 0x36, 0xf2, 0x98, 0x84, 0x1c, 0x2d, 0xa4, 0x20, 0xc1, 0x76, 0x8a, 0x8f, 0x07, 0x84, 0x72,
	0xae, 0x4d, 0x9e, 0x4b, 0x59, 0xac, 0x9f, 0xfe, 0x17, 0x68, 0x9d, 0xf0, 0x98, 0x42, 0xfc, 0x96,
	0xa1, 0x22, 0xf6, 0x14, 0x3a, 0x12, 0x95, 0xc8, 0xe4, 0x14, 0xcf, 0xd3, 0x68, 0x8e, 0xfd, 0xda,
	0x61, 0x6d, 0xe8, 0x86, 0x6d, 0x6b, 0xfc, 0x10, 0xcd, 0x91, 0x0d, 0xa0, 0x39, 0xc9, 0x66, 0x33,
	0x94, 0x7d, 0xe7, 0xb0, 0x3e, 0x6c, 0x05, 0x5d, 0x8d, 0x35, 0x3a, 0xc2, 0x24, 0x09, 0xc5, 0x8f,
	0xd0, 0x78, 0xfd, 0x97, 0xd0, 0xd6, 0xd8, 0x6a, 0x21, 0x52, 0x85, 0xec, 0x00, 0xe0, 0x22, 0x4a,
	0x79, 0x82, 0xf2, 0x3c, 0xe6, 0x05, 0x72, 0x27, 0x74, 0x8d, 0x65, 0xcc, 0xfd, 0xdf, 0x35, 0xcd,
	0x45, 0xc8, 0x93, 0xef, 0x98, 0x12, 0x7b, 0x01, 0x0d, 0xba, 0x5c, 0x68, 0x0a, 0xdd, 0x60, 0xdf,
	0x14, 0xb9, 0x16, 0x31, 0xfa, 0x7c, 0xb9, 0xc0, 0xb0, 0x08, 0x5a, 0x25, 0xee, 0xac, 0x21, 0xfe,
	0x04, 0x5a, 0x65, 0x50, 0xcc, 0xfb, 0xf5, 0x82, 0x01, 0x58, 0xd3, 0x98, 0xfb, 0x01, 0x34, 0x72,
	0x4c, 0xd6, 0x86, 0xdd, 0xfc, 0xfb, 0x71, 0x81, 0x69, 0xef, 0x0e, 0xeb, 0x80, 0x9b, 0xff, 0x1d,
	0x25, 0x42, 0x61, 0xaf, 0x66, 0x7f, 0xdf, 0x25, 0x99, 0xba, 0xe8, 0x39, 0x3e, 0x87, 0x3d, 0xcd,
	0xe9, 0x2c, 0x9b, 0xa8, 0xa9, 0x8c, 0x27, 0x68, 0xc5, 0xfc, 0xaf, 0x06, 0xaa, 0xe2, 0x38, 0xcb,
	0xe2, 0x3c, 0x82, 0xfd, 0x95, 0x2a, 0x5a, 0x56, 0xff, 0x6f, 0x0d, 0xf6, 0xce, 0x90, 0x4e, 0xc5,
	0x34, 0xa2, 0x58, 0xa4, 0xa7, 0xb1, 0x2a, 0xc7, 0xb9, 0x59, 0x71, 0x76, 0x0c, 0x6e, 0x62, 0xb2,
	0x94, 0x99, 0xe5, 0xc0, 0xb0, 0x5c, 0x0f, 0x38, 0xb2, 0xb6, 0xf0, 0x2a, 0xd1, 0xfb, 0x05, 0xbb,
	0xd6, 0xcc, 0x06, 0xd0, 0x98, 0x49, 0x31, 0x2f, 0x4a, 0xb5, 0x02, 0x66, 0x17, 0x43, 0x08, 0xc9,
	0xe3, 0x34, 0x22, 0x54, 0x61, 0xe1, 0x67, 0x3e, 0x38, 0x24, 0x8a, 0x2e, 0xd7, 0x47, 0x39, 0x24,
	0xd8, 0x73, 0x68, 0x44, 0x44, 0xb2, 0x18, 0x53, 0x2b, 0xb8, 0x67, 0xa2, 0xde, 0x12, 0xc9, 0x78,
	0x92, 0x15, 0x50, 0xb9, 0x3b, 0x57, 0x66, 0x85, 0xac, 0x51, 0x86, 0x43, 0x67, 0x9c, 0x2a, 0x94,
	0xdb, 0xea, 0xe1, 0x83, 0x13, 0xd1, 0x26, 0x56, 0x11, 0xb1, 0x1e, 0xd4, 0x95, 0x21, 0xe5, 0x86,
	0xf9, 0xd3, 0xff, 0x0a, 0x5d, 0x5b, 0xc5, 0x2c, 0xfa, 0x2d, 0xaa, 0xe0, 0xff, 0x84, 0xce, 0x31,
	0x26, 0x48, 0xb8, 0x65, 0x0f, 0xb6, 0xb6, 0xb3, 0x55, 0xed, 0xfa, 0xc6, 0xda, 0x12, 0xba, 0xb6,
	0xb6, 0xe9, 0x6c, 0x08, 0x3b, 0x8a, 0x22, 0x49, 0x1b, 0x5a, 0xd3, 0x01, 0xec, 0x19, 0xd4, 0x31,
	0xe5, 0x1b, 0x68, 0xe4, 0xee, 0x55, 0x35, 0x83, 0x3f, 0x0e, 0x34, 0xf5, 0xa6, 0xb3, 0x57, 0xd0,
	0xc8, 0x5f, 0x8c, 0x5d, 0xbb, 0x1c, 0xa3, 0x82, 0x77, 0xbf, 0x62, 0x33, 0xec, 0xde, 0x83, 0x5b,
	0x9e, 0x07, 0x3b, 0xa8, 0xdc, 0xdb, 0xf2, 0x71, 0x7a, 0x8f, 0x6f, 0x72, 0x1b, 0xac, 0x4f, 0x70,
	0x77, 0x69, 0xad, 0x4a, 0xc4, 0xf5, 0xb7, 0x51, 0x22, 0xde, 0xb0, 0x8d, 0xec, 0x0d, 0x34, 0xf5,
	0x9e, 0xb0, 0x07, 0x26, 0xb2, 0xb2, 0x9c, 0xde, 0xc3, 0x25, 0xeb, 0x55, 0x9a, 0x1e, 0x42, 0x99,
	0x56, 0xd9, 0x87, 0x32, 0xad, 0x3a, 0xa9, 0x49, 0xb3, 0xb0, 0xbe, 0xfe, 0x17, 0x00, 0x00, 0xff,
	0xff, 0xc8, 0x75, 0xae, 0xff, 0x0d, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// EditorClient is the client API for Editor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EditorClient interface {
	Edit(ctx context.Context, in *EditRequest, opts ...grpc.CallOption) (*EditResponse, error)
	Subscribe(ctx context.Context, in *EditorSubscribeRequest, opts ...grpc.CallOption) (*EditorSubscribeResponse, error)
	SetLocationList(ctx context.Context, in *SetLocationListRequest, opts ...grpc.CallOption) (*SetLocationListResponse, error)
	// cell.Writer
	Insert(ctx context.Context, in *InsertRequest, opts ...grpc.CallOption) (*InsertResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
}

type editorClient struct {
	cc grpc.ClientConnInterface
}

func NewEditorClient(cc grpc.ClientConnInterface) EditorClient {
	return &editorClient{cc}
}

func (c *editorClient) Edit(ctx context.Context, in *EditRequest, opts ...grpc.CallOption) (*EditResponse, error) {
	out := new(EditResponse)
	err := c.cc.Invoke(ctx, "/proto.Editor/Edit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *editorClient) Subscribe(ctx context.Context, in *EditorSubscribeRequest, opts ...grpc.CallOption) (*EditorSubscribeResponse, error) {
	out := new(EditorSubscribeResponse)
	err := c.cc.Invoke(ctx, "/proto.Editor/Subscribe", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *editorClient) SetLocationList(ctx context.Context, in *SetLocationListRequest, opts ...grpc.CallOption) (*SetLocationListResponse, error) {
	out := new(SetLocationListResponse)
	err := c.cc.Invoke(ctx, "/proto.Editor/SetLocationList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *editorClient) Insert(ctx context.Context, in *InsertRequest, opts ...grpc.CallOption) (*InsertResponse, error) {
	out := new(InsertResponse)
	err := c.cc.Invoke(ctx, "/proto.Editor/Insert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *editorClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/proto.Editor/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EditorServer is the server API for Editor service.
type EditorServer interface {
	Edit(context.Context, *EditRequest) (*EditResponse, error)
	Subscribe(context.Context, *EditorSubscribeRequest) (*EditorSubscribeResponse, error)
	SetLocationList(context.Context, *SetLocationListRequest) (*SetLocationListResponse, error)
	// cell.Writer
	Insert(context.Context, *InsertRequest) (*InsertResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
}

// UnimplementedEditorServer can be embedded to have forward compatible implementations.
type UnimplementedEditorServer struct {
}

func (*UnimplementedEditorServer) Edit(ctx context.Context, req *EditRequest) (*EditResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Edit not implemented")
}
func (*UnimplementedEditorServer) Subscribe(ctx context.Context, req *EditorSubscribeRequest) (*EditorSubscribeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (*UnimplementedEditorServer) SetLocationList(ctx context.Context, req *SetLocationListRequest) (*SetLocationListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetLocationList not implemented")
}
func (*UnimplementedEditorServer) Insert(ctx context.Context, req *InsertRequest) (*InsertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Insert not implemented")
}
func (*UnimplementedEditorServer) Delete(ctx context.Context, req *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterEditorServer(s *grpc.Server, srv EditorServer) {
	s.RegisterService(&_Editor_serviceDesc, srv)
}

func _Editor_Edit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EditorServer).Edit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Editor/Edit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EditorServer).Edit(ctx, req.(*EditRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Editor_Subscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditorSubscribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EditorServer).Subscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Editor/Subscribe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EditorServer).Subscribe(ctx, req.(*EditorSubscribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Editor_SetLocationList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetLocationListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EditorServer).SetLocationList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Editor/SetLocationList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EditorServer).SetLocationList(ctx, req.(*SetLocationListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Editor_Insert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EditorServer).Insert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Editor/Insert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EditorServer).Insert(ctx, req.(*InsertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Editor_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EditorServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Editor/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EditorServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Editor_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Editor",
	HandlerType: (*EditorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Edit",
			Handler:    _Editor_Edit_Handler,
		},
		{
			MethodName: "Subscribe",
			Handler:    _Editor_Subscribe_Handler,
		},
		{
			MethodName: "SetLocationList",
			Handler:    _Editor_SetLocationList_Handler,
		},
		{
			MethodName: "Insert",
			Handler:    _Editor_Insert_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Editor_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "editor.proto",
}
