// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.16.0
// source: editor_event_handler.proto

package proto

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type EditorEventHandleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Event *EditorEvent `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
}

func (x *EditorEventHandleRequest) Reset() {
	*x = EditorEventHandleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_editor_event_handler_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditorEventHandleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditorEventHandleRequest) ProtoMessage() {}

func (x *EditorEventHandleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_editor_event_handler_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditorEventHandleRequest.ProtoReflect.Descriptor instead.
func (*EditorEventHandleRequest) Descriptor() ([]byte, []int) {
	return file_editor_event_handler_proto_rawDescGZIP(), []int{0}
}

func (x *EditorEventHandleRequest) GetEvent() *EditorEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

type EditorEventHandleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Quit    bool `protobuf:"varint,1,opt,name=quit,proto3" json:"quit,omitempty"`
	Handled bool `protobuf:"varint,2,opt,name=handled,proto3" json:"handled,omitempty"`
}

func (x *EditorEventHandleResponse) Reset() {
	*x = EditorEventHandleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_editor_event_handler_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditorEventHandleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditorEventHandleResponse) ProtoMessage() {}

func (x *EditorEventHandleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_editor_event_handler_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditorEventHandleResponse.ProtoReflect.Descriptor instead.
func (*EditorEventHandleResponse) Descriptor() ([]byte, []int) {
	return file_editor_event_handler_proto_rawDescGZIP(), []int{1}
}

func (x *EditorEventHandleResponse) GetQuit() bool {
	if x != nil {
		return x.Quit
	}
	return false
}

func (x *EditorEventHandleResponse) GetHandled() bool {
	if x != nil {
		return x.Handled
	}
	return false
}

var File_editor_event_handler_proto protoreflect.FileDescriptor

var file_editor_event_handler_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x68,
	0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x44, 0x0a, 0x18, 0x45, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a,
	0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x52, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x22, 0x49, 0x0a, 0x19, 0x45, 0x64, 0x69, 0x74, 0x6f,
	0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x71, 0x75, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x04, 0x71, 0x75, 0x69, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x61, 0x6e, 0x64,
	0x6c, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x68, 0x61, 0x6e, 0x64, 0x6c,
	0x65, 0x64, 0x32, 0x61, 0x0a, 0x12, 0x45, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x12, 0x4b, 0x0a, 0x06, 0x48, 0x61, 0x6e, 0x64,
	0x6c, 0x65, 0x12, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x64, 0x69, 0x74, 0x6f,
	0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x64, 0x69, 0x74,
	0x6f, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_editor_event_handler_proto_rawDescOnce sync.Once
	file_editor_event_handler_proto_rawDescData = file_editor_event_handler_proto_rawDesc
)

func file_editor_event_handler_proto_rawDescGZIP() []byte {
	file_editor_event_handler_proto_rawDescOnce.Do(func() {
		file_editor_event_handler_proto_rawDescData = protoimpl.X.CompressGZIP(file_editor_event_handler_proto_rawDescData)
	})
	return file_editor_event_handler_proto_rawDescData
}

var file_editor_event_handler_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_editor_event_handler_proto_goTypes = []interface{}{
	(*EditorEventHandleRequest)(nil),  // 0: proto.EditorEventHandleRequest
	(*EditorEventHandleResponse)(nil), // 1: proto.EditorEventHandleResponse
	(*EditorEvent)(nil),               // 2: proto.EditorEvent
}
var file_editor_event_handler_proto_depIdxs = []int32{
	2, // 0: proto.EditorEventHandleRequest.event:type_name -> proto.EditorEvent
	0, // 1: proto.EditorEventHandler.Handle:input_type -> proto.EditorEventHandleRequest
	1, // 2: proto.EditorEventHandler.Handle:output_type -> proto.EditorEventHandleResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_editor_event_handler_proto_init() }
func file_editor_event_handler_proto_init() {
	if File_editor_event_handler_proto != nil {
		return
	}
	file_editor_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_editor_event_handler_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditorEventHandleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_editor_event_handler_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditorEventHandleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_editor_event_handler_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_editor_event_handler_proto_goTypes,
		DependencyIndexes: file_editor_event_handler_proto_depIdxs,
		MessageInfos:      file_editor_event_handler_proto_msgTypes,
	}.Build()
	File_editor_event_handler_proto = out.File
	file_editor_event_handler_proto_rawDesc = nil
	file_editor_event_handler_proto_goTypes = nil
	file_editor_event_handler_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// EditorEventHandlerClient is the client API for EditorEventHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EditorEventHandlerClient interface {
	Handle(ctx context.Context, in *EditorEventHandleRequest, opts ...grpc.CallOption) (*EditorEventHandleResponse, error)
}

type editorEventHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewEditorEventHandlerClient(cc grpc.ClientConnInterface) EditorEventHandlerClient {
	return &editorEventHandlerClient{cc}
}

func (c *editorEventHandlerClient) Handle(ctx context.Context, in *EditorEventHandleRequest, opts ...grpc.CallOption) (*EditorEventHandleResponse, error) {
	out := new(EditorEventHandleResponse)
	err := c.cc.Invoke(ctx, "/proto.EditorEventHandler/Handle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EditorEventHandlerServer is the server API for EditorEventHandler service.
type EditorEventHandlerServer interface {
	Handle(context.Context, *EditorEventHandleRequest) (*EditorEventHandleResponse, error)
}

// UnimplementedEditorEventHandlerServer can be embedded to have forward compatible implementations.
type UnimplementedEditorEventHandlerServer struct {
}

func (*UnimplementedEditorEventHandlerServer) Handle(context.Context, *EditorEventHandleRequest) (*EditorEventHandleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Handle not implemented")
}

func RegisterEditorEventHandlerServer(s *grpc.Server, srv EditorEventHandlerServer) {
	s.RegisterService(&_EditorEventHandler_serviceDesc, srv)
}

func _EditorEventHandler_Handle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditorEventHandleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EditorEventHandlerServer).Handle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EditorEventHandler/Handle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EditorEventHandlerServer).Handle(ctx, req.(*EditorEventHandleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _EditorEventHandler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.EditorEventHandler",
	HandlerType: (*EditorEventHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Handle",
			Handler:    _EditorEventHandler_Handle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "editor_event_handler.proto",
}
