// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/handler.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DrawRequest struct {
	Width                int32    `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height               int32    `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DrawRequest) Reset()         { *m = DrawRequest{} }
func (m *DrawRequest) String() string { return proto.CompactTextString(m) }
func (*DrawRequest) ProtoMessage()    {}
func (*DrawRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f2821b95a83419f, []int{0}
}

func (m *DrawRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DrawRequest.Unmarshal(m, b)
}
func (m *DrawRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DrawRequest.Marshal(b, m, deterministic)
}
func (m *DrawRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DrawRequest.Merge(m, src)
}
func (m *DrawRequest) XXX_Size() int {
	return xxx_messageInfo_DrawRequest.Size(m)
}
func (m *DrawRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DrawRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DrawRequest proto.InternalMessageInfo

func (m *DrawRequest) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *DrawRequest) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

type DrawResponse struct {
	Rows                 []*CellRow           `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	Cursor               *DrawResponse_Cursor `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DrawResponse) Reset()         { *m = DrawResponse{} }
func (m *DrawResponse) String() string { return proto.CompactTextString(m) }
func (*DrawResponse) ProtoMessage()    {}
func (*DrawResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f2821b95a83419f, []int{1}
}

func (m *DrawResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DrawResponse.Unmarshal(m, b)
}
func (m *DrawResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DrawResponse.Marshal(b, m, deterministic)
}
func (m *DrawResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DrawResponse.Merge(m, src)
}
func (m *DrawResponse) XXX_Size() int {
	return xxx_messageInfo_DrawResponse.Size(m)
}
func (m *DrawResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DrawResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DrawResponse proto.InternalMessageInfo

func (m *DrawResponse) GetRows() []*CellRow {
	if m != nil {
		return m.Rows
	}
	return nil
}

func (m *DrawResponse) GetCursor() *DrawResponse_Cursor {
	if m != nil {
		return m.Cursor
	}
	return nil
}

type DrawResponse_Cursor struct {
	Position             *Coordinates `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	Show                 bool         `protobuf:"varint,2,opt,name=show,proto3" json:"show,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *DrawResponse_Cursor) Reset()         { *m = DrawResponse_Cursor{} }
func (m *DrawResponse_Cursor) String() string { return proto.CompactTextString(m) }
func (*DrawResponse_Cursor) ProtoMessage()    {}
func (*DrawResponse_Cursor) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f2821b95a83419f, []int{1, 0}
}

func (m *DrawResponse_Cursor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DrawResponse_Cursor.Unmarshal(m, b)
}
func (m *DrawResponse_Cursor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DrawResponse_Cursor.Marshal(b, m, deterministic)
}
func (m *DrawResponse_Cursor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DrawResponse_Cursor.Merge(m, src)
}
func (m *DrawResponse_Cursor) XXX_Size() int {
	return xxx_messageInfo_DrawResponse_Cursor.Size(m)
}
func (m *DrawResponse_Cursor) XXX_DiscardUnknown() {
	xxx_messageInfo_DrawResponse_Cursor.DiscardUnknown(m)
}

var xxx_messageInfo_DrawResponse_Cursor proto.InternalMessageInfo

func (m *DrawResponse_Cursor) GetPosition() *Coordinates {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *DrawResponse_Cursor) GetShow() bool {
	if m != nil {
		return m.Show
	}
	return false
}

type HandleRequest struct {
	Event                *Event   `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HandleRequest) Reset()         { *m = HandleRequest{} }
func (m *HandleRequest) String() string { return proto.CompactTextString(m) }
func (*HandleRequest) ProtoMessage()    {}
func (*HandleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f2821b95a83419f, []int{2}
}

func (m *HandleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandleRequest.Unmarshal(m, b)
}
func (m *HandleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandleRequest.Marshal(b, m, deterministic)
}
func (m *HandleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandleRequest.Merge(m, src)
}
func (m *HandleRequest) XXX_Size() int {
	return xxx_messageInfo_HandleRequest.Size(m)
}
func (m *HandleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HandleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HandleRequest proto.InternalMessageInfo

func (m *HandleRequest) GetEvent() *Event {
	if m != nil {
		return m.Event
	}
	return nil
}

type HandleResponse struct {
	Handled              bool     `protobuf:"varint,1,opt,name=handled,proto3" json:"handled,omitempty"`
	Quit                 bool     `protobuf:"varint,2,opt,name=quit,proto3" json:"quit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HandleResponse) Reset()         { *m = HandleResponse{} }
func (m *HandleResponse) String() string { return proto.CompactTextString(m) }
func (*HandleResponse) ProtoMessage()    {}
func (*HandleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f2821b95a83419f, []int{3}
}

func (m *HandleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandleResponse.Unmarshal(m, b)
}
func (m *HandleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandleResponse.Marshal(b, m, deterministic)
}
func (m *HandleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandleResponse.Merge(m, src)
}
func (m *HandleResponse) XXX_Size() int {
	return xxx_messageInfo_HandleResponse.Size(m)
}
func (m *HandleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HandleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HandleResponse proto.InternalMessageInfo

func (m *HandleResponse) GetHandled() bool {
	if m != nil {
		return m.Handled
	}
	return false
}

func (m *HandleResponse) GetQuit() bool {
	if m != nil {
		return m.Quit
	}
	return false
}

type ManRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ManRequest) Reset()         { *m = ManRequest{} }
func (m *ManRequest) String() string { return proto.CompactTextString(m) }
func (*ManRequest) ProtoMessage()    {}
func (*ManRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f2821b95a83419f, []int{4}
}

func (m *ManRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ManRequest.Unmarshal(m, b)
}
func (m *ManRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ManRequest.Marshal(b, m, deterministic)
}
func (m *ManRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ManRequest.Merge(m, src)
}
func (m *ManRequest) XXX_Size() int {
	return xxx_messageInfo_ManRequest.Size(m)
}
func (m *ManRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ManRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ManRequest proto.InternalMessageInfo

type ManResponse struct {
	Man                  *Manual  `protobuf:"bytes,1,opt,name=man,proto3" json:"man,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ManResponse) Reset()         { *m = ManResponse{} }
func (m *ManResponse) String() string { return proto.CompactTextString(m) }
func (*ManResponse) ProtoMessage()    {}
func (*ManResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f2821b95a83419f, []int{5}
}

func (m *ManResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ManResponse.Unmarshal(m, b)
}
func (m *ManResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ManResponse.Marshal(b, m, deterministic)
}
func (m *ManResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ManResponse.Merge(m, src)
}
func (m *ManResponse) XXX_Size() int {
	return xxx_messageInfo_ManResponse.Size(m)
}
func (m *ManResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ManResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ManResponse proto.InternalMessageInfo

func (m *ManResponse) GetMan() *Manual {
	if m != nil {
		return m.Man
	}
	return nil
}

func init() {
	proto.RegisterType((*DrawRequest)(nil), "proto.DrawRequest")
	proto.RegisterType((*DrawResponse)(nil), "proto.DrawResponse")
	proto.RegisterType((*DrawResponse_Cursor)(nil), "proto.DrawResponse.Cursor")
	proto.RegisterType((*HandleRequest)(nil), "proto.HandleRequest")
	proto.RegisterType((*HandleResponse)(nil), "proto.HandleResponse")
	proto.RegisterType((*ManRequest)(nil), "proto.ManRequest")
	proto.RegisterType((*ManResponse)(nil), "proto.ManResponse")
}

func init() { proto.RegisterFile("proto/handler.proto", fileDescriptor_1f2821b95a83419f) }

var fileDescriptor_1f2821b95a83419f = []byte{
	// 360 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x50, 0xc1, 0x4e, 0xeb, 0x30,
	0x10, 0x54, 0x5e, 0x9b, 0xb4, 0xda, 0xb4, 0x7d, 0xef, 0x6d, 0x0b, 0x8a, 0x72, 0xa1, 0xf2, 0xa9,
	0x07, 0x94, 0x4a, 0xa9, 0x38, 0x21, 0x71, 0x29, 0x48, 0x1c, 0xe8, 0xc5, 0x7f, 0x60, 0x88, 0x45,
	0x22, 0xa5, 0x76, 0x6b, 0x3b, 0xe4, 0x73, 0xf8, 0x09, 0x3e, 0x10, 0xc5, 0x76, 0xa0, 0x45, 0x9c,
	0x92, 0x9d, 0xd9, 0x99, 0xf1, 0x0e, 0xcc, 0x0f, 0x4a, 0x1a, 0xb9, 0x2e, 0x99, 0x28, 0x6a, 0xae,
	0x32, 0x3b, 0x61, 0x68, 0x3f, 0xe9, 0x3f, 0xc7, 0x19, 0xae, 0xf6, 0x8e, 0x48, 0xff, 0x7a, 0xa4,
	0xa9, 0x1c, 0x40, 0x6e, 0x21, 0xbe, 0x57, 0xac, 0xa5, 0xfc, 0xd8, 0x70, 0x6d, 0x70, 0x01, 0x61,
	0x5b, 0x15, 0xa6, 0x4c, 0x82, 0x65, 0xb0, 0x0a, 0xa9, 0x1b, 0xf0, 0x12, 0xa2, 0x92, 0x57, 0xaf,
	0xa5, 0x49, 0xfe, 0x58, 0xd8, 0x4f, 0xe4, 0x23, 0x80, 0x89, 0x53, 0xeb, 0x83, 0x14, 0x9a, 0x23,
	0x81, 0xa1, 0x92, 0xad, 0x4e, 0x82, 0xe5, 0x60, 0x15, 0xe7, 0x33, 0x97, 0x91, 0x6d, 0x79, 0x5d,
	0x53, 0xd9, 0x52, 0xcb, 0x61, 0x0e, 0xd1, 0x4b, 0xa3, 0xb4, 0x54, 0xd6, 0x2c, 0xce, 0x53, 0xbf,
	0x75, 0x6a, 0x94, 0x6d, 0xed, 0x06, 0xf5, 0x9b, 0xe9, 0x13, 0x44, 0x0e, 0xc1, 0x0c, 0xc6, 0x07,
	0xa9, 0x2b, 0x53, 0x49, 0x61, 0xdf, 0x18, 0xe7, 0xd8, 0xa7, 0x48, 0xa9, 0x8a, 0x4a, 0x30, 0xc3,
	0x35, 0xfd, 0xda, 0x41, 0x84, 0xa1, 0x2e, 0x65, 0x6b, 0xb3, 0xc6, 0xd4, 0xfe, 0x93, 0x0d, 0x4c,
	0x1f, 0x6d, 0x5d, 0xfd, 0xd5, 0x04, 0x42, 0xfe, 0xc6, 0x85, 0xf1, 0x8e, 0x13, 0xef, 0xf8, 0xd0,
	0x61, 0xd4, 0x51, 0xe4, 0x0e, 0x66, 0xbd, 0xc8, 0x1f, 0x9b, 0xc0, 0xc8, 0xb5, 0x5e, 0x58, 0xdd,
	0x98, 0xf6, 0x63, 0x17, 0x7a, 0x6c, 0x2a, 0xd3, 0x87, 0x76, 0xff, 0x64, 0x02, 0xb0, 0x63, 0xc2,
	0x27, 0x92, 0x0c, 0x62, 0x3b, 0x79, 0xab, 0x2b, 0x18, 0xec, 0x59, 0x7f, 0xd0, 0xd4, 0xc7, 0xef,
	0x98, 0x68, 0x58, 0x4d, 0x3b, 0x26, 0x7f, 0x0f, 0x60, 0xe4, 0xe2, 0x15, 0xae, 0x61, 0xd8, 0x75,
	0x85, 0x78, 0x56, 0x9c, 0xf5, 0x4d, 0xe7, 0xbf, 0x94, 0x89, 0x37, 0x10, 0x39, 0x2d, 0x2e, 0x3c,
	0x7d, 0x76, 0x7e, 0x7a, 0xf1, 0x03, 0xf5, 0xb2, 0x6b, 0x18, 0xec, 0x98, 0xc0, 0xff, 0xdf, 0xcf,
	0xe9, 0x05, 0x78, 0x0a, 0xb9, 0xed, 0xe7, 0xc8, 0x42, 0x9b, 0xcf, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xfb, 0xf0, 0x16, 0x8a, 0x90, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// HandlerClient is the client API for Handler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HandlerClient interface {
	Draw(ctx context.Context, in *DrawRequest, opts ...grpc.CallOption) (*DrawResponse, error)
	Handle(ctx context.Context, in *HandleRequest, opts ...grpc.CallOption) (*HandleResponse, error)
	Man(ctx context.Context, in *ManRequest, opts ...grpc.CallOption) (*ManResponse, error)
}

type handlerClient struct {
	cc grpc.ClientConnInterface
}

func NewHandlerClient(cc grpc.ClientConnInterface) HandlerClient {
	return &handlerClient{cc}
}

func (c *handlerClient) Draw(ctx context.Context, in *DrawRequest, opts ...grpc.CallOption) (*DrawResponse, error) {
	out := new(DrawResponse)
	err := c.cc.Invoke(ctx, "/proto.Handler/Draw", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *handlerClient) Handle(ctx context.Context, in *HandleRequest, opts ...grpc.CallOption) (*HandleResponse, error) {
	out := new(HandleResponse)
	err := c.cc.Invoke(ctx, "/proto.Handler/Handle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *handlerClient) Man(ctx context.Context, in *ManRequest, opts ...grpc.CallOption) (*ManResponse, error) {
	out := new(ManResponse)
	err := c.cc.Invoke(ctx, "/proto.Handler/Man", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HandlerServer is the server API for Handler service.
type HandlerServer interface {
	Draw(context.Context, *DrawRequest) (*DrawResponse, error)
	Handle(context.Context, *HandleRequest) (*HandleResponse, error)
	Man(context.Context, *ManRequest) (*ManResponse, error)
}

// UnimplementedHandlerServer can be embedded to have forward compatible implementations.
type UnimplementedHandlerServer struct {
}

func (*UnimplementedHandlerServer) Draw(ctx context.Context, req *DrawRequest) (*DrawResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Draw not implemented")
}
func (*UnimplementedHandlerServer) Handle(ctx context.Context, req *HandleRequest) (*HandleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Handle not implemented")
}
func (*UnimplementedHandlerServer) Man(ctx context.Context, req *ManRequest) (*ManResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Man not implemented")
}

func RegisterHandlerServer(s *grpc.Server, srv HandlerServer) {
	s.RegisterService(&_Handler_serviceDesc, srv)
}

func _Handler_Draw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DrawRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HandlerServer).Draw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Handler/Draw",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HandlerServer).Draw(ctx, req.(*DrawRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Handler_Handle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HandlerServer).Handle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Handler/Handle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HandlerServer).Handle(ctx, req.(*HandleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Handler_Man_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ManRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HandlerServer).Man(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Handler/Man",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HandlerServer).Man(ctx, req.(*ManRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Handler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Handler",
	HandlerType: (*HandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Draw",
			Handler:    _Handler_Draw_Handler,
		},
		{
			MethodName: "Handle",
			Handler:    _Handler_Handle_Handler,
		},
		{
			MethodName: "Man",
			Handler:    _Handler_Man_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/handler.proto",
}
