// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ernestrc/go-tui/proto (interfaces: MuxBroker,MuxConn)

// Package mock_proto is a generated GoMock package.
package proto

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockMuxBroker is a mock of MuxBroker interface
type MockMuxBroker struct {
	ctrl     *gomock.Controller
	recorder *MockMuxBrokerMockRecorder
}

// MockMuxBrokerMockRecorder is the mock recorder for MockMuxBroker
type MockMuxBrokerMockRecorder struct {
	mock *MockMuxBroker
}

// NewMockMuxBroker creates a new mock instance
func NewMockMuxBroker(ctrl *gomock.Controller) *MockMuxBroker {
	mock := &MockMuxBroker{ctrl: ctrl}
	mock.recorder = &MockMuxBrokerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockMuxBroker) EXPECT() *MockMuxBrokerMockRecorder {
	return m.recorder
}

// AcceptAndServe mocks base method
func (m *MockMuxBroker) AcceptAndServe(arg0 uint32, arg1 func([]grpc.ServerOption) *grpc.Server) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AcceptAndServe", arg0, arg1)
}

// AcceptAndServe indicates an expected call of AcceptAndServe
func (mr *MockMuxBrokerMockRecorder) AcceptAndServe(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptAndServe", reflect.TypeOf((*MockMuxBroker)(nil).AcceptAndServe), arg0, arg1)
}

// Close mocks base method
func (m *MockMuxBroker) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close
func (mr *MockMuxBrokerMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockMuxBroker)(nil).Close))
}

// Dial mocks base method
func (m *MockMuxBroker) Dial(arg0 uint32) (MuxConn, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Dial", arg0)
	ret0, _ := ret[0].(MuxConn)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Dial indicates an expected call of Dial
func (mr *MockMuxBrokerMockRecorder) Dial(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dial", reflect.TypeOf((*MockMuxBroker)(nil).Dial), arg0)
}

// NextId mocks base method
func (m *MockMuxBroker) NextId() uint32 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NextId")
	ret0, _ := ret[0].(uint32)
	return ret0
}

// NextId indicates an expected call of NextId
func (mr *MockMuxBrokerMockRecorder) NextId() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NextId", reflect.TypeOf((*MockMuxBroker)(nil).NextId))
}

// MockMuxConn is a mock of MuxConn interface
type MockMuxConn struct {
	ctrl     *gomock.Controller
	recorder *MockMuxConnMockRecorder
}

// MockMuxConnMockRecorder is the mock recorder for MockMuxConn
type MockMuxConnMockRecorder struct {
	mock *MockMuxConn
}

// NewMockMuxConn creates a new mock instance
func NewMockMuxConn(ctrl *gomock.Controller) *MockMuxConn {
	mock := &MockMuxConn{ctrl: ctrl}
	mock.recorder = &MockMuxConnMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockMuxConn) EXPECT() *MockMuxConnMockRecorder {
	return m.recorder
}

// Close mocks base method
func (m *MockMuxConn) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close
func (mr *MockMuxConnMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockMuxConn)(nil).Close))
}

// Invoke mocks base method
func (m *MockMuxConn) Invoke(arg0 context.Context, arg1 string, arg2, arg3 interface{}, arg4 ...grpc.CallOption) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1, arg2, arg3}
	for _, a := range arg4 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Invoke", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Invoke indicates an expected call of Invoke
func (mr *MockMuxConnMockRecorder) Invoke(arg0, arg1, arg2, arg3 interface{}, arg4 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1, arg2, arg3}, arg4...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Invoke", reflect.TypeOf((*MockMuxConn)(nil).Invoke), varargs...)
}

// NewStream mocks base method
func (m *MockMuxConn) NewStream(arg0 context.Context, arg1 *grpc.StreamDesc, arg2 string, arg3 ...grpc.CallOption) (grpc.ClientStream, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NewStream", varargs...)
	ret0, _ := ret[0].(grpc.ClientStream)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewStream indicates an expected call of NewStream
func (mr *MockMuxConnMockRecorder) NewStream(arg0, arg1, arg2 interface{}, arg3 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1, arg2}, arg3...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewStream", reflect.TypeOf((*MockMuxConn)(nil).NewStream), varargs...)
}
