// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/term.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Attribute_Colors int32

const (
	Attribute_ColorDefault Attribute_Colors = 0
	Attribute_ColorBlack   Attribute_Colors = 1
	Attribute_ColorRed     Attribute_Colors = 2
	Attribute_ColorGreen   Attribute_Colors = 3
	Attribute_ColorYellow  Attribute_Colors = 4
	Attribute_ColorBlue    Attribute_Colors = 5
	Attribute_ColorMagenta Attribute_Colors = 6
	Attribute_ColorCyan    Attribute_Colors = 7
	Attribute_ColorWhite   Attribute_Colors = 8
)

var Attribute_Colors_name = map[int32]string{
	0: "ColorDefault",
	1: "ColorBlack",
	2: "ColorRed",
	3: "ColorGreen",
	4: "ColorYellow",
	5: "ColorBlue",
	6: "ColorMagenta",
	7: "ColorCyan",
	8: "ColorWhite",
}

var Attribute_Colors_value = map[string]int32{
	"ColorDefault": 0,
	"ColorBlack":   1,
	"ColorRed":     2,
	"ColorGreen":   3,
	"ColorYellow":  4,
	"ColorBlue":    5,
	"ColorMagenta": 6,
	"ColorCyan":    7,
	"ColorWhite":   8,
}

func (x Attribute_Colors) String() string {
	return proto.EnumName(Attribute_Colors_name, int32(x))
}

func (Attribute_Colors) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a5264c19600bbd1c, []int{0, 0}
}

type Attribute_Attrs int32

const (
	Attribute_AttrBold      Attribute_Attrs = 0
	Attribute_AttrUnderline Attribute_Attrs = 1
	Attribute_AttrReverse   Attribute_Attrs = 2
)

var Attribute_Attrs_name = map[int32]string{
	0: "AttrBold",
	1: "AttrUnderline",
	2: "AttrReverse",
}

var Attribute_Attrs_value = map[string]int32{
	"AttrBold":      0,
	"AttrUnderline": 1,
	"AttrReverse":   2,
}

func (x Attribute_Attrs) String() string {
	return proto.EnumName(Attribute_Attrs_name, int32(x))
}

func (Attribute_Attrs) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a5264c19600bbd1c, []int{0, 1}
}

type Event_Type int32

const (
	Event_TypeKey   Event_Type = 0
	Event_TypeMouse Event_Type = 2
)

var Event_Type_name = map[int32]string{
	0: "TypeKey",
	2: "TypeMouse",
}

var Event_Type_value = map[string]int32{
	"TypeKey":   0,
	"TypeMouse": 2,
}

func (x Event_Type) String() string {
	return proto.EnumName(Event_Type_name, int32(x))
}

func (Event_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a5264c19600bbd1c, []int{4, 0}
}

type Event_Mod int32

const (
	Event_None   Event_Mod = 0
	Event_Alt    Event_Mod = 1
	Event_Motion Event_Mod = 2
)

var Event_Mod_name = map[int32]string{
	0: "None",
	1: "Alt",
	2: "Motion",
}

var Event_Mod_value = map[string]int32{
	"None":   0,
	"Alt":    1,
	"Motion": 2,
}

func (x Event_Mod) String() string {
	return proto.EnumName(Event_Mod_name, int32(x))
}

func (Event_Mod) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a5264c19600bbd1c, []int{4, 1}
}

type Event_Key int32

const (
	Event_F1             Event_Key = 0
	Event_F2             Event_Key = 1
	Event_F3             Event_Key = 2
	Event_F4             Event_Key = 3
	Event_F5             Event_Key = 4
	Event_F6             Event_Key = 5
	Event_F7             Event_Key = 6
	Event_F8             Event_Key = 7
	Event_F9             Event_Key = 8
	Event_F10            Event_Key = 9
	Event_F11            Event_Key = 10
	Event_F12            Event_Key = 11
	Event_Insert         Event_Key = 12
	Event_Delete         Event_Key = 13
	Event_Home           Event_Key = 14
	Event_End            Event_Key = 15
	Event_Pgup           Event_Key = 16
	Event_Pgdn           Event_Key = 17
	Event_ArrowUp        Event_Key = 18
	Event_ArrowDown      Event_Key = 19
	Event_ArrowLeft      Event_Key = 20
	Event_ArrowRight     Event_Key = 21
	Event_MouseLeft      Event_Key = 22
	Event_MouseMiddle    Event_Key = 23
	Event_MouseRight     Event_Key = 24
	Event_MouseRelease   Event_Key = 25
	Event_MouseWheelUp   Event_Key = 26
	Event_MouseWheelDown Event_Key = 27
	Event_CtrlTilde      Event_Key = 28
	Event_Ctrl2          Event_Key = 29
	Event_CtrlSpace      Event_Key = 30
	Event_CtrlA          Event_Key = 31
	Event_CtrlB          Event_Key = 32
	Event_CtrlC          Event_Key = 33
	Event_CtrlD          Event_Key = 34
	Event_CtrlE          Event_Key = 35
	Event_CtrlF          Event_Key = 36
	Event_CtrlG          Event_Key = 37
	Event_Backspace      Event_Key = 38
	Event_CtrlH          Event_Key = 39
	Event_Tab            Event_Key = 40
	Event_CtrlI          Event_Key = 41
	Event_CtrlJ          Event_Key = 42
	Event_CtrlK          Event_Key = 43
	Event_CtrlL          Event_Key = 44
	Event_Enter          Event_Key = 45
	Event_CtrlM          Event_Key = 46
	Event_CtrlN          Event_Key = 47
	Event_CtrlO          Event_Key = 48
	Event_CtrlP          Event_Key = 49
	Event_CtrlQ          Event_Key = 50
	Event_CtrlR          Event_Key = 51
	Event_CtrlS          Event_Key = 52
	Event_CtrlT          Event_Key = 53
	Event_CtrlU          Event_Key = 54
	Event_CtrlV          Event_Key = 55
	Event_CtrlW          Event_Key = 56
	Event_CtrlX          Event_Key = 57
	Event_CtrlY          Event_Key = 58
	Event_CtrlZ          Event_Key = 59
	Event_Esc            Event_Key = 60
	Event_CtrlLsqBracket Event_Key = 61
	Event_Ctrl3          Event_Key = 62
	Event_Ctrl4          Event_Key = 63
	Event_CtrlBackslash  Event_Key = 64
	Event_Ctrl5          Event_Key = 65
	Event_CtrlRsqBracket Event_Key = 66
	Event_Ctrl6          Event_Key = 67
	Event_Ctrl7          Event_Key = 68
	Event_CtrlSlash      Event_Key = 69
	Event_CtrlUnderscore Event_Key = 70
	Event_Space          Event_Key = 72
	Event_Backspace2     Event_Key = 73
	Event_Ctrl8          Event_Key = 74
)

var Event_Key_name = map[int32]string{
	0:  "F1",
	1:  "F2",
	2:  "F3",
	3:  "F4",
	4:  "F5",
	5:  "F6",
	6:  "F7",
	7:  "F8",
	8:  "F9",
	9:  "F10",
	10: "F11",
	11: "F12",
	12: "Insert",
	13: "Delete",
	14: "Home",
	15: "End",
	16: "Pgup",
	17: "Pgdn",
	18: "ArrowUp",
	19: "ArrowDown",
	20: "ArrowLeft",
	21: "ArrowRight",
	22: "MouseLeft",
	23: "MouseMiddle",
	24: "MouseRight",
	25: "MouseRelease",
	26: "MouseWheelUp",
	27: "MouseWheelDown",
	28: "CtrlTilde",
	29: "Ctrl2",
	30: "CtrlSpace",
	31: "CtrlA",
	32: "CtrlB",
	33: "CtrlC",
	34: "CtrlD",
	35: "CtrlE",
	36: "CtrlF",
	37: "CtrlG",
	38: "Backspace",
	39: "CtrlH",
	40: "Tab",
	41: "CtrlI",
	42: "CtrlJ",
	43: "CtrlK",
	44: "CtrlL",
	45: "Enter",
	46: "CtrlM",
	47: "CtrlN",
	48: "CtrlO",
	49: "CtrlP",
	50: "CtrlQ",
	51: "CtrlR",
	52: "CtrlS",
	53: "CtrlT",
	54: "CtrlU",
	55: "CtrlV",
	56: "CtrlW",
	57: "CtrlX",
	58: "CtrlY",
	59: "CtrlZ",
	60: "Esc",
	61: "CtrlLsqBracket",
	62: "Ctrl3",
	63: "Ctrl4",
	64: "CtrlBackslash",
	65: "Ctrl5",
	66: "CtrlRsqBracket",
	67: "Ctrl6",
	68: "Ctrl7",
	69: "CtrlSlash",
	70: "CtrlUnderscore",
	72: "Space",
	73: "Backspace2",
	74: "Ctrl8",
}

var Event_Key_value = map[string]int32{
	"F1":             0,
	"F2":             1,
	"F3":             2,
	"F4":             3,
	"F5":             4,
	"F6":             5,
	"F7":             6,
	"F8":             7,
	"F9":             8,
	"F10":            9,
	"F11":            10,
	"F12":            11,
	"Insert":         12,
	"Delete":         13,
	"Home":           14,
	"End":            15,
	"Pgup":           16,
	"Pgdn":           17,
	"ArrowUp":        18,
	"ArrowDown":      19,
	"ArrowLeft":      20,
	"ArrowRight":     21,
	"MouseLeft":      22,
	"MouseMiddle":    23,
	"MouseRight":     24,
	"MouseRelease":   25,
	"MouseWheelUp":   26,
	"MouseWheelDown": 27,
	"CtrlTilde":      28,
	"Ctrl2":          29,
	"CtrlSpace":      30,
	"CtrlA":          31,
	"CtrlB":          32,
	"CtrlC":          33,
	"CtrlD":          34,
	"CtrlE":          35,
	"CtrlF":          36,
	"CtrlG":          37,
	"Backspace":      38,
	"CtrlH":          39,
	"Tab":            40,
	"CtrlI":          41,
	"CtrlJ":          42,
	"CtrlK":          43,
	"CtrlL":          44,
	"Enter":          45,
	"CtrlM":          46,
	"CtrlN":          47,
	"CtrlO":          48,
	"CtrlP":          49,
	"CtrlQ":          50,
	"CtrlR":          51,
	"CtrlS":          52,
	"CtrlT":          53,
	"CtrlU":          54,
	"CtrlV":          55,
	"CtrlW":          56,
	"CtrlX":          57,
	"CtrlY":          58,
	"CtrlZ":          59,
	"Esc":            60,
	"CtrlLsqBracket": 61,
	"Ctrl3":          62,
	"Ctrl4":          63,
	"CtrlBackslash":  64,
	"Ctrl5":          65,
	"CtrlRsqBracket": 66,
	"Ctrl6":          67,
	"Ctrl7":          68,
	"CtrlSlash":      69,
	"CtrlUnderscore": 70,
	"Space":          72,
	"Backspace2":     73,
	"Ctrl8":          74,
}

func (x Event_Key) String() string {
	return proto.EnumName(Event_Key_name, int32(x))
}

func (Event_Key) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a5264c19600bbd1c, []int{4, 2}
}

type Attribute struct {
	// Bitwise-OR of Colors and Attrs.
	Flags                uint32   `protobuf:"varint,1,opt,name=flags,proto3" json:"flags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Attribute) Reset()         { *m = Attribute{} }
func (m *Attribute) String() string { return proto.CompactTextString(m) }
func (*Attribute) ProtoMessage()    {}
func (*Attribute) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5264c19600bbd1c, []int{0}
}

func (m *Attribute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Attribute.Unmarshal(m, b)
}
func (m *Attribute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Attribute.Marshal(b, m, deterministic)
}
func (m *Attribute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Attribute.Merge(m, src)
}
func (m *Attribute) XXX_Size() int {
	return xxx_messageInfo_Attribute.Size(m)
}
func (m *Attribute) XXX_DiscardUnknown() {
	xxx_messageInfo_Attribute.DiscardUnknown(m)
}

var xxx_messageInfo_Attribute proto.InternalMessageInfo

func (m *Attribute) GetFlags() uint32 {
	if m != nil {
		return m.Flags
	}
	return 0
}

type Cell struct {
	Character            uint32     `protobuf:"varint,1,opt,name=Character,proto3" json:"Character,omitempty"`
	Foreground           *Attribute `protobuf:"bytes,2,opt,name=Foreground,proto3" json:"Foreground,omitempty"`
	Background           *Attribute `protobuf:"bytes,3,opt,name=Background,proto3" json:"Background,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Cell) Reset()         { *m = Cell{} }
func (m *Cell) String() string { return proto.CompactTextString(m) }
func (*Cell) ProtoMessage()    {}
func (*Cell) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5264c19600bbd1c, []int{1}
}

func (m *Cell) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cell.Unmarshal(m, b)
}
func (m *Cell) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cell.Marshal(b, m, deterministic)
}
func (m *Cell) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cell.Merge(m, src)
}
func (m *Cell) XXX_Size() int {
	return xxx_messageInfo_Cell.Size(m)
}
func (m *Cell) XXX_DiscardUnknown() {
	xxx_messageInfo_Cell.DiscardUnknown(m)
}

var xxx_messageInfo_Cell proto.InternalMessageInfo

func (m *Cell) GetCharacter() uint32 {
	if m != nil {
		return m.Character
	}
	return 0
}

func (m *Cell) GetForeground() *Attribute {
	if m != nil {
		return m.Foreground
	}
	return nil
}

func (m *Cell) GetBackground() *Attribute {
	if m != nil {
		return m.Background
	}
	return nil
}

type CellRow struct {
	Cells                []*Cell  `protobuf:"bytes,1,rep,name=cells,proto3" json:"cells,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CellRow) Reset()         { *m = CellRow{} }
func (m *CellRow) String() string { return proto.CompactTextString(m) }
func (*CellRow) ProtoMessage()    {}
func (*CellRow) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5264c19600bbd1c, []int{2}
}

func (m *CellRow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CellRow.Unmarshal(m, b)
}
func (m *CellRow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CellRow.Marshal(b, m, deterministic)
}
func (m *CellRow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CellRow.Merge(m, src)
}
func (m *CellRow) XXX_Size() int {
	return xxx_messageInfo_CellRow.Size(m)
}
func (m *CellRow) XXX_DiscardUnknown() {
	xxx_messageInfo_CellRow.DiscardUnknown(m)
}

var xxx_messageInfo_CellRow proto.InternalMessageInfo

func (m *CellRow) GetCells() []*Cell {
	if m != nil {
		return m.Cells
	}
	return nil
}

type Coordinates struct {
	X                    int32    `protobuf:"varint,1,opt,name=X,proto3" json:"X,omitempty"`
	Y                    int32    `protobuf:"varint,2,opt,name=Y,proto3" json:"Y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Coordinates) Reset()         { *m = Coordinates{} }
func (m *Coordinates) String() string { return proto.CompactTextString(m) }
func (*Coordinates) ProtoMessage()    {}
func (*Coordinates) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5264c19600bbd1c, []int{3}
}

func (m *Coordinates) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Coordinates.Unmarshal(m, b)
}
func (m *Coordinates) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Coordinates.Marshal(b, m, deterministic)
}
func (m *Coordinates) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Coordinates.Merge(m, src)
}
func (m *Coordinates) XXX_Size() int {
	return xxx_messageInfo_Coordinates.Size(m)
}
func (m *Coordinates) XXX_DiscardUnknown() {
	xxx_messageInfo_Coordinates.DiscardUnknown(m)
}

var xxx_messageInfo_Coordinates proto.InternalMessageInfo

func (m *Coordinates) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Coordinates) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type Event struct {
	Type                 Event_Type   `protobuf:"varint,1,opt,name=type,proto3,enum=proto.Event_Type" json:"type,omitempty"`
	Mod                  Event_Mod    `protobuf:"varint,2,opt,name=mod,proto3,enum=proto.Event_Mod" json:"mod,omitempty"`
	Key                  Event_Key    `protobuf:"varint,3,opt,name=key,proto3,enum=proto.Event_Key" json:"key,omitempty"`
	Char                 uint32       `protobuf:"varint,4,opt,name=Char,proto3" json:"Char,omitempty"`
	Mouse                *Event_Mouse `protobuf:"bytes,5,opt,name=mouse,proto3" json:"mouse,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5264c19600bbd1c, []int{4}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetType() Event_Type {
	if m != nil {
		return m.Type
	}
	return Event_TypeKey
}

func (m *Event) GetMod() Event_Mod {
	if m != nil {
		return m.Mod
	}
	return Event_None
}

func (m *Event) GetKey() Event_Key {
	if m != nil {
		return m.Key
	}
	return Event_F1
}

func (m *Event) GetChar() uint32 {
	if m != nil {
		return m.Char
	}
	return 0
}

func (m *Event) GetMouse() *Event_Mouse {
	if m != nil {
		return m.Mouse
	}
	return nil
}

type Event_Mouse struct {
	X                    int32    `protobuf:"varint,1,opt,name=X,proto3" json:"X,omitempty"`
	Y                    int32    `protobuf:"varint,2,opt,name=Y,proto3" json:"Y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event_Mouse) Reset()         { *m = Event_Mouse{} }
func (m *Event_Mouse) String() string { return proto.CompactTextString(m) }
func (*Event_Mouse) ProtoMessage()    {}
func (*Event_Mouse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5264c19600bbd1c, []int{4, 0}
}

func (m *Event_Mouse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event_Mouse.Unmarshal(m, b)
}
func (m *Event_Mouse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event_Mouse.Marshal(b, m, deterministic)
}
func (m *Event_Mouse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event_Mouse.Merge(m, src)
}
func (m *Event_Mouse) XXX_Size() int {
	return xxx_messageInfo_Event_Mouse.Size(m)
}
func (m *Event_Mouse) XXX_DiscardUnknown() {
	xxx_messageInfo_Event_Mouse.DiscardUnknown(m)
}

var xxx_messageInfo_Event_Mouse proto.InternalMessageInfo

func (m *Event_Mouse) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Event_Mouse) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func init() {
	proto.RegisterEnum("proto.Attribute_Colors", Attribute_Colors_name, Attribute_Colors_value)
	proto.RegisterEnum("proto.Attribute_Attrs", Attribute_Attrs_name, Attribute_Attrs_value)
	proto.RegisterEnum("proto.Event_Type", Event_Type_name, Event_Type_value)
	proto.RegisterEnum("proto.Event_Mod", Event_Mod_name, Event_Mod_value)
	proto.RegisterEnum("proto.Event_Key", Event_Key_name, Event_Key_value)
	proto.RegisterType((*Attribute)(nil), "proto.Attribute")
	proto.RegisterType((*Cell)(nil), "proto.Cell")
	proto.RegisterType((*CellRow)(nil), "proto.CellRow")
	proto.RegisterType((*Coordinates)(nil), "proto.Coordinates")
	proto.RegisterType((*Event)(nil), "proto.Event")
	proto.RegisterType((*Event_Mouse)(nil), "proto.Event.Mouse")
}

func init() { proto.RegisterFile("proto/term.proto", fileDescriptor_a5264c19600bbd1c) }

var fileDescriptor_a5264c19600bbd1c = []byte{
	// 897 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x94, 0x5d, 0x57, 0xdb, 0x46,
	0x13, 0xc7, 0x91, 0x6d, 0x19, 0xbc, 0x06, 0xf2, 0x67, 0x9f, 0x3c, 0x2d, 0x4d, 0xd3, 0x96, 0x28,
	0x49, 0x4b, 0xda, 0x94, 0x80, 0x79, 0xef, 0x3b, 0x36, 0x10, 0x08, 0x71, 0x9a, 0x2a, 0x50, 0xa0,
	0x77, 0xc2, 0x1a, 0xc0, 0x07, 0xa1, 0x75, 0xa5, 0x75, 0x38, 0xfe, 0x06, 0xfd, 0x0a, 0xbd, 0xe9,
	0xe7, 0xcc, 0x65, 0xcf, 0x8c, 0xbc, 0xa6, 0x27, 0xe7, 0xb4, 0x57, 0xf3, 0x9b, 0xf9, 0xcf, 0xce,
	0xce, 0xce, 0x6a, 0xa5, 0xd0, 0xcb, 0x8c, 0x35, 0xcf, 0x2c, 0x65, 0xd7, 0x0b, 0x82, 0xda, 0x17,
	0x13, 0xbc, 0xf3, 0x54, 0x6d, 0xcb, 0xda, 0xac, 0x7b, 0xd6, 0xb7, 0xa4, 0xef, 0x2a, 0xff, 0x3c,
	0x89, 0x2e, 0xf2, 0x59, 0x6f, 0xce, 0x9b, 0x9f, 0x0a, 0x0b, 0x27, 0xf8, 0xd3, 0x53, 0xd5, 0x96,
	0x49, 0x4c, 0x96, 0x6b, 0xa8, 0x49, 0xa1, 0x6d, 0x3a, 0x8f, 0xfa, 0x89, 0xc5, 0x98, 0x9e, 0x56,
	0x4a, 0x22, 0xcd, 0x24, 0xea, 0x5c, 0xc1, 0xd3, 0x93, 0x6a, 0x42, 0xfc, 0x90, 0x62, 0x94, 0x46,
	0xea, 0xf3, 0x8c, 0x28, 0x45, 0x59, 0xdf, 0x51, 0x75, 0xf1, 0x4f, 0x29, 0x49, 0xcc, 0x0d, 0x2a,
	0x7a, 0x4a, 0xd5, 0x86, 0xcb, 0xfb, 0x04, 0x7f, 0x54, 0xbf, 0x1d, 0x5d, 0x50, 0x6a, 0x23, 0x54,
	0x47, 0x09, 0xad, 0x41, 0x94, 0x62, 0x7c, 0x54, 0xf0, 0xf8, 0xb2, 0x6b, 0x09, 0x13, 0xc1, 0xa6,
	0xf2, 0xb9, 0xfd, 0x9c, 0xf7, 0x65, 0x68, 0x9a, 0x24, 0xc6, 0x98, 0x9e, 0x51, 0x53, 0xec, 0x1d,
	0xa5, 0x31, 0x65, 0x49, 0x37, 0x25, 0x78, 0xbc, 0x35, 0x87, 0x42, 0x7a, 0x4b, 0x59, 0x4e, 0x28,
	0x05, 0x7f, 0x78, 0xaa, 0xd2, 0xa2, 0x24, 0xd1, 0xf7, 0x55, 0xad, 0x75, 0x19, 0x65, 0x51, 0xc7,
	0x52, 0x36, 0x3c, 0xf9, 0x6d, 0x40, 0x2f, 0x2a, 0xb5, 0x6b, 0x32, 0xba, 0xc8, 0x4c, 0x3f, 0x8d,
	0x67, 0x4b, 0x73, 0xde, 0x7c, 0xbd, 0x81, 0x62, 0x88, 0x0b, 0xa3, 0xc9, 0x85, 0xff, 0xc8, 0xe1,
	0x15, 0xcd, 0xa8, 0x73, 0x35, 0x5c, 0x51, 0xfe, 0xb7, 0x15, 0xb7, 0x39, 0xc1, 0x53, 0x35, 0xce,
	0x9d, 0x84, 0xe6, 0x46, 0x3f, 0x50, 0x7e, 0x87, 0x92, 0x84, 0xaf, 0xa0, 0x3c, 0x5f, 0x6f, 0xd4,
	0x87, 0xeb, 0x44, 0x2e, 0x94, 0xe0, 0x09, 0x0f, 0xd1, 0x64, 0x71, 0x37, 0x8d, 0x2c, 0xf1, 0xc9,
	0xbd, 0x13, 0x69, 0xdb, 0x0f, 0xbd, 0x13, 0xf6, 0x4e, 0xa5, 0x4b, 0x3f, 0xf4, 0x4e, 0x83, 0xbf,
	0x6a, 0xca, 0xdf, 0x79, 0x4b, 0xa9, 0xd5, 0x8f, 0x55, 0xc5, 0x0e, 0x7a, 0x24, 0x89, 0xd3, 0x8d,
	0x99, 0x61, 0x59, 0xd1, 0x16, 0x0e, 0x07, 0x3d, 0x0a, 0x45, 0xd6, 0x81, 0x2a, 0x5f, 0x9b, 0xe2,
	0x98, 0xd3, 0xa3, 0xa6, 0x8b, 0xac, 0xb6, 0x89, 0x43, 0x16, 0x39, 0xe7, 0x8a, 0x06, 0x72, 0xb0,
	0xf7, 0x73, 0x0e, 0x68, 0x10, 0xb2, 0xa8, 0xb5, 0xaa, 0xf0, 0x08, 0x67, 0x2b, 0x32, 0x4e, 0x61,
	0x3d, 0xaf, 0xfc, 0x6b, 0xd3, 0xcf, 0x69, 0xd6, 0x97, 0x91, 0xe8, 0xf7, 0xaa, 0xf7, 0x73, 0x0a,
	0x8b, 0x84, 0x7b, 0x0f, 0x95, 0x2f, 0xfe, 0x7f, 0x9e, 0x2d, 0x50, 0x15, 0x6e, 0x5c, 0xd7, 0xd5,
	0x38, 0xdb, 0x03, 0x1a, 0x60, 0x8c, 0x3f, 0x17, 0x76, 0x64, 0x35, 0x4a, 0xc1, 0x23, 0x55, 0x6e,
	0x9b, 0x58, 0x4f, 0xa8, 0xca, 0x2b, 0x93, 0x12, 0xc6, 0xf4, 0xb8, 0x2a, 0x6f, 0x25, 0x16, 0x9e,
	0x56, 0xaa, 0xda, 0x36, 0xb6, 0x6b, 0x52, 0x94, 0x82, 0x77, 0x55, 0x55, 0x3e, 0xa0, 0x81, 0xae,
	0xaa, 0xd2, 0xee, 0x12, 0xc6, 0xc4, 0x36, 0xe0, 0x89, 0x5d, 0x46, 0x49, 0xec, 0x0a, 0xca, 0x62,
	0x57, 0x51, 0x11, 0xbb, 0x06, 0x5f, 0xec, 0x3a, 0xaa, 0x62, 0x37, 0x30, 0x2e, 0x76, 0x13, 0x13,
	0xbc, 0xc9, 0xee, 0xd2, 0x22, 0x6a, 0x05, 0x2c, 0x41, 0x15, 0xd0, 0x40, 0x9d, 0xb7, 0xdd, 0x4f,
	0x73, 0xca, 0x2c, 0x26, 0x99, 0xb7, 0x29, 0x21, 0x4b, 0x98, 0xe2, 0x0e, 0xf7, 0xcc, 0x35, 0x61,
	0x9a, 0x53, 0x77, 0xd2, 0x18, 0x77, 0x38, 0xf4, 0xfa, 0xa2, 0xdf, 0x03, 0x0a, 0x8a, 0x53, 0xcc,
	0xf0, 0x59, 0xb7, 0xb2, 0xcc, 0xdc, 0x1c, 0xf5, 0xa0, 0xf9, 0xac, 0xe2, 0x6c, 0x9b, 0x9b, 0x14,
	0xff, 0x1b, 0xb9, 0x2f, 0xe9, 0xdc, 0xe2, 0x2e, 0xbf, 0x14, 0x71, 0xc3, 0xee, 0xc5, 0xa5, 0xc5,
	0xff, 0x59, 0x96, 0xa9, 0x88, 0xfc, 0x01, 0x3f, 0x07, 0x71, 0xdb, 0xdd, 0x38, 0x4e, 0x08, 0x1f,
	0x72, 0x7e, 0x71, 0x07, 0x92, 0x3f, 0xcb, 0x4f, 0xb1, 0xf0, 0x29, 0xa1, 0x28, 0x27, 0x7c, 0x34,
	0x8a, 0x1c, 0x5f, 0x12, 0x25, 0x47, 0x3d, 0xdc, 0xd3, 0x5a, 0x4d, 0xdf, 0x46, 0xa4, 0x8d, 0x8f,
	0xe5, 0xc1, 0xda, 0x2c, 0x39, 0xec, 0x26, 0x31, 0xe1, 0xbe, 0xae, 0x29, 0x9f, 0xdd, 0x06, 0x3e,
	0x71, 0xca, 0x9b, 0x5e, 0xd4, 0x21, 0x7c, 0xea, 0x94, 0x2d, 0x7c, 0xe6, 0xb0, 0x89, 0x39, 0x87,
	0x2d, 0x3c, 0x70, 0xb8, 0x8d, 0xc0, 0xe1, 0x0e, 0x1e, 0x3a, 0xdc, 0xc5, 0x23, 0x87, 0xcf, 0xf1,
	0x98, 0x6b, 0xf3, 0x7b, 0xca, 0xa5, 0xf6, 0xe7, 0x4e, 0xd9, 0xc3, 0x17, 0x3c, 0xcf, 0xc3, 0xe8,
	0x0c, 0xf3, 0x2e, 0xb6, 0x8f, 0x27, 0x0e, 0x5f, 0xe0, 0x4b, 0x87, 0x07, 0xf8, 0xca, 0xe1, 0x4b,
	0x3c, 0x65, 0xdc, 0x49, 0x2d, 0x65, 0xf8, 0xda, 0x45, 0xdb, 0x58, 0x70, 0xf8, 0x0a, 0xcf, 0x1c,
	0xfe, 0x8c, 0x45, 0x87, 0xaf, 0xb1, 0xe4, 0xf0, 0x17, 0x34, 0x1c, 0x86, 0x58, 0x76, 0xf8, 0x06,
	0x2b, 0x0e, 0x0f, 0xb1, 0xea, 0xf0, 0x08, 0x6b, 0x0e, 0x7f, 0xc5, 0xba, 0xc3, 0x63, 0x6c, 0x38,
	0x3c, 0xc1, 0xa6, 0xc3, 0x53, 0x7c, 0xe3, 0xf0, 0x37, 0x7c, 0x2b, 0x5f, 0x4a, 0xde, 0xc1, 0x77,
	0x7c, 0x0d, 0xd2, 0x78, 0xfe, 0x7b, 0x33, 0x8b, 0x3a, 0x57, 0x64, 0xf1, 0xbd, 0xcb, 0x5b, 0xc6,
	0x0f, 0x0e, 0x57, 0xf0, 0x23, 0xff, 0x17, 0x65, 0xd0, 0x3c, 0xaa, 0x24, 0xca, 0x2f, 0xf1, 0x93,
	0x53, 0x57, 0xb1, 0xe5, 0xea, 0x84, 0xb7, 0x75, 0x9a, 0x4e, 0x5e, 0x43, 0xcb, 0xe1, 0x3a, 0xb6,
	0x47, 0x57, 0x29, 0x35, 0x76, 0xdc, 0x42, 0xf9, 0xdd, 0xe6, 0x1d, 0x93, 0x11, 0x76, 0x39, 0xbb,
	0xb8, 0xe9, 0x3d, 0xfe, 0xb4, 0x46, 0x97, 0xd3, 0xc0, 0xbe, 0x2b, 0xb4, 0x81, 0x17, 0x67, 0x55,
	0xf9, 0x07, 0x2c, 0xff, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xa5, 0x63, 0x6e, 0x58, 0xa1, 0x06, 0x00,
	0x00,
}
