// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tui.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Key struct {
	Event                *Event   `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Key) Reset()         { *m = Key{} }
func (m *Key) String() string { return proto.CompactTextString(m) }
func (*Key) ProtoMessage()    {}
func (*Key) Descriptor() ([]byte, []int) {
	return fileDescriptor_d00f7f131e631179, []int{0}
}

func (m *Key) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Key.Unmarshal(m, b)
}
func (m *Key) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Key.Marshal(b, m, deterministic)
}
func (m *Key) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Key.Merge(m, src)
}
func (m *Key) XXX_Size() int {
	return xxx_messageInfo_Key.Size(m)
}
func (m *Key) XXX_DiscardUnknown() {
	xxx_messageInfo_Key.DiscardUnknown(m)
}

var xxx_messageInfo_Key proto.InternalMessageInfo

func (m *Key) GetEvent() *Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *Key) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Key) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Manual struct {
	Summary              string   `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	Keys                 []*Key   `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Manual) Reset()         { *m = Manual{} }
func (m *Manual) String() string { return proto.CompactTextString(m) }
func (*Manual) ProtoMessage()    {}
func (*Manual) Descriptor() ([]byte, []int) {
	return fileDescriptor_d00f7f131e631179, []int{1}
}

func (m *Manual) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Manual.Unmarshal(m, b)
}
func (m *Manual) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Manual.Marshal(b, m, deterministic)
}
func (m *Manual) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Manual.Merge(m, src)
}
func (m *Manual) XXX_Size() int {
	return xxx_messageInfo_Manual.Size(m)
}
func (m *Manual) XXX_DiscardUnknown() {
	xxx_messageInfo_Manual.DiscardUnknown(m)
}

var xxx_messageInfo_Manual proto.InternalMessageInfo

func (m *Manual) GetSummary() string {
	if m != nil {
		return m.Summary
	}
	return ""
}

func (m *Manual) GetKeys() []*Key {
	if m != nil {
		return m.Keys
	}
	return nil
}

type Coordinates struct {
	X                    int32    `protobuf:"varint,1,opt,name=X,proto3" json:"X,omitempty"`
	Y                    int32    `protobuf:"varint,2,opt,name=Y,proto3" json:"Y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Coordinates) Reset()         { *m = Coordinates{} }
func (m *Coordinates) String() string { return proto.CompactTextString(m) }
func (*Coordinates) ProtoMessage()    {}
func (*Coordinates) Descriptor() ([]byte, []int) {
	return fileDescriptor_d00f7f131e631179, []int{2}
}

func (m *Coordinates) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Coordinates.Unmarshal(m, b)
}
func (m *Coordinates) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Coordinates.Marshal(b, m, deterministic)
}
func (m *Coordinates) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Coordinates.Merge(m, src)
}
func (m *Coordinates) XXX_Size() int {
	return xxx_messageInfo_Coordinates.Size(m)
}
func (m *Coordinates) XXX_DiscardUnknown() {
	xxx_messageInfo_Coordinates.DiscardUnknown(m)
}

var xxx_messageInfo_Coordinates proto.InternalMessageInfo

func (m *Coordinates) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Coordinates) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func init() {
	proto.RegisterType((*Key)(nil), "proto.Key")
	proto.RegisterType((*Manual)(nil), "proto.Manual")
	proto.RegisterType((*Coordinates)(nil), "proto.Coordinates")
}

func init() { proto.RegisterFile("tui.proto", fileDescriptor_d00f7f131e631179) }

var fileDescriptor_d00f7f131e631179 = []byte{
	// 202 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8e, 0xb1, 0x4e, 0x04, 0x21,
	0x10, 0x86, 0x03, 0x2b, 0x67, 0x76, 0xb8, 0x58, 0x50, 0x11, 0x0b, 0x43, 0xa8, 0xd6, 0xe6, 0x8a,
	0xf3, 0x0d, 0x34, 0x56, 0x17, 0x1b, 0xaa, 0xdd, 0x58, 0xa1, 0x4c, 0x41, 0x74, 0x61, 0x03, 0xac,
	0x09, 0x6f, 0x6f, 0x96, 0xd5, 0xe4, 0xaa, 0xc9, 0xff, 0x7d, 0x99, 0xf9, 0x07, 0xfa, 0xb2, 0xfa,
	0xd3, 0x92, 0x62, 0x89, 0x82, 0xb5, 0x71, 0x0f, 0x05, 0xd3, 0xbc, 0x23, 0xfd, 0x0e, 0xdd, 0x05,
	0xab, 0xd0, 0xc0, 0xf0, 0x07, 0x43, 0x91, 0x44, 0x91, 0x81, 0x9f, 0x8f, 0xbb, 0x3d, 0xbd, 0x6e,
	0xcc, 0xec, 0x4a, 0xdc, 0x01, 0xf5, 0x4e, 0x52, 0x45, 0x86, 0xde, 0x50, 0xef, 0x84, 0x02, 0xee,
	0x30, 0x7f, 0x26, 0xbf, 0x14, 0x1f, 0x83, 0xec, 0x9a, 0xb8, 0x46, 0xfa, 0x19, 0x0e, 0x6f, 0x36,
	0xac, 0xf6, 0x5b, 0x48, 0xb8, 0xcd, 0xeb, 0x3c, 0xdb, 0x54, 0x5b, 0x43, 0x6f, 0xfe, 0xa3, 0x78,
	0x80, 0x9b, 0x2f, 0xac, 0x59, 0x52, 0xd5, 0x0d, 0xfc, 0x0c, 0x7f, 0xc5, 0x17, 0xac, 0xa6, 0x71,
	0xfd, 0x08, 0xfc, 0x25, 0xc6, 0xe4, 0x7c, 0xb0, 0x05, 0xb3, 0x38, 0x02, 0x19, 0xdb, 0x09, 0x66,
	0xc8, 0xb8, 0xa5, 0xa9, 0x7d, 0xc4, 0x0c, 0x99, 0x3e, 0x0e, 0x6d, 0xf7, 0xe9, 0x37, 0x00, 0x00,
	0xff, 0xff, 0x33, 0x08, 0xf1, 0x61, 0xf2, 0x00, 0x00, 0x00,
}
