// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/tui.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Key struct {
	Event                *Event   `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Key) Reset()         { *m = Key{} }
func (m *Key) String() string { return proto.CompactTextString(m) }
func (*Key) ProtoMessage()    {}
func (*Key) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e55ed91ef169e4a, []int{0}
}

func (m *Key) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Key.Unmarshal(m, b)
}
func (m *Key) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Key.Marshal(b, m, deterministic)
}
func (m *Key) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Key.Merge(m, src)
}
func (m *Key) XXX_Size() int {
	return xxx_messageInfo_Key.Size(m)
}
func (m *Key) XXX_DiscardUnknown() {
	xxx_messageInfo_Key.DiscardUnknown(m)
}

var xxx_messageInfo_Key proto.InternalMessageInfo

func (m *Key) GetEvent() *Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *Key) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Key) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Manual struct {
	Summary              string   `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	Keys                 []*Key   `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Manual) Reset()         { *m = Manual{} }
func (m *Manual) String() string { return proto.CompactTextString(m) }
func (*Manual) ProtoMessage()    {}
func (*Manual) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e55ed91ef169e4a, []int{1}
}

func (m *Manual) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Manual.Unmarshal(m, b)
}
func (m *Manual) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Manual.Marshal(b, m, deterministic)
}
func (m *Manual) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Manual.Merge(m, src)
}
func (m *Manual) XXX_Size() int {
	return xxx_messageInfo_Manual.Size(m)
}
func (m *Manual) XXX_DiscardUnknown() {
	xxx_messageInfo_Manual.DiscardUnknown(m)
}

var xxx_messageInfo_Manual proto.InternalMessageInfo

func (m *Manual) GetSummary() string {
	if m != nil {
		return m.Summary
	}
	return ""
}

func (m *Manual) GetKeys() []*Key {
	if m != nil {
		return m.Keys
	}
	return nil
}

func init() {
	proto.RegisterType((*Key)(nil), "proto.Key")
	proto.RegisterType((*Manual)(nil), "proto.Manual")
}

func init() { proto.RegisterFile("proto/tui.proto", fileDescriptor_4e55ed91ef169e4a) }

var fileDescriptor_4e55ed91ef169e4a = []byte{
	// 175 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0x29, 0xcd, 0xd4, 0x03, 0xb3, 0x84, 0x58, 0xc1, 0x94, 0x94, 0x00, 0x54, 0x3c,
	0xb5, 0x28, 0x17, 0x22, 0xa1, 0x14, 0xcd, 0xc5, 0xec, 0x9d, 0x5a, 0x29, 0xa4, 0xc4, 0xc5, 0x9a,
	0x5a, 0x96, 0x9a, 0x57, 0x22, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x6d, 0xc4, 0x03, 0x91, 0xd5, 0x73,
	0x05, 0x89, 0x05, 0x41, 0xa4, 0x84, 0xf8, 0xb8, 0x98, 0x32, 0x53, 0x24, 0x98, 0x14, 0x18, 0x35,
	0x38, 0x83, 0x98, 0x32, 0x53, 0x84, 0x14, 0xb8, 0xb8, 0x53, 0x52, 0x8b, 0x93, 0x8b, 0x32, 0x0b,
	0x4a, 0x32, 0xf3, 0xf3, 0x24, 0x98, 0xc1, 0x12, 0xc8, 0x42, 0x4a, 0x4e, 0x5c, 0x6c, 0xbe, 0x89,
	0x79, 0xa5, 0x89, 0x39, 0x42, 0x12, 0x5c, 0xec, 0xc5, 0xa5, 0xb9, 0xb9, 0x89, 0x45, 0x95, 0x60,
	0x1b, 0x38, 0x83, 0x60, 0x5c, 0x21, 0x39, 0x2e, 0x96, 0xec, 0xd4, 0xca, 0x62, 0x09, 0x26, 0x05,
	0x66, 0x0d, 0x6e, 0x23, 0x2e, 0xa8, 0xc5, 0xde, 0xa9, 0x95, 0x41, 0x60, 0xf1, 0x24, 0x36, 0xb0,
	0x80, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x5c, 0xad, 0x08, 0x02, 0xd3, 0x00, 0x00, 0x00,
}
