syntax = "proto3";

option go_package = "unstable.build/go-tui/extension/rpc";

package extension;

message Permission {
	string id = 1;
}
message PermissionGrant {
	string id = 1;
	string address = 2;
}

message PermRequest {
    bytes config = 1;
}
message PermResponse {
	repeated Permission perms = 1;
}

message OnPermGrantRequest {
	repeated PermissionGrant granted = 1;
	repeated Permission denied = 2;
}
message OnPermGrantResponse{}

message ShutdownRequest {
	string reason = 1;
}
message ShutdownResponse {}

message HealthRequest {}
message HealthResponse {}

service Grantee {
	rpc Permissions(PermRequest) returns (PermResponse);
	rpc OnGrant(OnPermGrantRequest) returns (OnPermGrantResponse);
	rpc Shutdown(ShutdownRequest) returns (ShutdownResponse);
	rpc Health(HealthRequest) returns (HealthResponse);
}
