package notifications

import (
	"testing"
	"time"

	"unstable.build/go-tui/component"
	"unstable.build/go-tui/term"
	testutil "unstable.build/go-tui/util/test"
)

func TestComponentDraw(t *testing.T) {
	inner := &component.TestComponent{Ch: 'X'}

	c := New(inner, Config{
		AutoClose:   1 * time.Hour,
		ProgressBar: true,
		Width:       10,
	})
	c.Resize(40, 15)

	w := term.NewStringWriter(40, 15)

	tests := []testutil.ComponentTestCase{
		{
			nil, `
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX`,
		}, {
			func() { c.Notify(LevelInfo, "hello world") }, `
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX┌────────┐
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ hello  │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ world  │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX└────────┘
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX`,
		}, {
			func() { c.Notify(LevelInfo, "Does not fit I think") }, `
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX┌────────┐
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│Does    │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│not fit │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│I think │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX└────────┘
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX┌────────┐
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ hello  │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ world  │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX└────────┘
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX`,
		}, {
			func() { c.Notify(LevelInfo, "This time it won't fit for sure") }, `
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX┌────────┐
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│This    │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│time it │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│won't   │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│fit for │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX└────────┘
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX┌────────┐
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│Does    │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│not fit │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│I think │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX└────────┘
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX┌────────┐
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ hello  │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ world  │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX└────────┘`,
		}, {
			func() { c.Notify(LevelInfo, "This time it won't fit for sure") }, `
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX┌────────┐
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│This    │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│time it │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│won't   │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│fit for │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX└────────┘
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX┌────────┐
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│This    │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│time it │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│won't   │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│fit for │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX└────────┘
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX┌────────┐
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│Does    │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│not fit │`,
		}, {
			func() { c.Resize(20, 10) }, `
XXXXXXXXXX┌────────┐                    
XXXXXXXXXX│This    │                    
XXXXXXXXXX│time it │                    
XXXXXXXXXX│won't   │                    
XXXXXXXXXX│fit for │                    
XXXXXXXXXX└────────┘                    
XXXXXXXXXX┌────────┐                    
XXXXXXXXXX│This    │                    
XXXXXXXXXX│time it │                    
XXXXXXXXXX│won't   │                    
                                        
                                        
                                        
                                        
                                        `,
		}, {
			func() { c.Resize(40, 15) }, `
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX┌────────┐
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│This    │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│time it │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│won't   │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│fit for │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX└────────┘
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX┌────────┐
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│This    │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│time it │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│won't   │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│fit for │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX└────────┘
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX┌────────┐
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│Does    │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│not fit │`,
		},
	}

	testutil.TestComponent(t, c, w, tests)
}
