package notifications

import (
	"testing"
	"time"

	"unstable.build/go-tui/component"
	"unstable.build/go-tui/term"
	testutil "unstable.build/go-tui/util/test"
)

func TestComponentDraw(t *testing.T) {
	inner := &component.TestComponent{Ch: 'X'}

	c := New(inner, Config{
		AutoClose:   1 * time.Hour,
		ProgressBar: true,
		Width:       10,
	})
	c.Resize(40, 15)

	w := term.NewStringWriter(40, 15)

	tests := []testutil.ComponentTestCase{
		{
			nil, `
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX`,
		}, {
			func() { c.Notify(LevelInfo, "hello world") }, `
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX┌────────┐
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ hello  │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ world  │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX└════════┘
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX`,
		}, {
			func() { c.Notify(LevelInfo, "Does not fit I think") }, `
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX┌────────┐
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ Does   │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ not    │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ fit I  │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ think  │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX└════════┘
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX┌────────┐
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ hello  │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ world  │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX└════════┘
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX`,
		}, {
			func() { c.Notify(LevelInfo, "This time it won't fit for sure") }, `
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX┌────────┐
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ This   │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ time   │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ it     │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ won't  │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ fit    │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ for    │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ sure   │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX└════════┘
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX┌────────┐
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ Does   │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ not    │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ fit I  │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ think  │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX└════════┘`,
		}, {
			func() { c.Notify(LevelInfo, "This time it won't fit for SURE SURE") }, `
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX┌────────┐
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ This   │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ time   │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ it     │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ won't  │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ fit    │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ for    │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ SURE   │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ SURE   │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX└════════┘
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX┌────────┐
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ This   │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ time   │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ it     │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ won't  │`,
		}, {
			func() { c.Resize(20, 10) }, `
XXXXXXXXXX┌────────┐                    
XXXXXXXXXX│ This   │                    
XXXXXXXXXX│ time   │                    
XXXXXXXXXX│ it     │                    
XXXXXXXXXX│ won't  │                    
XXXXXXXXXX│ fit    │                    
XXXXXXXXXX│ for    │                    
XXXXXXXXXX│ SURE   │                    
XXXXXXXXXX│ SURE   │                    
XXXXXXXXXX└════════┘                    
                                        
                                        
                                        
                                        
                                        `,
		}, {
			func() { c.Resize(40, 15) }, `
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX┌────────┐
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ This   │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ time   │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ it     │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ won't  │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ fit    │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ for    │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ SURE   │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ SURE   │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX└════════┘
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX┌────────┐
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ This   │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ time   │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ it     │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ won't  │`,
		}, {
			func() {
				c.PauseAll()
				c.ResumeAll()
				c.PauseAll()
				c.ResumeAll()
			}, /* simply tests data races and deadlocks */ `
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX┌────────┐
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ This   │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ time   │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ it     │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ won't  │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ fit    │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ for    │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ SURE   │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ SURE   │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX└════════┘
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX┌────────┐
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ This   │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ time   │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ it     │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ won't  │`,
		}, {
			func() { c.CloseAll() }, `
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX`,
		},
	}

	testutil.TestComponent(t, c, w, tests)
}
