; Generated by tools/expand-inherits.sh
; kind=folds lang=zig
; Inherits chains have been inlined; do not re-expand.

; --- begin zig (folds) (from tree-sitter-zig/queries/folds.scm) ---
[
  (block)
  (switch_expression)
  (initializer_list)
  (asm_expression)
  (multiline_string)
  (if_statement)
  (while_statement)
  (for_statement)
  (if_expression)
  (else_clause)
  (for_expression)
  (while_expression)
  (if_type_expression)
  (function_signature)
  (parameters)
  (call_expression)
  (struct_declaration)
  (opaque_declaration)
  (enum_declaration)
  (union_declaration)
  (error_set_declaration)
] @fold
; --- end zig (folds) ---
